/**
 * modules/tournaments/tournament-matches.js - Tournament Match Operations
 * CANONICAL match mutation API for tournaments.
 *
 * Path: js/modules/tournaments/tournament-matches.js
 *
 * RESPONSIBILITIES:
 *   - Match CRUD (create, update, delete)
 *   - Match completion (per-participant pass/fail/retry)
 *   - Team match completion (team-level + member-level results)
 *   - Auto-generation of matches from an eligible pool
 *   - Internal pure builders for Core.addRound
 *   - Round promotion: when the last match in a round completes, the
 *     round's status is set to 'completed'
 *
 * NOT RESPONSIBILITIES:
 *   - Tournament-level status transitions (TournamentCore)
 *   - Round addition/removal (TournamentCore)
 *   - Persistence (MutationPipeline)
 *   - Rendering, notifications
 *
 * IDENTITY:
 *   Rounds and matches carry stable IDs generated by TournamentSchema.
 *   All public commands accept IDs, not array indices. Lookup goes
 *   through Schema.findRoundById / Schema.findMatchById.
 *
 * ROUND STATUS PROMOTION:
 *   Completing a match does not automatically complete the tournament.
 *   It does automatically promote the round to 'completed' when every
 *   match in the round is completed. This is required by
 *   TournamentRules.validateCompletionReadiness, which requires each
 *   round's status to be 'completed' before the tournament can be
 *   marked complete. Without this promotion, no tournament could ever
 *   be completed.
 *
 * MATCH TYPES:
 *   'standard'    : legacy 2-participant match. Read-only compat.
 *   'group_exam'  : open assessment. 2+ participants. Per-participant
 *                   results (pass | fail | retry).
 *   'team_vs_team': adversarial team match. 2+ teams. Two-layer
 *                   results: teamResults + individualResults.
 *
 * PAIR EXAM:
 *   'group_exam' with isPairExam: true. Pairings partition participants
 *   into groups of 2 or 3.
 *
 * RESULT VOCABULARY:
 *   'pass' | 'retry' | 'fail'. Advancement = 'pass' or 'retry'.
 *
 * DEPENDENCIES (MANDATORY):
 *   - window.TournamentConstants
 *   - window.TournamentSchema
 *   - window.TournamentLifecycle
 *   - window.TournamentRules
 *   - window.TournamentQueries
 *   - window.MutationPipeline
 *   - window.ObjectUtils
 *   - window.IdUtils
 *
 * USAGE:
 *   var Matches = window.TournamentMatches;
 *
 *   Matches.createMatch('tourn_123', 'round_abc', {
 *       participants: ['char_1', 'char_2']
 *   });
 *
 *   Matches.completeMatch('tourn_123', 'round_abc', 'match_xyz', {
 *       results: { char_1: 'pass', char_2: 'retry' }
 *   });
 *
 *   Matches.generateMatches('tourn_123', 'round_abc', { matchSize: 2 });
 */

(function() {
    'use strict';

    if (window.__tournamentMatchesLoaded) {
        return;
    }

    // ============================================================
    // MANDATORY DEPENDENCIES
    // ============================================================

    var Constants = window.TournamentConstants;
    var Schema = window.TournamentSchema;
    var Lifecycle = window.TournamentLifecycle;
    var Rules = window.TournamentRules;
    var Queries = window.TournamentQueries;
    var MutationPipeline = window.MutationPipeline;
    var ObjectUtils = window.ObjectUtils;
    var IdUtils = window.IdUtils;

    var _missing = [];

    if (!Constants) { _missing.push('TournamentConstants'); }
    if (!Schema || typeof Schema.findRoundById !== 'function') {
        _missing.push('TournamentSchema.findRoundById');
    }
    if (!Schema || typeof Schema.findMatchById !== 'function') {
        _missing.push('TournamentSchema.findMatchById');
    }
    if (!Schema || typeof Schema.generateRoundId !== 'function') {
        _missing.push('TournamentSchema.generateRoundId');
    }
    if (!Schema || typeof Schema.generateMatchId !== 'function') {
        _missing.push('TournamentSchema.generateMatchId');
    }
    if (!Schema || typeof Schema.deriveAdvancing !== 'function') {
        _missing.push('TournamentSchema.deriveAdvancing');
    }
    if (!Schema || typeof Schema.isValidMatchType !== 'function') {
        _missing.push('TournamentSchema.isValidMatchType');
    }
    if (!Schema || typeof Schema.normalisePairings !== 'function') {
        _missing.push('TournamentSchema.normalisePairings');
    }
    if (!Schema || typeof Schema.isValidResult !== 'function') {
        _missing.push('TournamentSchema.isValidResult');
    }
    if (!Lifecycle) { _missing.push('TournamentLifecycle'); }
    if (!Rules) { _missing.push('TournamentRules'); }
    if (!Queries) { _missing.push('TournamentQueries'); }
    if (!MutationPipeline ||
        typeof MutationPipeline.performMutation !== 'function') {
        _missing.push('MutationPipeline.performMutation');
    }
    if (!ObjectUtils || typeof ObjectUtils.deepClone !== 'function') {
        _missing.push('ObjectUtils.deepClone');
    }
    if (!IdUtils || typeof IdUtils.generateId !== 'function') {
        _missing.push('IdUtils.generateId');
    }

    if (_missing.length > 0) {
        throw new Error(
            '[TournamentMatches] Missing mandatory dependencies: ' +
            _missing.join(', ')
        );
    }

    window.__tournamentMatchesLoaded = true;

    // ============================================================
    // HELPERS
    // ============================================================

    function isObject(value) {
        return value !== null &&
               typeof value === 'object' &&
               !Array.isArray(value);
    }

    function isNonEmptyString(value) {
        return typeof value === 'string' && value.trim() !== '';
    }

    function normaliseId(value) {
        return Schema.normaliseId(value);
    }

    function deepClone(value) {
        var result = ObjectUtils.deepClone(value);
        if (result === value && value !== null && typeof value === 'object') {
            throw new Error(
                '[TournamentMatches] deepClone aliased the input.'
            );
        }
        return result;
    }

    function parsePositiveInteger(value) {
        if (value === undefined || value === null) {
            return null;
        }
        var num = parseInt(value, 10);
        if (isNaN(num) || num < 1) {
            return null;
        }
        return num;
    }

    function failure(message) {
        return { success: false, message: message };
    }

    function success(data) {
        return { success: true, data: data };
    }

    function getCanonicalParticipantType(mode) {
        if (Schema && typeof Schema.getCanonicalParticipantType === 'function') {
            return Schema.getCanonicalParticipantType(mode);
        }
        return mode === 'teams' ? 'team' : 'character';
    }

    function isValidResult(value) {
        return Schema.isValidResult(value);
    }

    // ============================================================
    // SNAPSHOT-AWARE LOOKUP
    // ============================================================
    //
    // Every mutation re-reads from the pipeline snapshot. These helpers
    // resolve entities within a snapshot rather than from live queries.

    function findTournamentInSnapshot(appData, tournamentId) {
        if (!appData || !Array.isArray(appData.tournaments)) {
            return null;
        }
        var target = normaliseId(tournamentId);
        if (target === null) { return null; }
        for (var i = 0; i < appData.tournaments.length; i++) {
            var t = appData.tournaments[i];
            if (t && normaliseId(t.id) === target) {
                return t;
            }
        }
        return null;
    }

    function findRoundInSnapshot(appData, tournamentId, roundId) {
        var tournament = findTournamentInSnapshot(appData, tournamentId);
        if (!tournament) { return null; }
        return Schema.findRoundById(tournament, roundId);
    }

    function findMatchInSnapshot(appData, tournamentId, roundId, matchId) {
        var round = findRoundInSnapshot(appData, tournamentId, roundId);
        if (!round) { return null; }
        return Schema.findMatchById(round, matchId);
    }

    // ============================================================
    // ELIGIBILITY
    // ============================================================
    //
    // A participant is eligible for a NEW match in a round when:
    //   - They are in the tournament roster.
    //   - They have not been individually eliminated.
    //   - They have not failed any prior completed match in this
    //     tournament.
    //
    // Reads via TournamentQueries. This is a pre-flight helper used by
    // generateMatches and the pool preview; it is not part of the
    // mutation critical path.

    function isEligibleForNewMatch(tournamentId, participantId) {
        if (!participantId) { return false; }

        if (!Queries.isParticipantInTournament(tournamentId, participantId)) {
            return false;
        }

        if (Queries.isParticipantEliminated(tournamentId, participantId)) {
            return false;
        }

        var rounds = Queries.getRounds(tournamentId);
        for (var r = 0; r < rounds.length; r++) {
            var matches = rounds[r] && Array.isArray(rounds[r].matches)
                ? rounds[r].matches
                : [];
            for (var m = 0; m < matches.length; m++) {
                var match = matches[m];
                if (!match || match.status !== 'completed') { continue; }

                if (match.type === 'team_vs_team') {
                    var tr = match.teamResults || {};
                    if (tr[participantId] === 'fail') {
                        return false;
                    }
                } else {
                    var rr = match.results || {};
                    if (rr[participantId] === 'fail') {
                        return false;
                    }
                }
            }
        }

        return true;
    }

    function getEligibleParticipants(tournamentId) {
        var tournament = Queries.getTournament(tournamentId);
        if (!tournament || !Array.isArray(tournament.participants)) {
            return [];
        }
        var result = [];
        for (var i = 0; i < tournament.participants.length; i++) {
            var p = tournament.participants[i];
            if (!p || !p.id) { continue; }
            if (isEligibleForNewMatch(tournamentId, p.id)) {
                result.push(p.id);
            }
        }
        return result;
    }

    // ============================================================
    // VALIDATION - Match participants
    // ============================================================

    function validateMatchParticipants(tournamentId, participantIds) {
        if (!Array.isArray(participantIds) || participantIds.length < 2) {
            return { valid: false, message: 'At least 2 participants required.' };
        }

        var seen = {};
        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return { valid: false, message: 'Tournament not found.' };
        }

        var expectedType = getCanonicalParticipantType(tournament.mode);

        for (var i = 0; i < participantIds.length; i++) {
            var id = normaliseId(participantIds[i]);
            if (id === null) {
                return {
                    valid: false,
                    message: 'Invalid participant ID: ' + participantIds[i]
                };
            }
            if (seen[id]) {
                return { valid: false, message: 'Duplicate participant: ' + id };
            }
            seen[id] = true;

            if (!Queries.isParticipantInTournament(tournamentId, id)) {
                return {
                    valid: false,
                    message: 'Participant not in tournament: ' + id
                };
            }

            if (Queries.isParticipantEliminated(tournamentId, id)) {
                return {
                    valid: false,
                    message: 'Participant is eliminated: ' + id
                };
            }

            var actualType = Queries.getParticipantTypeFromRecord(
                tournamentId,
                id
            );
            if (actualType && actualType !== expectedType) {
                return {
                    valid: false,
                    message: 'Participant type mismatch for ' + id +
                        '. Expected ' + expectedType + ', got ' + actualType
                };
            }
        }

        return { valid: true };
    }

    // ============================================================
    // VALIDATION - Result maps
    // ============================================================

    function validateResultMap(rawMap, participants, options) {
        options = options || {};
        var requireAll = options.requireAll === true;

        if (!isObject(rawMap)) {
            return { valid: false, message: 'Results must be an object.' };
        }

        var normalised = {};
        var keys = Object.keys(rawMap);
        for (var i = 0; i < keys.length; i++) {
            var key = keys[i];
            var id = normaliseId(key);
            if (id === null) {
                return { valid: false, message: 'Invalid result key: ' + key };
            }
            if (Array.isArray(participants) &&
                participants.indexOf(id) === -1) {
                return {
                    valid: false,
                    message: 'Result for ' + id +
                        ' does not match a match participant.'
                };
            }
            var value = rawMap[key];
            if (!isValidResult(value)) {
                return {
                    valid: false,
                    message: 'Invalid result for ' + id + ': ' + value +
                        ' (expected pass, fail, or retry)'
                };
            }
            normalised[id] = value;
        }

        if (requireAll && Array.isArray(participants)) {
            for (var j = 0; j < participants.length; j++) {
                var pid = normaliseId(participants[j]);
                if (pid !== null && normalised[pid] === undefined) {
                    return {
                        valid: false,
                        message: 'Missing result for participant: ' + pid
                    };
                }
            }
        }

        return { valid: true, map: normalised };
    }

    // ============================================================
    // INTERNAL PURE BUILDERS
    // ============================================================

    /**
     * Build an empty match for a given round configuration.
     *
     * Generates a stable match ID. Participants and results are
     * populated by the caller.
     */
    function buildMatch(participants, roundConfig) {
        roundConfig = roundConfig || {};
        var matchType = roundConfig.matchType || 'group_exam';
        var matchParticipants = Array.isArray(participants)
            ? participants.slice()
            : [];

        var id = Schema.generateMatchId();

        var result = {
            id: id,
            participants: matchParticipants,
            type: matchType,
            status: 'pending',
            winner: null,
            loser: null,
            advancing: []
        };

        if (matchType === 'group_exam') {
            result.results = {};
            if (roundConfig.isPairExam === true) {
                result.isPairExam = true;
                result.pairings = [];
            }
        } else if (matchType === 'team_vs_team') {
            result.teamResults = {};
            result.individualResults = {};
        }

        return result;
    }

    /**
     * Build an empty round.
     *
     * Generates a stable round ID. The round has ZERO matches.
     * Matches are added explicitly via createMatch or generateMatches.
     */
    function buildRound(roundData, participants) {
        roundData = roundData || {};
        var matchSize = roundData.matchSize || 2;
        var matchType = roundData.matchType || 'group_exam';
        var roundNumber = roundData.roundNumber || 1;
        var isPairExam = roundData.isPairExam === true;

        var id = Schema.generateRoundId();

        var round = {
            id: id,
            roundNumber: roundNumber,
            status: 'pending',
            matchSize: matchSize,
            matchType: matchType,
            matches: []
        };

        if (isPairExam) {
            round.isPairExam = true;
        }

        return round;
    }

    /**
     * Build a complete proposed match state.
     * Preserves the base match's ID.
     */
    function buildProposedMatch(base, updates, tournament, round, options) {
        options = options || {};
        var allowCompletion = options.allowCompletion === true;

        var allowedKeys = [
            'participants',
            'type',
            'status',
            'results',
            'isPairExam',
            'pairings',
            'teamResults',
            'individualResults'
        ];
        if (!hasOnlyAllowedKeys(updates, allowedKeys)) {
            return null;
        }

        var normalisedUpdates = {};

        // ---- participants ----
        if (updates.participants !== undefined) {
            var participants = normaliseIdArrayStrict(updates.participants);
            if (participants === null) { return null; }
            normalisedUpdates.participants = participants;
        }

        // ---- type ----
        var proposedType = updates.type !== undefined
            ? updates.type
            : (base.type || round.matchType || 'group_exam');

        if (updates.type !== undefined && updates.type !== base.type) {
            if (!isTypeChangeAllowed(base)) {
                return null;
            }
            var validTypes = Constants.VALID_MATCH_TYPES;
            if (validTypes.indexOf(proposedType) === -1) {
                return null;
            }
        }

        normalisedUpdates.type = proposedType;

        // ---- status ----
        var currentStatus = base.status || 'pending';
        if (updates.status !== undefined &&
            updates.status !== currentStatus) {
            var validStatuses = ['pending', 'in_progress', 'completed'];
            if (validStatuses.indexOf(updates.status) === -1) {
                return null;
            }
            if (updates.status === 'completed' &&
                currentStatus !== 'completed') {
                if (!allowCompletion) { return null; }
            }
            normalisedUpdates.status = updates.status;
        }

        // ---- isPairExam ----
        if (updates.isPairExam !== undefined) {
            if (proposedType !== 'group_exam') {
                return null;
            }
            normalisedUpdates.isPairExam = updates.isPairExam === true;
        }

        // ---- results (group_exam) ----
        if (updates.results !== undefined) {
            if (proposedType !== 'group_exam') {
                return null;
            }
            var resultCheck = validateResultMap(
                updates.results,
                [],
                { requireAll: false }
            );
            if (!resultCheck.valid) { return null; }
            normalisedUpdates.results = resultCheck.map;
        }

        // ---- teamResults (team_vs_team) ----
        if (updates.teamResults !== undefined) {
            if (proposedType !== 'team_vs_team') {
                return null;
            }
            var teamCheck = validateResultMap(
                updates.teamResults,
                [],
                { requireAll: false }
            );
            if (!teamCheck.valid) { return null; }
            normalisedUpdates.teamResults = teamCheck.map;
        }

        // ---- individualResults (team_vs_team) ----
        if (updates.individualResults !== undefined) {
            if (proposedType !== 'team_vs_team') {
                return null;
            }
            var indCheck = validateResultMap(
                updates.individualResults,
                [],
                { requireAll: false }
            );
            if (!indCheck.valid) { return null; }
            normalisedUpdates.individualResults = indCheck.map;
        }

        // ---- pairings (group_exam + isPairExam) ----
        if (updates.pairings !== undefined) {
            var isPairExamFinal = normalisedUpdates.isPairExam !== undefined
                ? normalisedUpdates.isPairExam
                : (base.isPairExam === true);
            if (proposedType !== 'group_exam' || !isPairExamFinal) {
                return null;
            }
            var pairings = Schema.normalisePairings(updates.pairings);
            if (pairings === null) {
                return null;
            }
            normalisedUpdates.pairings = pairings;
        }

        // ---- build proposed ----
        var proposed = {
            // ID is preserved from the base.
            id: base.id,
            participants: normalisedUpdates.participants !== undefined
                ? normalisedUpdates.participants
                : (base.participants ? base.participants.slice() : []),
            type: normalisedUpdates.type,
            status: normalisedUpdates.status !== undefined
                ? normalisedUpdates.status
                : (base.status !== undefined ? base.status : 'pending'),
            winner: null,
            loser: null,
            advancing: []
        };

        var isPairExam = normalisedUpdates.isPairExam !== undefined
            ? normalisedUpdates.isPairExam
            : (base.isPairExam === true);

        if (isPairExam) {
            proposed.isPairExam = true;
        }

        // ---- per-type payloads ----
        if (proposed.type === 'group_exam') {
            proposed.results = normalisedUpdates.results !== undefined
                ? normalisedUpdates.results
                : (base.results ? Object.assign({}, base.results) : {});
            proposed.pairings = normalisedUpdates.pairings !== undefined
                ? normalisedUpdates.pairings
                : (base.pairings
                    ? base.pairings.slice()
                    : (isPairExam ? [] : undefined));
            if (proposed.pairings === undefined) {
                delete proposed.pairings;
            }
        }

        if (proposed.type === 'team_vs_team') {
            proposed.teamResults = normalisedUpdates.teamResults !== undefined
                ? normalisedUpdates.teamResults
                : (base.teamResults
                    ? Object.assign({}, base.teamResults)
                    : {});
            proposed.individualResults =
                normalisedUpdates.individualResults !== undefined
                    ? normalisedUpdates.individualResults
                    : (base.individualResults
                        ? Object.assign({}, base.individualResults)
                        : {});
        }

        // ---- size check against round.matchSize ----
        var matchSize = round && round.matchSize ? round.matchSize : 2;
        if (proposed.participants.length > 0 &&
            proposed.participants.length !== matchSize) {
            if (proposed.status === 'completed') {
                return null;
            }
        }

        // ---- participant eligibility check ----
        var expectedType = tournament.mode === 'teams'
            ? 'team'
            : 'character';
        for (var pi = 0; pi < proposed.participants.length; pi++) {
            var pid = proposed.participants[pi];
            if (Rules &&
                typeof Rules.isParticipantEligible === 'function') {
                if (!Rules.isParticipantEligible(
                    tournament,
                    pid,
                    expectedType
                )) {
                    return null;
                }
            }
        }

        // ---- result participant check ----
        if (proposed.type === 'group_exam') {
            if (!validateMatchResultParticipants(
                proposed.participants,
                proposed.results
            )) {
                return null;
            }
        }

        // ---- derive advancing ----
        if (Schema &&
            typeof Schema.deriveAdvancing === 'function') {
            proposed.advancing = Schema.deriveAdvancing(proposed);
        }

        return proposed;
    }

    /**
     * Validate a complete proposed match state.
     */
    function validateProposedMatch(proposed, tournament, round, matchId) {
        var errors = [];

        if (!proposed || typeof proposed !== 'object') {
            errors.push('Proposed match is invalid.');
            return { valid: false, errors: errors };
        }

        if (round.status === 'completed') {
            errors.push('Cannot modify matches in a completed round.');
            return { valid: false, errors: errors };
        }

        if (matchId) {
            var existingMatch = Schema.findMatchById(round, matchId);
            if (existingMatch && existingMatch.status === 'completed') {
                errors.push('Cannot modify a completed match.');
                return { valid: false, errors: errors };
            }
        }

        if (Schema && typeof Schema.validateMatch === 'function') {
            var schemaErrors = Schema.validateMatch(proposed, round, true);
            if (Array.isArray(schemaErrors)) {
                for (var i = 0; i < schemaErrors.length; i++) {
                    errors.push(schemaErrors[i]);
                }
            }
        } else {
            errors.push('Schema not available for validation.');
        }

        return { valid: errors.length === 0, errors: errors };
    }

    // ============================================================
    // SMALL VALIDATION HELPERS
    // ============================================================

    function hasOnlyAllowedKeys(object, allowedKeys) {
        var keys = Object.keys(object);
        for (var i = 0; i < keys.length; i++) {
            if (allowedKeys.indexOf(keys[i]) === -1) {
                return false;
            }
        }
        return true;
    }

    function isTypeChangeAllowed(base) {
        if (!base) { return false; }
        if (base.status !== 'pending') { return false; }
        if (base.results && Object.keys(base.results).length > 0) {
            return false;
        }
        if (base.teamResults && Object.keys(base.teamResults).length > 0) {
            return false;
        }
        if (base.individualResults &&
            Object.keys(base.individualResults).length > 0) {
            return false;
        }
        if (base.winner) { return false; }
        return true;
    }

    function normaliseIdArrayStrict(ids) {
        if (!Array.isArray(ids)) { return null; }
        var result = [];
        var seen = {};
        for (var i = 0; i < ids.length; i++) {
            var normalised = normaliseId(ids[i]);
            if (normalised === null) { return null; }
            if (seen[normalised]) { return null; }
            seen[normalised] = true;
            result.push(normalised);
        }
        return result;
    }

    function validateMatchResultParticipants(participants, results) {
        if (!results || typeof results !== 'object') {
            return true;
        }
        var participantIds = participants.map(normaliseId).filter(function(id) {
            return id !== null;
        });
        var keys = Object.keys(results);
        for (var i = 0; i < keys.length; i++) {
            var id = normaliseId(keys[i]);
            if (id === null) { return false; }
            if (participantIds.indexOf(id) === -1) { return false; }
        }
        return true;
    }

    // ============================================================
    // ROUND PROMOTION
    // ============================================================
    //
    // When every match in a round is completed, the round's own status
    // is promoted to 'completed'. This is required by
    // TournamentRules.validateCompletionReadiness, which requires every
    // round to be complete before a tournament can be marked complete.
    //
    // If the round has zero matches, promotion is NOT applied. A round
    // with no matches is not "complete" in the domain's sense; the
    // lifecycle requires every round to have at least one completed
    // match.

    function promoteRoundIfComplete(round) {
        if (!round || !Array.isArray(round.matches)) { return false; }
        if (round.matches.length === 0) { return false; }
        if (round.status === 'completed') { return false; }

        for (var i = 0; i < round.matches.length; i++) {
            var m = round.matches[i];
            if (!m || m.status !== 'completed') {
                return false;
            }
        }

        round.status = 'completed';
        return true;
    }

    // ============================================================
    // MUTATION PIPELINE WRAPPER
    // ============================================================

    function executeMutation(config) {
        return MutationPipeline.performMutation({
            validate: config.validate || function() {
                return { valid: true };
            },
            mutate: config.mutate,
            logMessage: config.logMessage || 'Match operation performed.',
            successMessage: config.successMessage ||
                'Match operation completed.',
            failureMessage: config.failureMessage ||
                'Match operation failed.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Create Match
    // ============================================================

    /**
     * Create a single match in a round.
     *
     * @param {string} tournamentId
     * @param {string} roundId
     * @param {object} matchData - { participants, type?, isPairExam?, pairings? }
     * @returns {Promise<object>}
     */
    function createMatch(tournamentId, roundId, matchData) {
        if (!isObject(matchData)) {
            return Promise.resolve(failure('Invalid match data.'));
        }
        if (!isNonEmptyString(roundId)) {
            return Promise.resolve(failure('Round ID is required.'));
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var rounds = Queries.getRounds(tournamentId);
        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot add matches to a completed round.')
            );
        }

        var participants = matchData.participants || [];
        var validation = validateMatchParticipants(
            tournamentId,
            participants
        );
        if (!validation.valid) {
            return Promise.resolve(failure(validation.message));
        }

        var base = buildMatch([], {
            matchType: matchData.type || round.matchType || 'group_exam',
            isPairExam: matchData.isPairExam === true ||
                round.isPairExam === true
        });

        var updates = {
            participants: participants,
            type: matchData.type || round.matchType || 'group_exam'
        };

        if (matchData.isPairExam === true || round.isPairExam === true) {
            updates.isPairExam = true;
            if (Array.isArray(matchData.pairings)) {
                updates.pairings = matchData.pairings;
            }
        }

        var proposed = buildProposedMatch(
            base,
            updates,
            tournament,
            round
        );
        if (!proposed) {
            return Promise.resolve(failure('Failed to build match.'));
        }

        var validationResult = validateProposedMatch(
            proposed,
            tournament,
            round,
            null
        );
        if (!validationResult.valid) {
            return Promise.resolve(
                failure(validationResult.errors.join('; '))
            );
        }

        // Auto-partition pair exam if no explicit pairings.
        if (proposed.isPairExam &&
            (!proposed.pairings || proposed.pairings.length === 0)) {
            var autoPairings = partitionIntoPairs(proposed.participants);
            if (autoPairings) {
                proposed.pairings = autoPairings;
            }
        }

        var matchCopy = deepClone(proposed);
        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    return { valid: false, message: 'Round no longer exists.' };
                }
                if (snapshotRound.status === 'completed') {
                    return { valid: false, message: 'Round is completed.' };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    throw new Error('Round not found in data store.');
                }
                if (!Array.isArray(snapshotRound.matches)) {
                    snapshotRound.matches = [];
                }
                snapshotRound.matches.push(matchCopy);
                return { match: matchCopy };
            },
            logMessage: 'Added match to round',
            successMessage: 'Match added successfully.',
            failureMessage: 'Failed to add match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Remove Match
    // ============================================================

    function removeMatch(tournamentId, roundId, matchId) {
        if (!isNonEmptyString(roundId) || !isNonEmptyString(matchId)) {
            return Promise.resolve(
                failure('Round ID and match ID are required.')
            );
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot remove matches from a completed round.')
            );
        }

        var match = Schema.findMatchById(round, matchId);
        if (!match) {
            return Promise.resolve(failure('Match not found.'));
        }

        if (match.status === 'completed') {
            return Promise.resolve(
                failure('Cannot remove a completed match.')
            );
        }

        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);
        var targetMatchId = normaliseId(matchId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    return { valid: false, message: 'Round no longer exists.' };
                }
                if (snapshotRound.status === 'completed') {
                    return { valid: false, message: 'Round is completed.' };
                }
                if (!Schema.findMatchById(snapshotRound, targetMatchId)) {
                    return { valid: false, message: 'Match no longer exists.' };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound || !Array.isArray(snapshotRound.matches)) {
                    throw new Error('Round not found in data store.');
                }

                var idx = -1;
                for (var i = 0; i < snapshotRound.matches.length; i++) {
                    if (normaliseId(snapshotRound.matches[i].id) ===
                        targetMatchId) {
                        idx = i;
                        break;
                    }
                }
                if (idx === -1) {
                    throw new Error('Match not found in data store.');
                }

                snapshotRound.matches.splice(idx, 1);
                // Round status remains as-is; removing a match from an
                // 'in_progress' or 'pending' round does not change the
                // round status.
                return { removed: true };
            },
            logMessage: 'Removed match from round',
            successMessage: 'Match removed successfully.',
            failureMessage: 'Failed to remove match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Update Match
    // ============================================================

    function updateMatch(tournamentId, roundId, matchId, updates) {
        if (!isObject(updates)) {
            return Promise.resolve(failure('Invalid updates.'));
        }
        if (!isNonEmptyString(roundId) || !isNonEmptyString(matchId)) {
            return Promise.resolve(
                failure('Round ID and match ID are required.')
            );
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot modify matches in a completed round.')
            );
        }

        var match = Schema.findMatchById(round, matchId);
        if (!match) {
            return Promise.resolve(failure('Match not found.'));
        }

        if (match.status === 'completed') {
            return Promise.resolve(
                failure('Cannot modify a completed match.')
            );
        }

        if (updates.status === 'completed') {
            return Promise.resolve(
                failure('Use completeMatch() to complete a match.')
            );
        }

        var proposedMatch = buildProposedMatch(
            match,
            updates,
            tournament,
            round
        );
        if (!proposedMatch) {
            return Promise.resolve(failure('Invalid updates.'));
        }

        var validationResult = validateProposedMatch(
            proposedMatch,
            tournament,
            round,
            matchId
        );
        if (!validationResult.valid) {
            return Promise.resolve(
                failure(validationResult.errors.join('; '))
            );
        }

        var updatedMatch = deepClone(proposedMatch);

        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);
        var targetMatchId = normaliseId(matchId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    return { valid: false, message: 'Round no longer exists.' };
                }
                if (snapshotRound.status === 'completed') {
                    return { valid: false, message: 'Round is completed.' };
                }
                if (!Schema.findMatchById(snapshotRound, targetMatchId)) {
                    return { valid: false, message: 'Match no longer exists.' };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound || !Array.isArray(snapshotRound.matches)) {
                    throw new Error('Round not found in data store.');
                }

                var idx = -1;
                for (var i = 0; i < snapshotRound.matches.length; i++) {
                    if (normaliseId(snapshotRound.matches[i].id) ===
                        targetMatchId) {
                        idx = i;
                        break;
                    }
                }
                if (idx === -1) {
                    throw new Error('Match not found in data store.');
                }

                applyMatchUpdate(snapshotRound.matches[idx], updatedMatch);
                return { match: snapshotRound.matches[idx] };
            },
            logMessage: 'Updated match',
            successMessage: 'Match updated successfully.',
            failureMessage: 'Failed to update match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Complete Match
    // ============================================================

    function completeMatch(tournamentId, roundId, matchId, result) {
        if (!isObject(result)) {
            return Promise.resolve(failure('Invalid result.'));
        }
        if (!isNonEmptyString(roundId) || !isNonEmptyString(matchId)) {
            return Promise.resolve(
                failure('Round ID and match ID are required.')
            );
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot modify matches in a completed round.')
            );
        }

        var match = Schema.findMatchById(round, matchId);
        if (!match) {
            return Promise.resolve(failure('Match not found.'));
        }

        if (match.status === 'completed') {
            return Promise.resolve(
                failure('Match is already completed.')
            );
        }

        var type = match.type || 'group_exam';
        var updates = { status: 'completed' };

        // ---- group_exam ----
        if (type === 'group_exam') {
            var rawResults = result.results;
            if (!isObject(rawResults) ||
                Object.keys(rawResults).length === 0) {
                return Promise.resolve(
                    failure('Results are required for a group exam.')
                );
            }

            var participants = Array.isArray(match.participants)
                ? match.participants
                : [];
            var check = validateResultMap(
                rawResults,
                participants,
                { requireAll: true }
            );
            if (!check.valid) {
                return Promise.resolve(failure(check.message));
            }
            updates.results = check.map;

            if (match.isPairExam && Array.isArray(match.pairings)) {
                updates.isPairExam = true;
                updates.pairings = deepClone(match.pairings);
            }
        }

        // ---- team_vs_team ----
        if (type === 'team_vs_team') {
            var rawTeam = result.teamResults;
            var rawInd = result.individualResults || {};

            if (!isObject(rawTeam) ||
                Object.keys(rawTeam).length === 0) {
                return Promise.resolve(
                    failure('teamResults are required for a team match.')
                );
            }

            var teams = Array.isArray(match.participants)
                ? match.participants
                : [];
            var teamCheck = validateResultMap(
                rawTeam,
                teams,
                { requireAll: true }
            );
            if (!teamCheck.valid) {
                return Promise.resolve(failure(teamCheck.message));
            }
            updates.teamResults = teamCheck.map;

            if (isObject(rawInd)) {
                var indCheck = validateResultMap(
                    rawInd,
                    null,
                    { requireAll: false }
                );
                if (!indCheck.valid) {
                    return Promise.resolve(failure(indCheck.message));
                }
                updates.individualResults = indCheck.map;
            }
        }

        // ---- standard (legacy) ----
        if (type === 'standard') {
            if (!result.winner) {
                return Promise.resolve(
                    failure('Winner is required for a standard match.')
                );
            }
            var winnerNormalised = normaliseId(result.winner);
            var matchParticipants = Array.isArray(match.participants)
                ? match.participants
                : [];
            if (winnerNormalised === null ||
                matchParticipants.indexOf(winnerNormalised) === -1) {
                return Promise.resolve(
                    failure('Winner must be a participant in the match.')
                );
            }
            updates.winner = winnerNormalised;
        }

        // ---- build proposed ----
        var proposed;
        if (type === 'standard') {
            proposed = Object.assign({}, match);
            proposed.status = 'completed';
            proposed.winner = updates.winner;
        } else {
            proposed = buildProposedMatch(
                match,
                updates,
                tournament,
                round,
                { allowCompletion: true }
            );
        }

        if (!proposed) {
            return Promise.resolve(
                failure('Failed to build completed match.')
            );
        }

        var validationResult = validateProposedMatch(
            proposed,
            tournament,
            round,
            matchId
        );
        if (!validationResult.valid) {
            return Promise.resolve(
                failure(validationResult.errors.join('; '))
            );
        }

        var completedMatch = deepClone(proposed);

        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);
        var targetMatchId = normaliseId(matchId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    return { valid: false, message: 'Round no longer exists.' };
                }
                if (snapshotRound.status === 'completed') {
                    return { valid: false, message: 'Round is completed.' };
                }
                var snapshotMatch = Schema.findMatchById(
                    snapshotRound,
                    targetMatchId
                );
                if (!snapshotMatch) {
                    return { valid: false, message: 'Match no longer exists.' };
                }
                if (snapshotMatch.status === 'completed') {
                    return { valid: false, message: 'Match is already completed.' };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound || !Array.isArray(snapshotRound.matches)) {
                    throw new Error('Round not found in data store.');
                }

                var idx = -1;
                for (var i = 0; i < snapshotRound.matches.length; i++) {
                    if (normaliseId(snapshotRound.matches[i].id) ===
                        targetMatchId) {
                        idx = i;
                        break;
                    }
                }
                if (idx === -1) {
                    throw new Error('Match not found in data store.');
                }

                applyMatchUpdate(
                    snapshotRound.matches[idx],
                    completedMatch
                );

                // Round promotion: if every match is now completed, the
                // round's own status is set to 'completed'.
                var promoted = promoteRoundIfComplete(snapshotRound);

                return {
                    match: snapshotRound.matches[idx],
                    roundPromoted: promoted
                };
            },
            logMessage: 'Completed match',
            successMessage: 'Match completed successfully.',
            failureMessage: 'Failed to complete match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Generate Matches
    // ============================================================

    function generateMatches(tournamentId, roundId, options) {
        options = options || {};

        if (!isNonEmptyString(roundId)) {
            return Promise.resolve(failure('Round ID is required.'));
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot add matches to a completed round.')
            );
        }

        // ---- determine match size ----
        var matchSize = parseInt(options.matchSize, 10);
        if (isNaN(matchSize) || matchSize < 2) {
            matchSize = round.matchSize || 2;
        }

        var isPairExam = round.isPairExam === true ||
            options.isPairExam === true;
        if (isPairExam) {
            matchSize = 2;
        }

        // ---- eligible pool ----
        var pool = getEligibleParticipants(tournamentId);

        // Exclude anyone already placed in a match within this round.
        var alreadyInRound = {};
        if (Array.isArray(round.matches)) {
            for (var m = 0; m < round.matches.length; m++) {
                var existing = round.matches[m];
                if (existing && Array.isArray(existing.participants)) {
                    for (var p = 0; p < existing.participants.length; p++) {
                        var pid = normaliseId(existing.participants[p]);
                        if (pid !== null) {
                            alreadyInRound[pid] = true;
                        }
                    }
                }
            }
        }

        var eligible = pool.filter(function(id) {
            return !alreadyInRound[id];
        });

        if (eligible.length < 2) {
            return Promise.resolve(failure(
                'Not enough eligible participants to generate a match ' +
                '(need at least 2, have ' + eligible.length + ').'
            ));
        }

        // ---- partition ----
        var partitions;
        if (isPairExam) {
            partitions = partitionIntoPairs(eligible);
        } else {
            partitions = partitionIntoGroups(eligible, matchSize);
        }

        if (!partitions || partitions.length === 0) {
            return Promise.resolve(
                failure('Could not partition participants.')
            );
        }

        // ---- build proposed matches ----
        var proposedMatches = [];
        var matchType = round.matchType || 'group_exam';
        if (isPairExam && matchType !== 'group_exam') {
            matchType = 'group_exam';
        }

        for (var i = 0; i < partitions.length; i++) {
            var group = partitions[i];
            var base = buildMatch([], {
                matchType: matchType,
                isPairExam: isPairExam
            });
            var updates = {
                participants: group,
                type: matchType
            };
            if (isPairExam) {
                updates.isPairExam = true;
                updates.pairings = [group.slice()];
            }
            var proposed = buildProposedMatch(
                base,
                updates,
                tournament,
                round
            );
            if (!proposed) {
                return Promise.resolve(failure(
                    'Failed to build match for group ' + (i + 1) + '.'
                ));
            }
            proposedMatches.push(proposed);
        }

        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    return { valid: false, message: 'Round no longer exists.' };
                }
                if (snapshotRound.status === 'completed') {
                    return { valid: false, message: 'Round is completed.' };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData,
                    targetTournamentId,
                    targetRoundId
                );
                if (!snapshotRound) {
                    throw new Error('Round not found in data store.');
                }
                if (!Array.isArray(snapshotRound.matches)) {
                    snapshotRound.matches = [];
                }
                var created = [];
                for (var k = 0; k < proposedMatches.length; k++) {
                    var copy = deepClone(proposedMatches[k]);
                    snapshotRound.matches.push(copy);
                    created.push(copy);
                }
                return {
                    createdCount: created.length,
                    matches: created
                };
            },
            logMessage: 'Generated ' + proposedMatches.length + ' match(es)',
            successMessage: 'Matches generated successfully.',
            failureMessage: 'Failed to generate matches.'
        });
    }

    // ============================================================
    // PARTITION HELPERS
    // ============================================================

    function partitionIntoGroups(ids, groupSize) {
        if (!Array.isArray(ids) || ids.length < 2) { return []; }
        if (groupSize < 2) { groupSize = 2; }

        var pool = ids.slice();
        for (var s = pool.length - 1; s > 0; s--) {
            var r = Math.floor(Math.random() * (s + 1));
            var tmp = pool[s];
            pool[s] = pool[r];
            pool[r] = tmp;
        }

        var groups = [];
        for (var i = 0; i < pool.length; i += groupSize) {
            var slice = pool.slice(i, i + groupSize);
            if (slice.length >= 2) {
                groups.push(slice);
            }
        }

        return groups;
    }

    function partitionIntoPairs(ids) {
        if (!Array.isArray(ids) || ids.length < 2) { return []; }

        var pool = ids.slice();
        for (var s = pool.length - 1; s > 0; s--) {
            var r = Math.floor(Math.random() * (s + 1));
            var tmp = pool[s];
            pool[s] = pool[r];
            pool[r] = tmp;
        }

        var groups = [];
        var i = 0;

        if (pool.length % 2 === 1 && pool.length >= 3) {
            groups.push(pool.slice(0, 3));
            i = 3;
        }

        for (; i < pool.length; i += 2) {
            var slice = pool.slice(i, i + 2);
            if (slice.length === 2) {
                groups.push(slice);
            } else if (slice.length === 1) {
                if (groups.length > 0) {
                    groups[groups.length - 1].push(slice[0]);
                }
            }
        }

        return groups;
    }

    // ============================================================
    // INTERNAL HELPERS
    // ============================================================

    /**
     * Apply the fields of `updated` to `target`, preserving the
     * target's ID.
     */
    function applyMatchUpdate(target, updated) {
        var keys = [
            'participants',
            'type',
            'status',
            'winner',
            'loser',
            'advancing',
            'results',
            'isPairExam',
            'pairings',
            'teamResults',
            'individualResults'
        ];
        for (var i = 0; i < keys.length; i++) {
            var key = keys[i];
            if (updated[key] !== undefined) {
                target[key] = updated[key];
            } else {
                delete target[key];
            }
        }
        // ID is preserved. It is not in the updateable key list, so it
        // is never overwritten or removed by an update.
    }

    // ============================================================
    // READ HELPERS - Delegated to Queries
    // ============================================================

    function getRoundMatches(tournamentId, roundId) {
        return Queries.getMatches(tournamentId, roundId);
    }

    function getMatchWrapper(tournamentId, roundId, matchId) {
        return Queries.getMatch(tournamentId, roundId, matchId);
    }

    function isMatchComplete(tournamentId, roundId, matchId) {
        var match = Queries.getMatch(tournamentId, roundId, matchId);
        if (!match) { return false; }
        return match.status === 'completed';
    }

    function getMatchAdvancing(tournamentId, roundId, matchId) {
        var match = Queries.getMatch(tournamentId, roundId, matchId);
        if (!match) { return []; }
        return Schema.deriveAdvancing(match);
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.TournamentMatches = {
        // Public mutation commands
        createMatch: createMatch,
        removeMatch: removeMatch,
        updateMatch: updateMatch,
        completeMatch: completeMatch,
        generateMatches: generateMatches,

        // Eligibility helpers
        isEligibleForNewMatch: isEligibleForNewMatch,
        getEligibleParticipants: getEligibleParticipants,

        // Internal pure builders
        buildMatch: buildMatch,
        buildRound: buildRound,
        buildProposedMatch: buildProposedMatch,

        // Validation
        validateProposedMatch: validateProposedMatch,
        validateMatchParticipants: validateMatchParticipants,
        validateResultMap: validateResultMap,
        isTypeChangeAllowed: isTypeChangeAllowed,

        // Partition helpers
        partitionIntoGroups: partitionIntoGroups,
        partitionIntoPairs: partitionIntoPairs,

        // Round promotion (exposed for testing)
        promoteRoundIfComplete: promoteRoundIfComplete,

        // Read operations
        getRoundMatches: getRoundMatches,
        getMatch: getMatchWrapper,
        isMatchComplete: isMatchComplete,
        getMatchAdvancing: getMatchAdvancing
    };

})();
