/**
 * modules/tournaments/tournament-core.js - Tournament Core
 * CANONICAL mutation API for tournaments (tournament and round level).
 *
 * Path: js/modules/tournaments/tournament-core.js
 *
 * RESPONSIBILITIES:
 *   - Tournament CRUD (create, update, archive, purge)
 *   - Participant management (add, remove)
 *   - Round management (add, remove, reopen) — by stable round ID
 *   - Elimination week shift when endWeek changes (T8)
 *
 * NOT RESPONSIBILITIES:
 *   - Match-level mutations (TournamentMatches)
 *   - Tournament-level reads (TournamentQueries)
 *   - Cross-domain cascades (character deletion strips references
 *     through a dedicated cascade, not from here)
 *   - Lifecycle state machine (status is a soft label)
 *   - Public read surface (query via TournamentQueries)
 *
 * STATUS MODEL (SIMPLIFIED):
 *   Tournaments are RECORDS, not state machines. The status field is
 *   a soft label the user controls:
 *
 *     draft      — being set up
 *     active     — running
 *     completed  — done (can be reopened)
 *
 *   No operation is blocked by status. Any field can be updated at
 *   any time. Any participant can be added or removed at any time.
 *   Any round can be added at any time. Round removal is subject to
 *   the domain rule that a round with completed matches cannot be
 *   removed through the ordinary remove-round path.
 *
 *   There is no transitionStatus. Status is updated through
 *   updateTournament({ status: ... }) like any other field.
 *
 * ARCHIVE vs PURGE:
 *   Tournaments follow the same historical-preservation model as
 *   classes:
 *
 *     archiveTournament(id)
 *       Sets `archivedAt` and status 'completed'. The tournament and
 *       all its history remain intact. Archived tournaments are
 *       hidden from active selectors but stay queryable.
 *
 *     purgeTournament(id)
 *       Physically removes the tournament. Reverses every
 *       non-standalone character-side elimination keyed to it.
 *       Explicit destructive administration only.
 *
 *   The Academy UI uses archiveTournament. purgeTournament is not
 *   wired to the ordinary delete button.
 *
 * MUTATION CONTRACT:
 *   Every public mutation returns a Promise resolving to
 *   { success: boolean, data?: any, message?: string }.
 *
 * IDENTITY:
 *   Rounds carry stable IDs generated by TournamentMatches.buildRound.
 *   Round operations take IDs, not indices. roundNumber is positional
 *   (index + 1) and is recomputed after round removal.
 *
 * ELIMINATION REVERSAL:
 *   removeRound reverses eliminations produced by completed matches
 *   in the round, keyed by fromRoundId.
 *
 *   purgeTournament reverses every non-standalone character-side
 *   elimination keyed to the tournament.
 *
 *   Both run inside the same transaction as the structural mutation.
 *   If persistence fails, both roll back together.
 *
 * ELIMINATION WEEK SHIFT (T8):
 *   updateTournament shifts every tournament-driven elimination
 *   record for the tournament to the new endWeek, on both sides,
 *   when endWeek changes. The elimination week is derived from
 *   endWeek (see TournamentEliminationCascade.applyFailEliminations),
 *   so when endWeek moves, the eliminations move with it.
 *
 *   Standalone eliminations (Drop Out) are not touched.
 *
 *   The shift runs inside the same transaction as the endWeek
 *   update. If persistence fails, both roll back together.
 *
 *   The comparison is made entirely against the transaction snapshot:
 *   the pre-update endWeek is read from the snapshot immediately
 *   before the updates are applied. This makes the shift decision
 *   provably correct against the transaction's own view, rather than
 *   dependent on a preflight read of the live store.
 *
 * REOPEN SEMANTICS (v21):
 *   The model treats a completed match as committed: its eliminations
 *   reflect its results, and the results cannot be edited in place.
 *   When a user discovers a data-entry error or clicks Complete by
 *   mistake, they reopen:
 *
 *     TournamentMatches.reopenMatch(tournamentId, roundId, matchId)
 *       Per-match reopen. See tournament-matches.js.
 *
 *     reopenRound(tournamentId, roundId)
 *       Round-level reopen. Reverses every elimination produced by
 *       every match in the round, flips every match to 'pending',
 *       and sets the round's status to 'pending'. Results on each
 *       match are preserved. The round is now editable through the
 *       ordinary match-level path.
 *
 *   Reopen restores the invariant that eliminations match results,
 *   by removing the eliminations and letting the user fix the match
 *   results before completing again.
 *
 *   Round reopen does NOT recursively reopen matched rounds. It is
 *   one round at a time. If the user wants the whole tournament
 *   editable, they reopen each round.
 *
 *   Standalone eliminations are not touched by any reopen. Only
 *   eliminations whose provenance is this round (fromRoundId) are
 *   reversed.
 *
 * TRANSACTION VALIDATION:
 *   Pre-flight validation is for UX. Pipeline validation is for
 *   correctness. Every invariant is re-checked against the
 *   transaction snapshot.
 *
 * INTEGER PARSING:
 *   Positive-integer parsing goes through
 *   TournamentConstants.parsePositiveInteger, the single strict
 *   parser for the domain. This file has no local parser.
 *
 * DEPENDENCIES (MANDATORY):
 *   - window.TournamentConstants
 *   - window.TournamentSchema
 *   - window.TournamentRules
 *   - window.TournamentMatches
 *   - window.TournamentQueries
 *   - window.TournamentEliminationCascade
 *   - window.CalendarValidation
 *   - window.IdUtils
 *   - window.ObjectUtils
 *   - window.MutationPipeline
 */

(function() {
    'use strict';

    if (window.__tournamentCoreLoaded) {
        return;
    }

    // ============================================================
    // MANDATORY DEPENDENCIES
    // ============================================================

    var Constants = window.TournamentConstants;
    var Schema = window.TournamentSchema;
    var Rules = window.TournamentRules;
    var Matches = window.TournamentMatches;
    var Queries = window.TournamentQueries;
    var EliminationCascade = window.TournamentEliminationCascade;
    var CalendarValidation = window.CalendarValidation;
    var IdUtils = window.IdUtils;
    var ObjectUtils = window.ObjectUtils;
    var MutationPipeline = window.MutationPipeline;

    var _missing = [];

    if (!Constants ||
        typeof Constants.parsePositiveInteger !== 'function') {
        _missing.push('TournamentConstants.parsePositiveInteger');
    }
    if (!Schema || typeof Schema.findRoundByIdInternal !== 'function') {
        _missing.push('TournamentSchema.findRoundByIdInternal');
    }
    if (!Schema || typeof Schema.findRoundIndexById !== 'function') {
        _missing.push('TournamentSchema.findRoundIndexById');
    }
    if (!Schema || typeof Schema.isValidMode !== 'function') {
        _missing.push('TournamentSchema.isValidMode');
    }
    if (!Schema || typeof Schema.isValidStatus !== 'function') {
        _missing.push('TournamentSchema.isValidStatus');
    }
    if (!Schema || typeof Schema.isValidParticipantType !== 'function') {
        _missing.push('TournamentSchema.isValidParticipantType');
    }
    if (!Schema || typeof Schema.getCanonicalParticipantType !== 'function') {
        _missing.push('TournamentSchema.getCanonicalParticipantType');
    }
    if (!Schema || typeof Schema.isParticipantInTournament !== 'function') {
        _missing.push('TournamentSchema.isParticipantInTournament');
    }
    if (!Schema || typeof Schema.isParticipantEliminated !== 'function') {
        _missing.push('TournamentSchema.isParticipantEliminated');
    }
    if (!Schema || typeof Schema.getParticipantTypeFromRecord !== 'function') {
        _missing.push('TournamentSchema.getParticipantTypeFromRecord');
    }
    if (!Schema || typeof Schema.normaliseId !== 'function') {
        _missing.push('TournamentSchema.normaliseId');
    }
    if (!Rules) { _missing.push('TournamentRules'); }
    if (!Matches || typeof Matches.buildRound !== 'function') {
        _missing.push('TournamentMatches.buildRound');
    }
    if (!Queries || typeof Queries.getTournament !== 'function') {
        _missing.push('TournamentQueries.getTournament');
    }
    if (!Queries || typeof Queries.getRounds !== 'function') {
        _missing.push('TournamentQueries.getRounds');
    }
    if (!Queries || typeof Queries.getRound !== 'function') {
        _missing.push('TournamentQueries.getRound');
    }
    if (!EliminationCascade ||
        typeof EliminationCascade.reverseRoundEliminations !== 'function') {
        _missing.push(
            'TournamentEliminationCascade.reverseRoundEliminations'
        );
    }
    if (!EliminationCascade ||
        typeof EliminationCascade.reverseTournamentEliminations !==
            'function') {
        _missing.push(
            'TournamentEliminationCascade.reverseTournamentEliminations'
        );
    }
    if (!EliminationCascade ||
        typeof EliminationCascade.shiftTournamentEliminationWeeks !==
            'function') {
        _missing.push(
            'TournamentEliminationCascade.shiftTournamentEliminationWeeks'
        );
    }
    if (!CalendarValidation ||
        typeof CalendarValidation.parseWeek !== 'function') {
        _missing.push('CalendarValidation.parseWeek');
    }
    if (!IdUtils || typeof IdUtils.generateId !== 'function') {
        _missing.push('IdUtils.generateId');
    }
    if (!ObjectUtils || typeof ObjectUtils.deepClone !== 'function') {
        _missing.push('ObjectUtils.deepClone');
    }
    if (!MutationPipeline ||
        typeof MutationPipeline.performMutation !== 'function') {
        _missing.push('MutationPipeline.performMutation');
    }

    if (_missing.length > 0) {
        throw new Error(
            '[TournamentCore] Missing mandatory dependencies: ' +
            _missing.join(', ')
        );
    }

    window.__tournamentCoreLoaded = true;

    // ============================================================
    // HELPERS
    // ============================================================

    function isObject(value) {
        return value !== null &&
               typeof value === 'object' &&
               !Array.isArray(value);
    }

    function isNonEmptyString(value) {
        return typeof value === 'string' && value.trim() !== '';
    }

    function normaliseId(value) {
        return Schema.normaliseId(value);
    }

    function deepClone(value) {
        var result = ObjectUtils.deepClone(value);
        if (result === value &&
            value !== null &&
            typeof value === 'object') {
            throw new Error(
                '[TournamentCore] deepClone aliased the input.'
            );
        }
        return result;
    }

    /**
     * Strict positive-integer parse.
     * Delegates to TournamentConstants.parsePositiveInteger, the
     * canonical strict parser for the tournament domain. See the
     * header of tournament-constants.js for the full contract.
     *
     * Accepts: integers (numbers), pure-digit strings.
     * Rejects: floats, negatives, "12abc", "12.5", "-1", "", "   ",
     * NaN, Infinity, booleans, objects, arrays.
     */
    function parsePositiveInteger(value) {
        return Constants.parsePositiveInteger(value);
    }

    function parseWeek(value) {
        return CalendarValidation.parseWeek(value);
    }

    function failure(message) {
        return { success: false, message: message };
    }

    function success(data) {
        return { success: true, data: data };
    }

    function getDataStore() {
        if (!window.data || typeof window.data !== 'object') {
            return null;
        }
        return window.data;
    }

    // ============================================================
    // SNAPSHOT-AWARE LOOKUP
    // ============================================================

    function findTournamentInSnapshot(appData, tournamentId) {
        if (!appData || !Array.isArray(appData.tournaments)) {
            return null;
        }
        var target = normaliseId(tournamentId);
        if (target === null) { return null; }
        for (var i = 0; i < appData.tournaments.length; i++) {
            var t = appData.tournaments[i];
            if (t && normaliseId(t.id) === target) {
                return t;
            }
        }
        return null;
    }

    // ============================================================
    // LIVE READ HELPERS - PRIVATE
    // ============================================================

    function getTournamentInternal(id) {
        var normalisedId = normaliseId(id);
        if (normalisedId === null) {
            return null;
        }
        var data = getDataStore();
        if (!data || !Array.isArray(data.tournaments)) {
            return null;
        }
        for (var i = 0; i < data.tournaments.length; i++) {
            var t = data.tournaments[i];
            if (t && normaliseId(t.id) === normalisedId) {
                return t;
            }
        }
        return null;
    }

    // ============================================================
    // ID GENERATION
    // ============================================================

    function generateUniqueTournamentId(appData) {
        var attempts = 0;
        var maxAttempts = 10;
        var id;
        var generated = false;

        while (!generated && attempts < maxAttempts) {
            id = IdUtils.generateId('tourn');
            attempts++;

            var normalisedId_ = normaliseId(id);
            if (normalisedId_ === null) {
                continue;
            }

            var collision = Array.isArray(appData.tournaments) &&
                appData.tournaments.some(function(t) {
                    return t && normaliseId(t.id) === normalisedId_;
                });

            if (!collision) {
                generated = true;
            }
        }

        if (!generated) {
            return null;
        }
        return normaliseId(id);
    }

    // ============================================================
    // VALIDATION - SNAPSHOT-AWARE
    // ============================================================

    function validateTournamentInSnapshot(tournament, options) {
        if (!Schema || typeof Schema.validateTournament !== 'function') {
            return { valid: true, errors: [] };
        }
        return Schema.validateTournament(tournament, options || {});
    }

    // ============================================================
    // CREATE
    // ============================================================

    function createTournament(data) {
        if (!isObject(data)) {
            return Promise.resolve(
                failure('Tournament data is required.')
            );
        }
        if (!isNonEmptyString(data.name)) {
            return Promise.resolve(
                failure('Tournament name is required.')
            );
        }
        var name = data.name.trim();

        if (!Schema.isValidMode(data.mode)) {
            return Promise.resolve(failure(
                'Tournament mode is required and must be one of: ' +
                Schema.VALID_MODES.join(', ') + '.'
            ));
        }
        var mode = data.mode;

        var startWeek = data.startWeek !== undefined
            ? data.startWeek
            : 1;
        var parsedStart = parseWeek(startWeek);
        if (parsedStart === null) {
            return Promise.resolve(failure('Invalid start week.'));
        }

        var endWeek = data.endWeek !== undefined
            ? data.endWeek
            : Schema.MAX_WEEK;
        var parsedEnd = parseWeek(endWeek);
        if (parsedEnd === null) {
            return Promise.resolve(failure('Invalid end week.'));
        }

        if (parsedStart > parsedEnd) {
            return Promise.resolve(
                failure('Start week cannot be after end week.')
            );
        }

        var totalRounds = data.totalRounds !== undefined
            ? data.totalRounds
            : 1;
        var parsedRounds = parsePositiveInteger(totalRounds);
        if (parsedRounds === null) {
            return Promise.resolve(failure('Invalid total rounds.'));
        }

        var status = data.status !== undefined
            ? data.status
            : 'draft';
        if (!Schema.isValidStatus(status)) {
            return Promise.resolve(failure('Invalid status: ' + status));
        }

        var graduatingClassId = data.graduatingClassId !== undefined
            ? normaliseId(data.graduatingClassId)
            : null;

        var classFilterEnabled = data.classFilterEnabled === true;

        var appData = getDataStore();
        if (!appData || !Array.isArray(appData.tournaments)) {
            return Promise.resolve(failure(
                'Tournament store is not available.'
            ));
        }

        var id = generateUniqueTournamentId(appData);
        if (id === null) {
            return Promise.resolve(
                failure('Failed to generate a unique tournament ID.')
            );
        }

        var now = new Date().toISOString();

        var newTournament = {
            id: id,
            name: name,
            mode: mode,
            startWeek: parsedStart,
            endWeek: parsedEnd,
            totalRounds: parsedRounds,
            status: status,
            participants: [],
            rounds: [],
            eliminations: [],
            graduatingClassId: graduatingClassId,
            classFilterEnabled: classFilterEnabled,
            createdAt: now,
            archivedAt: null,
            _schemaVersion: Schema.SCHEMA_VERSION
        };

        var validation = validateTournamentInSnapshot(newTournament, {
            strict: true
        });
        if (!validation.valid) {
            return Promise.resolve(
                failure(validation.errors.join('; '))
            );
        }

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                if (!appDataSnapshot ||
                    !Array.isArray(appDataSnapshot.tournaments)) {
                    return {
                        valid: false,
                        message: 'Tournament store is not available.'
                    };
                }
                var collision = appDataSnapshot.tournaments.some(
                    function(t) {
                        return t && normaliseId(t.id) === id;
                    }
                );
                if (collision) {
                    return {
                        valid: false,
                        message: 'Tournament ID collision.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                if (!Array.isArray(appDataSnapshot.tournaments)) {
                    appDataSnapshot.tournaments = [];
                }
                appDataSnapshot.tournaments.push(deepClone(newTournament));
                return { tournament: newTournament, id: id };
            },
            logMessage: 'Created tournament: ' + name,
            successMessage: 'Tournament created successfully!',
            failureMessage: 'Failed to create tournament.'
        });
    }

    // ============================================================
    // UPDATE
    // ============================================================

    function updateTournament(id, updates) {
        if (!isObject(updates)) {
            return Promise.resolve(failure('Updates must be an object.'));
        }

        var updateKeys = Object.keys(updates);
        if (updateKeys.length === 0) {
            return Promise.resolve(failure('Updates are required.'));
        }

        var hasUndefined = updateKeys.some(function(key) {
            return updates[key] === undefined;
        });
        if (hasUndefined) {
            return Promise.resolve(
                failure('Updates cannot contain undefined values.')
            );
        }

        var tournament = getTournamentInternal(id);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var allowedKeys = [
            'name',
            'mode',
            'startWeek',
            'endWeek',
            'totalRounds',
            'status',
            'graduatingClassId',
            'classFilterEnabled'
        ];
        var unknownKeys = updateKeys.filter(function(key) {
            return allowedKeys.indexOf(key) === -1;
        });
        if (unknownKeys.length > 0) {
            return Promise.resolve(failure(
                'Unknown or non-updatable keys: ' +
                unknownKeys.join(', ')
            ));
        }

        if (updates.status !== undefined) {
            if (!Schema.isValidStatus(updates.status)) {
                return Promise.resolve(failure(
                    'Invalid status: ' + updates.status
                ));
            }
        }

        if (updates.name !== undefined &&
            !isNonEmptyString(updates.name)) {
            return Promise.resolve(failure(
                'Tournament name cannot be empty.'
            ));
        }

        if (updates.mode !== undefined &&
            !Schema.isValidMode(updates.mode)) {
            return Promise.resolve(failure(
                'Invalid mode: ' + updates.mode
            ));
        }

        var targetId = normaliseId(id);
        var updatesCopy = deepClone(updates);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }

                var proposed = deepClone(current);
                var keys = Object.keys(updatesCopy);
                for (var i = 0; i < keys.length; i++) {
                    proposed[keys[i]] = updatesCopy[keys[i]];
                }

                if (updatesCopy.totalRounds !== undefined) {
                    var newTotal = parsePositiveInteger(
                        proposed.totalRounds
                    );
                    if (newTotal !== null &&
                        Array.isArray(current.rounds) &&
                        current.rounds.length > newTotal) {
                        return {
                            valid: false,
                            message:
                                'Cannot reduce total rounds below the ' +
                                'existing round count.'
                        };
                    }
                }

                if (updatesCopy.mode !== undefined &&
                    updatesCopy.mode !== current.mode) {
                    if (Array.isArray(current.participants) &&
                        current.participants.length > 0) {
                        return {
                            valid: false,
                            message:
                                'Cannot change mode while participants ' +
                                'exist.'
                        };
                    }
                }

                var validation = validateTournamentInSnapshot(
                    proposed,
                    { strict: false }
                );
                if (!validation.valid) {
                    return {
                        valid: false,
                        message: validation.errors.join('; ')
                    };
                }

                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }

                // ---- Capture pre-update endWeek FROM THE SNAPSHOT ----
                //
                // The shift decision (T8) must be made against the
                // transaction's own view. Reading the previous value
                // here, before applying the updates, ensures the
                // comparison is between the snapshot's current endWeek
                // and the proposed new endWeek. If a prior mutation in
                // the same transaction had already changed endWeek,
                // this read sees the change.
                //
                // The preflight read in getTournamentInternal is used
                // only for the "tournament exists" check and the
                // allowed-keys validation. It is NOT the source of the
                // shift comparison.
                var previousEndWeek = current.endWeek;

                var keys = Object.keys(updatesCopy);
                for (var i = 0; i < keys.length; i++) {
                    current[keys[i]] = deepClone(updatesCopy[keys[i]]);
                }

                // ---- T8: shift elimination weeks if endWeek changed ----
                //
                // The elimination week is derived from the tournament
                // endWeek (see TournamentEliminationCascade.
                // applyFailEliminations). When endWeek moves, every
                // tournament-driven elimination record for this
                // tournament moves with it, on both sides.
                //
                // Standalone eliminations (Drop Out) are not touched.
                //
                // The check is "endWeek was present in the update
                // AND the new value differs from the pre-update
                // value." Saving the same week again is a no-op.
                var shiftResult = null;
                if (updatesCopy.endWeek !== undefined) {
                    var newEndWeek = parseWeek(current.endWeek);
                    var oldEndWeek = parseWeek(previousEndWeek);
                    if (newEndWeek !== null &&
                        oldEndWeek !== null &&
                        newEndWeek !== oldEndWeek) {
                        shiftResult = EliminationCascade
                            .shiftTournamentEliminationWeeks(
                                appDataSnapshot,
                                targetId,
                                newEndWeek
                            );
                    }
                }

                return {
                    tournament: current,
                    id: targetId,
                    eliminationShift: shiftResult
                };
            },
            logMessage: function(result) {
                if (result && result.eliminationShift &&
                    result.eliminationShift.shifted > 0) {
                    return 'Updated tournament (shifted ' +
                        result.eliminationShift.shifted +
                        ' elimination week(s))';
                }
                return 'Updated tournament';
            },
            successMessage: 'Tournament updated successfully!',
            failureMessage: 'Failed to update tournament.'
        });
    }

    // ============================================================
    // ARCHIVE / PURGE
    // ============================================================

    function archiveTournament(id) {
        var normalisedId_ = normaliseId(id);
        if (normalisedId_ === null) {
            return Promise.resolve(
                failure('Tournament ID is required.')
            );
        }

        var tournament = getTournamentInternal(normalisedId_);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        if (tournament.archivedAt) {
            return Promise.resolve(failure(
                'Tournament is already archived.'
            ));
        }

        var name = tournament.name || 'Unknown';

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    normalisedId_
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (current.archivedAt) {
                    return {
                        valid: false,
                        message: 'Tournament is already archived.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    normalisedId_
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }

                current.archivedAt = new Date().toISOString();
                current.status = 'completed';

                return {
                    id: normalisedId_,
                    archivedAt: current.archivedAt
                };
            },
            logMessage: 'Archived tournament: ' + name,
            successMessage: 'Tournament archived.',
            failureMessage: 'Failed to archive tournament.'
        });
    }

    function purgeTournament(id) {
        var normalisedId_ = normaliseId(id);
        if (normalisedId_ === null) {
            return Promise.resolve(
                failure('Tournament ID is required.')
            );
        }

        var tournament = getTournamentInternal(normalisedId_);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var name = tournament.name || 'Unknown';

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var target = findTournamentInSnapshot(
                    appDataSnapshot,
                    normalisedId_
                );
                if (!target) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                if (!Array.isArray(appDataSnapshot.tournaments)) {
                    throw new Error(
                        'Tournament store is not available.'
                    );
                }

                // Reverse character-side eliminations BEFORE the
                // tournament record is spliced out.
                var reversal = EliminationCascade
                    .reverseTournamentEliminations(
                        appDataSnapshot,
                        normalisedId_
                    );

                var idx = -1;
                for (var i = 0;
                     i < appDataSnapshot.tournaments.length;
                     i++) {
                    if (normaliseId(
                        appDataSnapshot.tournaments[i].id
                    ) === normalisedId_) {
                        idx = i;
                        break;
                    }
                }
                if (idx === -1) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                appDataSnapshot.tournaments.splice(idx, 1);

                return {
                    id: normalisedId_,
                    eliminationsReversed: reversal.reversed,
                    reversedCharacterIds: reversal.characterIds
                };
            },
            logMessage: function(result) {
                if (result && result.eliminationsReversed > 0) {
                    return 'Purged tournament: ' + name +
                        ' (reversed ' + result.eliminationsReversed +
                        ' elimination(s))';
                }
                return 'Purged tournament: ' + name;
            },
            successMessage: 'Tournament purged.',
            failureMessage: 'Failed to purge tournament.'
        });
    }

    // ============================================================
    // PARTICIPANT OPERATIONS
    // ============================================================

    function addParticipant(tournamentId, participant) {
        if (!isObject(participant)) {
            return Promise.resolve(
                failure('Participant data is required.')
            );
        }

        var id = normaliseId(participant.id);
        if (id === null) {
            return Promise.resolve(
                failure('Participant ID is required.')
            );
        }

        var type = participant.type;
        if (!Schema.isValidParticipantType(type)) {
            return Promise.resolve(failure(
                'Invalid participant type: ' + type
            ));
        }

        var tournament = getTournamentInternal(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var canonicalType = Schema.getCanonicalParticipantType(
            tournament.mode
        );
        if (canonicalType === null || type !== canonicalType) {
            return Promise.resolve(failure(
                'Participant type "' + type +
                '" does not match tournament mode "' +
                tournament.mode + '" (expected "' +
                canonicalType + '").'
            ));
        }

        if (Schema.isParticipantInTournament(tournament, id)) {
            return Promise.resolve(failure(
                'Participant is already in this tournament.'
            ));
        }

        var targetId = normaliseId(tournamentId);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }

                var currentCanonical = Schema
                    .getCanonicalParticipantType(current.mode);
                if (currentCanonical === null ||
                    type !== currentCanonical) {
                    return {
                        valid: false,
                        message:
                            'Participant type no longer matches ' +
                            'tournament mode.'
                    };
                }

                if (Schema.isParticipantInTournament(current, id)) {
                    return {
                        valid: false,
                        message:
                            'Participant is already in this tournament.'
                    };
                }

                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                if (!Array.isArray(current.participants)) {
                    current.participants = [];
                }
                current.participants.push({
                    id: id,
                    type: type,
                    addedAt: new Date().toISOString()
                });
                return { participantId: id, type: type };
            },
            logMessage: 'Added participant to tournament: ' +
                (tournament.name || targetId),
            successMessage: 'Participant added successfully!',
            failureMessage: 'Failed to add participant.'
        });
    }

    function removeParticipant(tournamentId, participantId) {
        var id = normaliseId(participantId);
        if (id === null) {
            return Promise.resolve(
                failure('Participant ID is required.')
            );
        }

        var tournament = getTournamentInternal(tournamentId);
        if (!tournament || !Array.isArray(tournament.participants)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var found = false;
        for (var i = 0; i < tournament.participants.length; i++) {
            if (normaliseId(tournament.participants[i].id) === id) {
                found = true;
                break;
            }
        }
        if (!found) {
            return Promise.resolve(failure(
                'Participant not found in this tournament.'
            ));
        }

        var targetId = normaliseId(tournamentId);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                var present = Array.isArray(current.participants) &&
                    current.participants.some(function(p) {
                        return p && normaliseId(p.id) === id;
                    });
                if (!present) {
                    return {
                        valid: false,
                        message: 'Participant no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current || !Array.isArray(current.participants)) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                current.participants = current.participants.filter(
                    function(p) {
                        return !(p && normaliseId(p.id) === id);
                    }
                );
                return { participantId: id };
            },
            logMessage: 'Removed participant from tournament: ' +
                (tournament.name || targetId),
            successMessage: 'Participant removed successfully!',
            failureMessage: 'Failed to remove participant.'
        });
    }

    // ============================================================
    // ROUND OPERATIONS
    // ============================================================

    function addRound(tournamentId, roundData) {
        var tournament = getTournamentInternal(tournamentId);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var matchSize = 2;
        var matchType = 'group_exam';
        var isPairExam = false;

        if (roundData && typeof roundData === 'object') {
            if (roundData.matchSize !== undefined) {
                var size = parsePositiveInteger(
                    roundData.matchSize
                );
                if (size === null || size < 2) {
                    return Promise.resolve(failure(
                        'Match size must be an integer >= 2.'
                    ));
                }
                matchSize = size;
            }

            if (roundData.matchType !== undefined) {
                if (!Schema.isValidMatchType(roundData.matchType)) {
                    return Promise.resolve(failure(
                        'Invalid match type: ' + roundData.matchType
                    ));
                }
                matchType = roundData.matchType;
            }

            if (roundData.isPairExam === true) {
                if (matchType !== 'group_exam') {
                    return Promise.resolve(failure(
                        'Pair exams require match type "group_exam".'
                    ));
                }
                isPairExam = true;
                matchSize = 2;
            }
        }

        var ruleCheck = Rules.validateRoundAddition(tournament, {
            matchSize: matchSize,
            matchType: matchType,
            isPairExam: isPairExam
        });
        if (!ruleCheck.valid) {
            return Promise.resolve(failure(ruleCheck.message));
        }

        var roundNumber = tournament.rounds.length + 1;
        var round = Matches.buildRound({
            matchSize: matchSize,
            matchType: matchType,
            roundNumber: roundNumber,
            isPairExam: isPairExam
        });

        if (!round || !normaliseId(round.id)) {
            return Promise.resolve(
                failure('Failed to build round with a stable ID.')
            );
        }

        var roundCopy = deepClone(round);
        var targetTournamentId = normaliseId(tournamentId);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                if (!Array.isArray(current.rounds)) {
                    current.rounds = [];
                }
                current.rounds.push(roundCopy);
                return { round: roundCopy, roundId: roundCopy.id };
            },
            logMessage: 'Added round to tournament: ' +
                (tournament.name || targetTournamentId),
            successMessage: 'Round added successfully!',
            failureMessage: 'Failed to add round.'
        });
    }

    function removeRound(tournamentId, roundId) {
        var normalisedRoundId = normaliseId(roundId);
        if (normalisedRoundId === null) {
            return Promise.resolve(failure('Round ID is required.'));
        }

        var tournament = getTournamentInternal(tournamentId);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundByIdInternal(
            tournament,
            normalisedRoundId
        );
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        var ruleCheck = Rules.validateRoundRemoval(
            tournament,
            Schema.findRoundIndexById(tournament, normalisedRoundId)
        );
        if (!ruleCheck.valid) {
            return Promise.resolve(failure(ruleCheck.message));
        }

        var targetTournamentId = normaliseId(tournamentId);
        var roundDisplayNumber = round.roundNumber;

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current || !Array.isArray(current.rounds)) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (!Schema.findRoundByIdInternal(
                    current,
                    normalisedRoundId
                )) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                var idx = Schema.findRoundIndexById(
                    current,
                    normalisedRoundId
                );
                var removalCheck = Rules.validateRoundRemoval(
                    current,
                    idx
                );
                if (!removalCheck.valid) {
                    return {
                        valid: false,
                        message: removalCheck.message
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current || !Array.isArray(current.rounds)) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }

                // Reverse eliminations BEFORE splicing the round.
                var reversal = EliminationCascade
                    .reverseRoundEliminations(
                        appDataSnapshot,
                        current,
                        normalisedRoundId
                    );

                var idx = Schema.findRoundIndexById(
                    current,
                    normalisedRoundId
                );
                if (idx === -1) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                current.rounds.splice(idx, 1);

                // Recompute roundNumber positionally.
                for (var i = 0; i < current.rounds.length; i++) {
                    current.rounds[i].roundNumber = i + 1;
                }

                return {
                    roundId: normalisedRoundId,
                    roundDisplayNumber: roundDisplayNumber,
                    eliminationsReversed: reversal.reversed,
                    reversedCharacterIds: reversal.characterIds
                };
            },
            logMessage: function(result) {
                if (result && result.eliminationsReversed > 0) {
                    return 'Removed round ' + roundDisplayNumber +
                        ' from tournament: ' +
                        (tournament.name || targetTournamentId) +
                        ' (reversed ' + result.eliminationsReversed +
                        ' elimination(s))';
                }
                return 'Removed round ' + roundDisplayNumber +
                    ' from tournament: ' +
                    (tournament.name || targetTournamentId);
            },
            successMessage: 'Round removed successfully!',
            failureMessage: 'Failed to remove round.'
        });
    }

    // ============================================================
    // ROUND REOPEN (v21)
    // ============================================================

    /**
     * Reopen a round so every match in it can be edited.
     *
     * SEMANTICS:
     *   - Reverses every elimination produced by every match in the
     *     round, via the cascade's reverseRoundEliminations (keyed
     *     by fromRoundId).
     *   - Flips every match in the round to 'pending'. Results on
     *     each match are preserved. The form pre-populates when the
     *     user reopens a match for editing.
     *   - Sets the round's status to 'pending'.
     *   - Standalone eliminations are not touched. Eliminations
     *     produced by other rounds are not touched.
     *
     * The round is now editable through the ordinary match-level
     * path. When the user is done editing, each match is completed
     * individually, or the round is completed when all its matches
     * are complete.
     *
     * @param {string} tournamentId
     * @param {string} roundId
     * @returns {Promise<{success, data?, message?}>}
     */
    function reopenRound(tournamentId, roundId) {
        var normalisedRoundId = normaliseId(roundId);
        if (normalisedRoundId === null) {
            return Promise.resolve(failure('Round ID is required.'));
        }

        var tournament = getTournamentInternal(tournamentId);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundByIdInternal(
            tournament,
            normalisedRoundId
        );
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        var targetTournamentId = normaliseId(tournamentId);
        var roundDisplayNumber = round.roundNumber;
        var matchCount = Array.isArray(round.matches)
            ? round.matches.length
            : 0;

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current || !Array.isArray(current.rounds)) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (!Schema.findRoundByIdInternal(
                    current,
                    normalisedRoundId
                )) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current || !Array.isArray(current.rounds)) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }

                var liveRound = Schema.findRoundByIdInternal(
                    current,
                    normalisedRoundId
                );
                if (!liveRound) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                // ---- Reverse eliminations keyed to this round ----
                var reversal = EliminationCascade
                    .reverseRoundEliminations(
                        appDataSnapshot,
                        current,
                        normalisedRoundId
                    );

                // ---- Flip every match in the round to pending ----
                var reopenedCount = 0;
                if (Array.isArray(liveRound.matches)) {
                    for (var i = 0; i < liveRound.matches.length; i++) {
                        var m = liveRound.matches[i];
                        if (!m) { continue; }
                        if (m.status !== 'pending') {
                            m.status = 'pending';
                            reopenedCount++;
                        }
                    }
                }

                // ---- Reset the round's own status ----
                liveRound.status = 'pending';

                return {
                    roundId: normalisedRoundId,
                    roundDisplayNumber: roundDisplayNumber,
                    matchesReopened: reopenedCount,
                    eliminationsReversed: reversal.reversed,
                    reversedCharacterIds: reversal.characterIds
                };
            },
            logMessage: function(result) {
                var parts = [];
                if (result.matchesReopened > 0) {
                    parts.push(result.matchesReopened + ' match(es)');
                }
                if (result.eliminationsReversed > 0) {
                    parts.push(result.eliminationsReversed +
                        ' elimination(s)');
                }
                var suffix = parts.length > 0
                    ? ' (' + parts.join(', ') + ')'
                    : '';
                return 'Reopened round ' + roundDisplayNumber +
                    ' of tournament: ' +
                    (tournament.name || targetTournamentId) + suffix;
            },
            successMessage: 'Round reopened. Matches are editable.',
            failureMessage: 'Failed to reopen round.'
        });
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.TournamentCore = Object.freeze({
        // Tournament lifecycle
        createTournament: createTournament,
        updateTournament: updateTournament,
        archiveTournament: archiveTournament,
        purgeTournament: purgeTournament,

        // Participants
        addParticipant: addParticipant,
        removeParticipant: removeParticipant,

        // Rounds
        addRound: addRound,
        removeRound: removeRound,
        reopenRound: reopenRound
    });

    // ============================================================
    // VERIFICATION
    // ============================================================

    (function verify() {
        var exports = window.TournamentCore;
        var missing = [];

        var required = [
            'createTournament',
            'updateTournament',
            'archiveTournament',
            'purgeTournament',
            'addParticipant',
            'removeParticipant',
            'addRound',
            'removeRound',
            'reopenRound'
        ];

        for (var i = 0; i < required.length; i++) {
            if (typeof exports[required[i]] !== 'function') {
                missing.push(required[i]);
            }
        }

        if (missing.length > 0) {
            console.warn(
                '[TournamentCore] Verification - some exports may be ' +
                'missing:', missing.join(', ')
            );
        }
    })();

})();