/**
 * modules/tournaments/tournament-matches.js - Tournament Match Operations
 * CANONICAL match mutation API for tournaments.
 *
 * Path: js/modules/tournaments/tournament-matches.js
 *
 * RESPONSIBILITIES:
 *   - Match CRUD (create, update, delete)
 *   - Match completion (per-participant pass/fail/retry)
 *   - Team match completion (team-level + member-level results)
 *   - Auto-generation of matches from an eligible pool
 *   - Internal pure builders for Core.addRound
 *   - Round promotion / reconciliation: after any match mutation the
 *     round's derived status is reconciled from its matches
 *   - Elimination cascade on completion: failing participants are
 *     eliminated on both the tournament and character sides, inside
 *     the same pipeline transaction
 *   - Elimination reversal on removeMatch: if the removed match was
 *     completed, its eliminations are reversed
 *
 * NOT RESPONSIBILITIES:
 *   - Tournament-level status transitions (TournamentCore)
 *   - Round addition/removal (TournamentCore)
 *   - Persistence (MutationPipeline)
 *   - Rendering, notifications
 *
 * IDENTITY:
 *   Rounds and matches carry stable IDs generated by TournamentSchema.
 *   All public commands accept IDs, not array indices. Lookup goes
 *   through Schema.findRoundById / Schema.findMatchById.
 *
 * ROUND STATUS - DERIVED AND RECONCILED:
 *   A round's `status` is DERIVED from its matches:
 *     - zero matches        → 'pending'
 *     - all matches completed → 'completed'
 *     - otherwise           → 'in_progress'
 *   reconcileRoundStatus(round) applies this rule. It is called after
 *   every match mutation (completion, removal, creation, update) so
 *   the derived state is always consistent with the match list.
 *
 * MATCH TYPES:
 *   - 'group_exam'  : open assessment. participants.length === round.matchSize.
 *                     May be isPairExam.
 *   - 'team_vs_team': adversarial team match. participants.length >= 2.
 *
 * RESULT VALIDATION:
 *   buildProposedMatch validates result maps WITHOUT a participant
 *   allow-list. It passes `null` as the participants argument to
 *   validateResultMap, which skips the participant-membership check.
 *   The participant-membership check runs later in
 *   validateProposedMatch, against the actual round and participant
 *   list.
 *
 *   For team_vs_team:
 *     - teamResults keys are validated against match.participants
 *       (which are team IDs).
 *     - individualResults keys are validated as strings. Team
 *       membership of individual results is NOT checked here; that
 *       is a cross-domain concern.
 *
 * ELIMINATION CASCADE:
 *   When completeMatch succeeds and any participant's result is
 *   'fail', the cascade writes elimination records:
 *     - tournament.eliminations[]   { participantId, participantType,
 *                                     week, reason, fromRoundId,
 *                                     fromMatchId }
 *     - character.eliminations[]    { id, tournamentId, fromRoundId,
 *                                     fromMatchId, week, reason,
 *                                     standalone: false, fromMatch: true }
 *
 *   The elimination week is the tournament's endWeek. Missing or
 *   malformed endWeek causes the completion to fail, because an
 *   elimination with a fabricated week is worse than a failed
 *   completion.
 *
 *   For 'team_vs_team' matches, ONLY individualResults[charId] ===
 *   'fail' eliminates. teamResults never eliminates anyone directly.
 *   For 'group_exam', results[charId] === 'fail' eliminates.
 *
 *   The cascade runs inside completeMatch's mutate callback, in the
 *   same transaction as the match status change. It does NOT go
 *   through a public elimination mutation API.
 *
 * ELIMINATION REVERSAL:
 *   When removeMatch succeeds and the removed match was completed,
 *   reverseMatchEliminations runs BEFORE the match is spliced out.
 *   It removes eliminations whose provenance is this match, on both
 *   sides. Standalone eliminations are not touched.
 *
 * TRANSACTION VALIDATION:
 *   Pre-flight validation is for UX. Pipeline validation is for
 *   correctness. Every mutation re-validates its invariants against
 *   the transaction snapshot; no business-critical condition exists
 *   only in the preflight phase.
 *
 * DEPENDENCIES (MANDATORY):
 *   - window.TournamentConstants
 *   - window.TournamentSchema
 *   - window.TournamentRules
 *   - window.TournamentQueries
 *   - window.TournamentEliminationCascade
 *   - window.CalendarValidation
 *   - window.MutationPipeline
 *   - window.ObjectUtils
 */

(function() {
    'use strict';

    if (window.__tournamentMatchesLoaded) {
        return;
    }

    // ============================================================
    // MANDATORY DEPENDENCIES
    // ============================================================

    var Constants = window.TournamentConstants;
    var Schema = window.TournamentSchema;
    var Rules = window.TournamentRules;
    var Queries = window.TournamentQueries;
    var EliminationCascade = window.TournamentEliminationCascade;
    var CalendarValidation = window.CalendarValidation;
    var MutationPipeline = window.MutationPipeline;
    var ObjectUtils = window.ObjectUtils;

    var _missing = [];

    if (!Constants) { _missing.push('TournamentConstants'); }
    if (!Schema || typeof Schema.findRoundById !== 'function') {
        _missing.push('TournamentSchema.findRoundById');
    }
    if (!Schema || typeof Schema.findRoundByIdInternal !== 'function') {
        _missing.push('TournamentSchema.findRoundByIdInternal');
    }
    if (!Schema || typeof Schema.findMatchByIdInternal !== 'function') {
        _missing.push('TournamentSchema.findMatchByIdInternal');
    }
    if (!Schema || typeof Schema.findMatchIndexById !== 'function') {
        _missing.push('TournamentSchema.findMatchIndexById');
    }
    if (!Schema || typeof Schema.generateRoundId !== 'function') {
        _missing.push('TournamentSchema.generateRoundId');
    }
    if (!Schema || typeof Schema.generateMatchId !== 'function') {
        _missing.push('TournamentSchema.generateMatchId');
    }
    if (!Schema || typeof Schema.deriveAdvancing !== 'function') {
        _missing.push('TournamentSchema.deriveAdvancing');
    }
    if (!Schema || typeof Schema.isValidMatchType !== 'function') {
        _missing.push('TournamentSchema.isValidMatchType');
    }
    if (!Schema || typeof Schema.isValidMatchStatus !== 'function') {
        _missing.push('TournamentSchema.isValidMatchStatus');
    }
    if (!Schema || typeof Schema.normaliseId !== 'function') {
        _missing.push('TournamentSchema.normaliseId');
    }
    if (!Schema || typeof Schema.normalisePairings !== 'function') {
        _missing.push('TournamentSchema.normalisePairings');
    }
    if (!Schema || typeof Schema.isValidResult !== 'function') {
        _missing.push('TournamentSchema.isValidResult');
    }
    if (!Schema || typeof Schema.isParticipantEliminated !== 'function') {
        _missing.push('TournamentSchema.isParticipantEliminated');
    }
    if (!Rules) { _missing.push('TournamentRules'); }
    if (!Queries) { _missing.push('TournamentQueries'); }
    if (!EliminationCascade ||
        typeof EliminationCascade.applyFailEliminations !== 'function') {
        _missing.push('TournamentEliminationCascade.applyFailEliminations');
    }
    if (!EliminationCascade ||
        typeof EliminationCascade.reverseMatchEliminations !== 'function') {
        _missing.push(
            'TournamentEliminationCascade.reverseMatchEliminations'
        );
    }
    if (!CalendarValidation ||
        typeof CalendarValidation.parseWeek !== 'function') {
        _missing.push('CalendarValidation.parseWeek');
    }
    if (!MutationPipeline ||
        typeof MutationPipeline.performMutation !== 'function') {
        _missing.push('MutationPipeline.performMutation');
    }
    if (!ObjectUtils || typeof ObjectUtils.deepClone !== 'function') {
        _missing.push('ObjectUtils.deepClone');
    }

    if (_missing.length > 0) {
        throw new Error(
            '[TournamentMatches] Missing mandatory dependencies: ' +
            _missing.join(', ')
        );
    }

    window.__tournamentMatchesLoaded = true;

    // ============================================================
    // HELPERS
    // ============================================================

    function isObject(value) {
        return value !== null &&
               typeof value === 'object' &&
               !Array.isArray(value);
    }

    function isNonEmptyString(value) {
        return typeof value === 'string' && value.trim() !== '';
    }

    function normaliseId(value) {
        return Schema.normaliseId(value);
    }

    function deepClone(value) {
        var result = ObjectUtils.deepClone(value);
        if (result === value &&
            value !== null &&
            typeof value === 'object') {
            throw new Error(
                '[TournamentMatches] deepClone aliased the input.'
            );
        }
        return result;
    }

    function failure(message) {
        return { success: false, message: message };
    }

    function success(data) {
        return { success: true, data: data };
    }

    function isValidResult(value) {
        return Schema.isValidResult(value);
    }

    function matchSizeApplies(type) {
        return type === 'group_exam';
    }

    // ============================================================
    // SNAPSHOT-AWARE LOOKUP
    // ============================================================

    function findTournamentInSnapshot(appData, tournamentId) {
        if (!appData || !Array.isArray(appData.tournaments)) {
            return null;
        }
        var target = normaliseId(tournamentId);
        if (target === null) { return null; }
        for (var i = 0; i < appData.tournaments.length; i++) {
            var t = appData.tournaments[i];
            if (t && normaliseId(t.id) === target) {
                return t;
            }
        }
        return null;
    }

    function findRoundInSnapshot(appData, tournamentId, roundId) {
        var tournament = findTournamentInSnapshot(appData, tournamentId);
        if (!tournament) { return null; }
        return Schema.findRoundByIdInternal(tournament, roundId);
    }

    // ============================================================
    // ELIGIBILITY
    // ============================================================

    /**
     * Is the participant eligible for a NEW match in this tournament?
     *
     * Checks:
     *   - participant is in the tournament
     *   - participant is not eliminated
     *   - participant has no 'fail' result in any completed match
     *
     * For team_vs_team matches, only teamResults are consulted for the
     * participant (which is a team). Individual results concern
     * characters, who are not the participants of a team match.
     */
    function isEligibleForNewMatch(tournamentId, participantId) {
        if (!participantId) { return false; }

        if (!Queries.isParticipantInTournament(
            tournamentId,
            participantId
        )) {
            return false;
        }

        if (Queries.isParticipantEliminated(
            tournamentId,
            participantId
        )) {
            return false;
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return true;
        }

        for (var r = 0; r < tournament.rounds.length; r++) {
            var round = tournament.rounds[r];
            if (!round || !Array.isArray(round.matches)) { continue; }
            for (var m = 0; m < round.matches.length; m++) {
                var match = round.matches[m];
                if (!match || match.status !== 'completed') { continue; }

                if (match.type === 'team_vs_team') {
                    var tr = match.teamResults || {};
                    if (tr[participantId] === 'fail') {
                        return false;
                    }
                } else {
                    var rr = match.results || {};
                    if (rr[participantId] === 'fail') {
                        return false;
                    }
                }
            }
        }

        return true;
    }

    function getEligibleParticipants(tournamentId) {
        var tournament = Queries.getTournament(tournamentId);
        if (!tournament || !Array.isArray(tournament.participants)) {
            return [];
        }
        var result = [];
        for (var i = 0; i < tournament.participants.length; i++) {
            var p = tournament.participants[i];
            if (!p || !p.id) { continue; }
            if (isEligibleForNewMatch(tournamentId, p.id)) {
                result.push(p.id);
            }
        }
        return result;
    }

    // ============================================================
    // MATCH PARTICIPANT VALIDATION - PREFLIGHT (query-based)
    // ============================================================

    /**
     * Validate match participants against the LIVE tournament store.
     *
     * This is PREFLIGHT validation for UX. It is not authoritative;
     * the pipeline's validate callback re-checks the same invariants
     * against the transaction snapshot.
     */
    function validateMatchParticipantsPreflight(
        tournamentId,
        participantIds
    ) {
        if (!Array.isArray(participantIds) || participantIds.length < 2) {
            return {
                valid: false,
                message: 'At least 2 participants required.'
            };
        }

        var seen = Object.create(null);
        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return { valid: false, message: 'Tournament not found.' };
        }

        var expectedType = Schema.getCanonicalParticipantType(
            tournament.mode
        );

        for (var i = 0; i < participantIds.length; i++) {
            var id = normaliseId(participantIds[i]);
            if (id === null) {
                return {
                    valid: false,
                    message:
                        'Invalid participant ID: ' + participantIds[i]
                };
            }
            if (seen[id]) {
                return {
                    valid: false,
                    message: 'Duplicate participant: ' + id
                };
            }
            seen[id] = true;

            if (!Queries.isParticipantInTournament(tournamentId, id)) {
                return {
                    valid: false,
                    message: 'Participant not in tournament: ' + id
                };
            }

            if (Queries.isParticipantEliminated(tournamentId, id)) {
                return {
                    valid: false,
                    message: 'Participant is eliminated: ' + id
                };
            }

            var actualType = Queries.getParticipantTypeFromRecord(
                tournamentId,
                id
            );
            if (actualType && actualType !== expectedType) {
                return {
                    valid: false,
                    message: 'Participant type mismatch for ' + id +
                        '. Expected ' + expectedType + ', got ' + actualType
                };
            }
        }

        return { valid: true };
    }

    // ============================================================
    // MATCH PARTICIPANT VALIDATION - SNAPSHOT (authoritative)
    // ============================================================

    /**
     * Validate match participants against a transaction snapshot.
     *
     * This is the AUTHORITATIVE check. It runs inside the pipeline
     * validate callback and sees the same state the mutation will.
     */
    function validateMatchParticipantsInSnapshot(
        appData,
        tournamentId,
        participantIds
    ) {
        if (!Array.isArray(participantIds) || participantIds.length < 2) {
            return {
                valid: false,
                message: 'At least 2 participants required.'
            };
        }

        var tournament = findTournamentInSnapshot(appData, tournamentId);
        if (!tournament) {
            return { valid: false, message: 'Tournament no longer exists.' };
        }

        var expectedType = Schema.getCanonicalParticipantType(
            tournament.mode
        );

        var participantIds_set = Object.create(null);
        for (var p = 0; p < tournament.participants.length; p++) {
            var tp = tournament.participants[p];
            if (tp && isNonEmptyString(tp.id)) {
                participantIds_set[String(tp.id)] = true;
            }
        }

        var seen = Object.create(null);

        for (var i = 0; i < participantIds.length; i++) {
            var id = normaliseId(participantIds[i]);
            if (id === null) { return { valid: false, message: 'Invalid participant ID.' }; }
            if (seen[id]) { return { valid: false, message: 'Duplicate participant.' }; }
            seen[id] = true;

            if (!participantIds_set[id]) {
                return {
                    valid: false,
                    message: 'Participant ' + id +
                        ' is no longer in the tournament.'
                };
            }

            if (Schema.isParticipantEliminated(tournament, id)) {
                return {
                    valid: false,
                    message: 'Participant ' + id +
                        ' has been eliminated.'
                };
            }

            var actualType = Schema.getParticipantTypeFromRecord(
                tournament,
                id
            );
            if (actualType !== expectedType) {
                return {
                    valid: false,
                    message: 'Participant type mismatch for ' + id + '.'
                };
            }
        }

        return { valid: true };
    }

    // ============================================================
    // RESULT-MAP VALIDATION
    // ============================================================
    //
    // `participants` is optional. When it is an array, each result
    // key must match a member of that array. When it is `null` (or
    // any non-array), the participant-membership check is SKIPPED
    // and only keys + values are validated.
    //
    // Callers that don't yet know the full participant list should
    // pass `null`. The authoritative participant-membership check
    // runs later in validateProposedMatch against the actual
    // participant list.

    function validateResultMap(rawMap, participants, options) {
        options = options || {};
        var requireAll = options.requireAll === true;

        if (!isObject(rawMap)) {
            return { valid: false, message: 'Results must be an object.' };
        }

        var normalised = {};
        var keys = Object.keys(rawMap);
        for (var i = 0; i < keys.length; i++) {
            var key = keys[i];
            var id = normaliseId(key);
            if (id === null) {
                return {
                    valid: false,
                    message: 'Invalid result key: ' + key
                };
            }
            if (Array.isArray(participants) &&
                participants.indexOf(id) === -1) {
                return {
                    valid: false,
                    message: 'Result for ' + id +
                        ' does not match a match participant.'
                };
            }
            var value = rawMap[key];
            if (!isValidResult(value)) {
                return {
                    valid: false,
                    message: 'Invalid result for ' + id + ': ' + value +
                        ' (expected pass, fail, or retry)'
                };
            }
            normalised[id] = value;
        }

        if (requireAll && Array.isArray(participants)) {
            for (var j = 0; j < participants.length; j++) {
                var pid = normaliseId(participants[j]);
                if (pid !== null && normalised[pid] === undefined) {
                    return {
                        valid: false,
                        message: 'Missing result for participant: ' + pid
                    };
                }
            }
        }

        return { valid: true, map: normalised };
    }

    // ============================================================
    // INTERNAL PURE BUILDERS
    // ============================================================

    function buildMatch(participants, roundConfig) {
        roundConfig = roundConfig || {};
        var matchType = roundConfig.matchType || 'group_exam';
        var matchParticipants = Array.isArray(participants)
            ? participants.slice()
            : [];

        var id = Schema.generateMatchId();

        var result = {
            id: id,
            participants: matchParticipants,
            type: matchType,
            status: 'pending'
        };

        if (matchType === 'group_exam') {
            result.results = {};
            if (roundConfig.isPairExam === true) {
                result.isPairExam = true;
                result.pairings = [];
            }
        } else if (matchType === 'team_vs_team') {
            result.teamResults = {};
            result.individualResults = {};
        }

        return result;
    }

    function buildRound(roundData) {
        roundData = roundData || {};
        var matchSize = roundData.matchSize || 2;
        var matchType = roundData.matchType || 'group_exam';
        var roundNumber = roundData.roundNumber || 1;
        var isPairExam = roundData.isPairExam === true;

        var id = Schema.generateRoundId();

        var round = {
            id: id,
            roundNumber: roundNumber,
            status: 'pending',
            matchSize: matchSize,
            matchType: matchType,
            matches: []
        };

        if (isPairExam) {
            round.isPairExam = true;
        }

        return round;
    }

    // ============================================================
    // BUILD PROPOSED MATCH
    // ============================================================

    function buildProposedMatch(base, updates, tournament, round, options) {
        options = options || {};
        var allowCompletion = options.allowCompletion === true;

        var allowedKeys = [
            'participants',
            'type',
            'status',
            'results',
            'isPairExam',
            'pairings',
            'teamResults',
            'individualResults'
        ];
        if (!hasOnlyAllowedKeys(updates, allowedKeys)) {
            return null;
        }

        var normalisedUpdates = {};

        if (updates.participants !== undefined) {
            var participants = normaliseIdArrayStrict(updates.participants);
            if (participants === null) { return null; }
            normalisedUpdates.participants = participants;
        }

        var proposedType = updates.type !== undefined
            ? updates.type
            : base.type;

        if (!Schema.isValidMatchType(proposedType)) {
            return null;
        }

        if (updates.type !== undefined && updates.type !== base.type) {
            if (!isTypeChangeAllowed(base)) {
                return null;
            }
        }

        // Match type must agree with the round's declared match type.
        if (round && round.matchType && proposedType !== round.matchType) {
            return null;
        }

        normalisedUpdates.type = proposedType;

        var currentStatus = base.status;
        if (!Schema.isValidMatchStatus(currentStatus)) {
            // A persisted match with an invalid status is malformed.
            // We do not silently repair to 'pending'.
            return null;
        }

        if (updates.status !== undefined &&
            updates.status !== currentStatus) {
            if (!Schema.isValidMatchStatus(updates.status)) {
                return null;
            }
            if (updates.status === 'completed' &&
                currentStatus !== 'completed') {
                if (!allowCompletion) { return null; }
            }
            normalisedUpdates.status = updates.status;
        }

        if (updates.isPairExam !== undefined) {
            if (proposedType !== 'group_exam') {
                return null;
            }
            normalisedUpdates.isPairExam = updates.isPairExam === true;
        }

        // Pass `null` for participants: the participant-membership
        // check is not performed here. It runs later in
        // validateProposedMatch against the actual participant list.

        if (updates.results !== undefined) {
            if (proposedType !== 'group_exam') {
                return null;
            }
            var resultCheck = validateResultMap(
                updates.results,
                null,
                { requireAll: false }
            );
            if (!resultCheck.valid) { return null; }
            normalisedUpdates.results = resultCheck.map;
        }

        if (updates.teamResults !== undefined) {
            if (proposedType !== 'team_vs_team') {
                return null;
            }
            var teamCheck = validateResultMap(
                updates.teamResults,
                null,
                { requireAll: false }
            );
            if (!teamCheck.valid) { return null; }
            normalisedUpdates.teamResults = teamCheck.map;
        }

        if (updates.individualResults !== undefined) {
            if (proposedType !== 'team_vs_team') {
                return null;
            }
            var indCheck = validateResultMap(
                updates.individualResults,
                null,
                { requireAll: false }
            );
            if (!indCheck.valid) { return null; }
            normalisedUpdates.individualResults = indCheck.map;
        }

        if (updates.pairings !== undefined) {
            var isPairExamFinal =
                normalisedUpdates.isPairExam !== undefined
                    ? normalisedUpdates.isPairExam
                    : (base.isPairExam === true);
            if (proposedType !== 'group_exam' || !isPairExamFinal) {
                return null;
            }
            var pairings = Schema.normalisePairings(updates.pairings);
            if (pairings === null) {
                return null;
            }
            normalisedUpdates.pairings = pairings;
        }

        var proposed = {
            id: base.id,
            participants: normalisedUpdates.participants !== undefined
                ? normalisedUpdates.participants
                : (base.participants ? base.participants.slice() : []),
            type: normalisedUpdates.type,
            status: normalisedUpdates.status !== undefined
                ? normalisedUpdates.status
                : currentStatus
        };

        var isPairExam = normalisedUpdates.isPairExam !== undefined
            ? normalisedUpdates.isPairExam
            : (base.isPairExam === true);

        if (isPairExam) {
            proposed.isPairExam = true;
        }

        if (proposed.type === 'group_exam') {
            proposed.results = normalisedUpdates.results !== undefined
                ? normalisedUpdates.results
                : (base.results ? Object.assign({}, base.results) : {});
            proposed.pairings = normalisedUpdates.pairings !== undefined
                ? normalisedUpdates.pairings
                : (base.pairings
                    ? base.pairings.slice()
                    : (isPairExam ? [] : undefined));
            if (proposed.pairings === undefined) {
                delete proposed.pairings;
            }
        }

        if (proposed.type === 'team_vs_team') {
            proposed.teamResults = normalisedUpdates.teamResults !== undefined
                ? normalisedUpdates.teamResults
                : (base.teamResults
                    ? Object.assign({}, base.teamResults)
                    : {});
            proposed.individualResults =
                normalisedUpdates.individualResults !== undefined
                    ? normalisedUpdates.individualResults
                    : (base.individualResults
                        ? Object.assign({}, base.individualResults)
                        : {});
        }

        if (matchSizeApplies(proposed.type)) {
            var matchSize = round && round.matchSize
                ? round.matchSize
                : 2;
            if (proposed.participants.length > 0 &&
                proposed.participants.length !== matchSize) {
                return null;
            }
        }

        var expectedType = tournament.mode === 'teams'
            ? 'team'
            : 'character';
        for (var pi = 0; pi < proposed.participants.length; pi++) {
            var pid = proposed.participants[pi];
            if (Rules &&
                typeof Rules.isParticipantEligible === 'function') {
                if (!Rules.isParticipantEligible(
                    tournament,
                    pid,
                    expectedType
                )) {
                    return null;
                }
            }
        }

        if (proposed.type === 'group_exam') {
            if (!validateMatchResultParticipants(
                proposed.participants,
                proposed.results
            )) {
                return null;
            }
        }

        return proposed;
    }

    function validateProposedMatch(proposed, tournament, round, matchId) {
        var errors = [];

        if (!proposed || typeof proposed !== 'object') {
            errors.push('Proposed match is invalid.');
            return { valid: false, errors: errors };
        }

        if (round.status === 'completed') {
            errors.push('Cannot modify matches in a completed round.');
            return { valid: false, errors: errors };
        }

        if (matchId) {
            var existingMatch = Schema.findMatchByIdInternal(
                round,
                matchId
            );
            if (existingMatch && existingMatch.status === 'completed') {
                errors.push('Cannot modify a completed match.');
                return { valid: false, errors: errors };
            }
        }

        if (Schema && typeof Schema.validateMatch === 'function') {
            var schemaErrors = Schema.validateMatch(proposed, round, true);
            if (Array.isArray(schemaErrors)) {
                for (var i = 0; i < schemaErrors.length; i++) {
                    errors.push(schemaErrors[i]);
                }
            }
        } else {
            errors.push('Schema not available for validation.');
        }

        return { valid: errors.length === 0, errors: errors };
    }

    // ============================================================
    // SMALL VALIDATION HELPERS
    // ============================================================

    function hasOnlyAllowedKeys(object, allowedKeys) {
        var keys = Object.keys(object);
        for (var i = 0; i < keys.length; i++) {
            if (allowedKeys.indexOf(keys[i]) === -1) {
                return false;
            }
        }
        return true;
    }

    function isTypeChangeAllowed(base) {
        if (!base) { return false; }
        if (base.status !== 'pending') { return false; }
        if (base.results && Object.keys(base.results).length > 0) {
            return false;
        }
        if (base.teamResults && Object.keys(base.teamResults).length > 0) {
            return false;
        }
        if (base.individualResults &&
            Object.keys(base.individualResults).length > 0) {
            return false;
        }
        return true;
    }

    function normaliseIdArrayStrict(ids) {
        if (!Array.isArray(ids)) { return null; }
        var result = [];
        var seen = Object.create(null);
        for (var i = 0; i < ids.length; i++) {
            var normalised = normaliseId(ids[i]);
            if (normalised === null) { return null; }
            if (seen[normalised]) { return null; }
            seen[normalised] = true;
            result.push(normalised);
        }
        return result;
    }

    function validateMatchResultParticipants(participants, results) {
        if (!results || typeof results !== 'object') {
            return true;
        }
        var participantIds = participants.map(normaliseId).filter(
            function(id) { return id !== null; }
        );
        var keys = Object.keys(results);
        for (var i = 0; i < keys.length; i++) {
            var id = normaliseId(keys[i]);
            if (id === null) { return false; }
            if (participantIds.indexOf(id) === -1) { return false; }
        }
        return true;
    }

    // ============================================================
    // ROUND STATUS RECONCILIATION
    // ============================================================
    //
    // A round's status is DERIVED from its matches. This function is
    // called after every match mutation so the derived state is
    // always consistent.
    //
    // Rule:
    //   zero matches             → 'pending'
    //   all matches completed    → 'completed'
    //   otherwise                → 'in_progress'

    function reconcileRoundStatus(round) {
        if (!round || !Array.isArray(round.matches)) {
            return false;
        }

        var nextStatus;

        if (round.matches.length === 0) {
            nextStatus = 'pending';
        } else {
            var allCompleted = true;
            for (var i = 0; i < round.matches.length; i++) {
                var m = round.matches[i];
                if (!m || m.status !== 'completed') {
                    allCompleted = false;
                    break;
                }
            }
            nextStatus = allCompleted ? 'completed' : 'in_progress';
        }

        if (round.status !== nextStatus) {
            round.status = nextStatus;
            return true;
        }

        return false;
    }

    // ============================================================
    // MUTATION PIPELINE WRAPPER
    // ============================================================

    function executeMutation(config) {
        return MutationPipeline.performMutation({
            validate: config.validate || function() {
                return { valid: true };
            },
            mutate: config.mutate,
            logMessage: config.logMessage || 'Match operation performed.',
            successMessage: config.successMessage ||
                'Match operation completed.',
            failureMessage: config.failureMessage ||
                'Match operation failed.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Create Match
    // ============================================================

    function createMatch(tournamentId, roundId, matchData) {
        if (!isObject(matchData)) {
            return Promise.resolve(failure('Invalid match data.'));
        }
        if (!isNonEmptyString(roundId)) {
            return Promise.resolve(failure('Round ID is required.'));
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot add matches to a completed round.')
            );
        }

        var participants = matchData.participants || [];
        var validation = validateMatchParticipantsPreflight(
            tournamentId,
            participants
        );
        if (!validation.valid) {
            return Promise.resolve(failure(validation.message));
        }

        var base = buildMatch([], {
            matchType: matchData.type || round.matchType || 'group_exam',
            isPairExam: matchData.isPairExam === true ||
                round.isPairExam === true
        });

        var updates = {
            participants: participants,
            type: matchData.type || round.matchType || 'group_exam'
        };

        if (matchData.isPairExam === true || round.isPairExam === true) {
            updates.isPairExam = true;
            if (Array.isArray(matchData.pairings)) {
                updates.pairings = matchData.pairings;
            }
        }

        var proposed = buildProposedMatch(base, updates, tournament, round);
        if (!proposed) {
            return Promise.resolve(failure('Failed to build match.'));
        }

        var validationResult = validateProposedMatch(
            proposed, tournament, round, null
        );
        if (!validationResult.valid) {
            return Promise.resolve(
                failure(validationResult.errors.join('; '))
            );
        }

        if (proposed.isPairExam &&
            (!proposed.pairings || proposed.pairings.length === 0)) {
            var autoPairings = partitionIntoPairs(proposed.participants);
            if (autoPairings) {
                proposed.pairings = autoPairings;
            }
        }

        var matchCopy = deepClone(proposed);
        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                if (snapshotRound.status === 'completed') {
                    return {
                        valid: false,
                        message: 'Round is completed.'
                    };
                }
                var participantCheck = validateMatchParticipantsInSnapshot(
                    appData,
                    targetTournamentId,
                    matchCopy.participants
                );
                if (!participantCheck.valid) {
                    return {
                        valid: false,
                        message: participantCheck.message
                    };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }
                if (!Array.isArray(snapshotRound.matches)) {
                    snapshotRound.matches = [];
                }
                snapshotRound.matches.push(matchCopy);
                reconcileRoundStatus(snapshotRound);
                return { match: matchCopy };
            },
            logMessage: 'Added match to round',
            successMessage: 'Match added successfully.',
            failureMessage: 'Failed to add match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Remove Match
    // ============================================================
    //
    // ELIMINATION REVERSAL:
    //   If the removed match was completed, its eliminations are
    //   reversed BEFORE the match is spliced out. Reversal touches
    //   both tournament.eliminations[] and character.eliminations[],
    //   keyed by (tournamentId, fromMatchId). Standalone eliminations
    //   and legacy eliminations without provenance are not touched.
    //
    // ROUND STATUS RECONCILIATION:
    //   After removal, the round's status is reconciled. A round that
    //   was completed because all matches were completed may now be
    //   pending or in_progress. This is the fix for the previously
    //   inconsistent state where removing a match from a completed
    //   round left the round permanently completed.

    function removeMatch(tournamentId, roundId, matchId) {
        if (!isNonEmptyString(roundId) || !isNonEmptyString(matchId)) {
            return Promise.resolve(
                failure('Round ID and match ID are required.')
            );
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        var match = Schema.findMatchById(round, matchId);
        if (!match) {
            return Promise.resolve(failure('Match not found.'));
        }

        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);
        var targetMatchId = normaliseId(matchId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                if (!Schema.findMatchByIdInternal(
                    snapshotRound,
                    targetMatchId
                )) {
                    return {
                        valid: false,
                        message: 'Match no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotTournament = findTournamentInSnapshot(
                    appData, targetTournamentId
                );
                if (!snapshotTournament) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                var snapshotRound = Schema.findRoundByIdInternal(
                    snapshotTournament, targetRoundId
                );
                if (!snapshotRound ||
                    !Array.isArray(snapshotRound.matches)) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                var idx = Schema.findMatchIndexById(
                    snapshotRound,
                    targetMatchId
                );
                if (idx === -1) {
                    throw new Error(
                        'Match not found in data store.'
                    );
                }

                // ---- Reverse eliminations BEFORE splicing the match ----
                // We check the LIVE match status in the snapshot, not
                // the pre-flight status, because another mutation may
                // have completed the match between preflight and now.
                var liveMatch = snapshotRound.matches[idx];
                var reversal = { reversed: 0, characterIds: [] };
                if (liveMatch && liveMatch.status === 'completed') {
                    reversal = EliminationCascade
                        .reverseMatchEliminations(
                            appData,
                            snapshotTournament,
                            targetMatchId
                        );
                }

                snapshotRound.matches.splice(idx, 1);

                // ---- Reconcile round status ----
                reconcileRoundStatus(snapshotRound);

                return {
                    removed: true,
                    eliminationsReversed: reversal.reversed,
                    reversedCharacterIds: reversal.characterIds
                };
            },
            logMessage: function(result) {
                if (result && result.eliminationsReversed > 0) {
                    return 'Removed match (reversed ' +
                        result.eliminationsReversed +
                        ' elimination(s))';
                }
                return 'Removed match from round';
            },
            successMessage: 'Match removed successfully.',
            failureMessage: 'Failed to remove match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Update Match
    // ============================================================

    function updateMatch(tournamentId, roundId, matchId, updates) {
        if (!isObject(updates)) {
            return Promise.resolve(failure('Invalid updates.'));
        }
        if (!isNonEmptyString(roundId) || !isNonEmptyString(matchId)) {
            return Promise.resolve(
                failure('Round ID and match ID are required.')
            );
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot modify matches in a completed round.')
            );
        }

        var match = Schema.findMatchById(round, matchId);
        if (!match) {
            return Promise.resolve(failure('Match not found.'));
        }

        if (match.status === 'completed') {
            return Promise.resolve(
                failure('Cannot modify a completed match.')
            );
        }

        if (updates.status === 'completed') {
            return Promise.resolve(
                failure('Use completeMatch() to complete a match.')
            );
        }

        var proposedMatch = buildProposedMatch(
            match, updates, tournament, round
        );
        if (!proposedMatch) {
            return Promise.resolve(failure('Invalid updates.'));
        }

        var validationResult = validateProposedMatch(
            proposedMatch, tournament, round, matchId
        );
        if (!validationResult.valid) {
            return Promise.resolve(
                failure(validationResult.errors.join('; '))
            );
        }

        var updatedMatch = deepClone(proposedMatch);
        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);
        var targetMatchId = normaliseId(matchId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                if (snapshotRound.status === 'completed') {
                    return {
                        valid: false,
                        message: 'Round is completed.'
                    };
                }
                if (!Schema.findMatchByIdInternal(
                    snapshotRound,
                    targetMatchId
                )) {
                    return {
                        valid: false,
                        message: 'Match no longer exists.'
                    };
                }
                var participantCheck = validateMatchParticipantsInSnapshot(
                    appData,
                    targetTournamentId,
                    updatedMatch.participants
                );
                if (!participantCheck.valid) {
                    return {
                        valid: false,
                        message: participantCheck.message
                    };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound ||
                    !Array.isArray(snapshotRound.matches)) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                var idx = Schema.findMatchIndexById(
                    snapshotRound,
                    targetMatchId
                );
                if (idx === -1) {
                    throw new Error(
                        'Match not found in data store.'
                    );
                }

                // Replace the entire match object.
                snapshotRound.matches[idx] = deepClone(updatedMatch);

                // Reconcile round status (the replaced match may have
                // a different status than the one it replaced, though
                // updateMatch forbids 'completed' transitions).
                reconcileRoundStatus(snapshotRound);

                return { match: snapshotRound.matches[idx] };
            },
            logMessage: 'Updated match',
            successMessage: 'Match updated successfully.',
            failureMessage: 'Failed to update match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Complete Match
    // ============================================================
    //
    // ELIMINATION CASCADE:
    //   After the match is marked completed, applyFailEliminations
    //   writes elimination records for every failing participant:
    //     - group_exam:   results[charId] === 'fail'
    //     - team_vs_team: individualResults[charId] === 'fail'
    //
    //   teamResults is NOT consulted. A team failing a match does not
    //   directly eliminate its members.
    //
    //   The elimination week is the tournament's endWeek. A missing or
    //   malformed endWeek causes the completion to fail BEFORE the
    //   mutation runs. An elimination with a fabricated week would be
    //   a lie in the historical record.
    //
    //   Last-wins: if a participant already has an elimination for
    //   this tournament (from an earlier failure, a second chance),
    //   the existing elimination is removed and the new one is
    //   written. One elimination per (characterId, tournamentId).

    function completeMatch(tournamentId, roundId, matchId, result) {
        if (!isObject(result)) {
            return Promise.resolve(failure('Invalid result.'));
        }
        if (!isNonEmptyString(roundId) || !isNonEmptyString(matchId)) {
            return Promise.resolve(
                failure('Round ID and match ID are required.')
            );
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        var match = Schema.findMatchById(round, matchId);
        if (!match) {
            return Promise.resolve(failure('Match not found.'));
        }

        if (match.status === 'completed') {
            return Promise.resolve(
                failure('Match is already completed.')
            );
        }

        // ---- Elimination week ----
        // The cascade needs a valid week to write. If the tournament
        // has no valid endWeek, we refuse to complete the match
        // rather than fabricate one. The caller fixes the tournament
        // and retries.
        var eliminationWeek = CalendarValidation.parseWeek(
            tournament.endWeek
        );
        if (eliminationWeek === null) {
            return Promise.resolve(failure(
                'Tournament has no valid endWeek. ' +
                'Cannot determine the elimination week. ' +
                'Set the tournament endWeek and retry.'
            ));
        }

        var type = match.type;
        var updates = { status: 'completed' };

        if (type === 'group_exam') {
            var rawResults = result.results;
            if (!isObject(rawResults) ||
                Object.keys(rawResults).length === 0) {
                return Promise.resolve(
                    failure('Results are required for a group exam.')
                );
            }

            var participants = Array.isArray(match.participants)
                ? match.participants
                : [];
            var check = validateResultMap(
                rawResults,
                participants,
                { requireAll: true }
            );
            if (!check.valid) {
                return Promise.resolve(failure(check.message));
            }
            updates.results = check.map;

            if (match.isPairExam && Array.isArray(match.pairings)) {
                updates.isPairExam = true;
                updates.pairings = deepClone(match.pairings);
            }
        }

        if (type === 'team_vs_team') {
            var rawTeam = result.teamResults;
            var rawInd = result.individualResults || {};

            if (!isObject(rawTeam) ||
                Object.keys(rawTeam).length === 0) {
                return Promise.resolve(
                    failure('teamResults are required for a team match.')
                );
            }

            var teams = Array.isArray(match.participants)
                ? match.participants
                : [];
            var teamCheck = validateResultMap(
                rawTeam,
                teams,
                { requireAll: true }
            );
            if (!teamCheck.valid) {
                return Promise.resolve(failure(teamCheck.message));
            }
            updates.teamResults = teamCheck.map;

            if (isObject(rawInd)) {
                var indCheck = validateResultMap(
                    rawInd,
                    null,
                    { requireAll: false }
                );
                if (!indCheck.valid) {
                    return Promise.resolve(failure(indCheck.message));
                }
                updates.individualResults = indCheck.map;
            }
        }

        var proposed = buildProposedMatch(
            match,
            updates,
            tournament,
            round,
            { allowCompletion: true }
        );

        if (!proposed) {
            return Promise.resolve(
                failure('Failed to build completed match.')
            );
        }

        var validationResult = validateProposedMatch(
            proposed, tournament, round, matchId
        );
        if (!validationResult.valid) {
            return Promise.resolve(
                failure(validationResult.errors.join('; '))
            );
        }

        var completedMatch = deepClone(proposed);
        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);
        var targetMatchId = normaliseId(matchId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                var snapshotMatch = Schema.findMatchByIdInternal(
                    snapshotRound,
                    targetMatchId
                );
                if (!snapshotMatch) {
                    return {
                        valid: false,
                        message: 'Match no longer exists.'
                    };
                }
                if (snapshotMatch.status === 'completed') {
                    return {
                        valid: false,
                        message: 'Match is already completed.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotTournament = findTournamentInSnapshot(
                    appData, targetTournamentId
                );
                if (!snapshotTournament) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                var snapshotRound = Schema.findRoundByIdInternal(
                    snapshotTournament, targetRoundId
                );
                if (!snapshotRound ||
                    !Array.isArray(snapshotRound.matches)) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                var idx = Schema.findMatchIndexById(
                    snapshotRound,
                    targetMatchId
                );
                if (idx === -1) {
                    throw new Error(
                        'Match not found in data store.'
                    );
                }

                // Replace the entire match object.
                snapshotRound.matches[idx] = deepClone(completedMatch);

                // ---- Elimination cascade ----
                // Runs inside this transaction. Failing participants
                // are eliminated on both sides.
                var cascade = EliminationCascade.applyFailEliminations(
                    appData,
                    snapshotTournament,
                    snapshotRound.matches[idx],
                    snapshotRound,
                    eliminationWeek
                );

                // ---- Reconcile round status ----
                var promoted = reconcileRoundStatus(snapshotRound);

                return {
                    match: snapshotRound.matches[idx],
                    roundReconciled: promoted,
                    eliminationsWritten: cascade.written,
                    eliminationsReplaced: cascade.replaced,
                    eliminatedCharacterIds: cascade.characterIds
                };
            },
            logMessage: function(result) {
                if (result && result.eliminationsWritten > 0) {
                    return 'Completed match (eliminated ' +
                        result.eliminationsWritten +
                        ' participant(s))';
                }
                return 'Completed match';
            },
            successMessage: 'Match completed successfully.',
            failureMessage: 'Failed to complete match.'
        });
    }

    // ============================================================
    // PUBLIC COMMAND - Generate Matches
    // ============================================================
    //
    // TRANSACTION SAFETY:
    //   The eligible pool is computed inside the transaction
    //   mutate callback, from the snapshot, not from the live store.
    //   Two rapid calls cannot generate overlapping matches from the
    //   same pool because each transaction sees the other's writes.
    //
    //   The pre-flight phase validates only the round's declared
    //   configuration (matchSize, isPairExam, matchType). It does not
    //   compute the pool; that would be wasted work.

    function generateMatches(tournamentId, roundId, options) {
        options = options || {};

        if (!isNonEmptyString(roundId)) {
            return Promise.resolve(failure('Round ID is required.'));
        }

        var tournament = Queries.getTournament(tournamentId);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, roundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (round.status === 'completed') {
            return Promise.resolve(
                failure('Cannot add matches to a completed round.')
            );
        }

        var matchSize = parseInt(options.matchSize, 10);
        if (isNaN(matchSize) || matchSize < 2) {
            matchSize = round.matchSize || 2;
        }

        var isPairExam = round.isPairExam === true ||
            options.isPairExam === true;
        if (isPairExam) {
            matchSize = 2;
        }

        var targetTournamentId = normaliseId(tournamentId);
        var targetRoundId = normaliseId(roundId);

        return executeMutation({
            validate: function(appData) {
                var snapshotRound = findRoundInSnapshot(
                    appData, targetTournamentId, targetRoundId
                );
                if (!snapshotRound) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                if (snapshotRound.status === 'completed') {
                    return {
                        valid: false,
                        message: 'Round is completed.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appData) {
                var snapshotTournament = findTournamentInSnapshot(
                    appData, targetTournamentId
                );
                if (!snapshotTournament) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                var snapshotRound = Schema.findRoundByIdInternal(
                    snapshotTournament, targetRoundId
                );
                if (!snapshotRound ||
                    !Array.isArray(snapshotRound.matches)) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                // ---- Build the eligible pool from the snapshot ----
                var pool = [];
                if (Array.isArray(snapshotTournament.participants)) {
                    for (var p = 0;
                         p < snapshotTournament.participants.length;
                         p++) {
                        var participant =
                            snapshotTournament.participants[p];
                        if (!participant || !participant.id) { continue; }
                        if (Schema.isParticipantEliminated(
                            snapshotTournament,
                            participant.id
                        )) {
                            continue;
                        }
                        pool.push(String(participant.id));
                    }
                }

                // ---- Exclude participants already in this round ----
                var alreadyInRound = Object.create(null);
                for (var m = 0; m < snapshotRound.matches.length; m++) {
                    var existing = snapshotRound.matches[m];
                    if (!existing ||
                        !Array.isArray(existing.participants)) {
                        continue;
                    }
                    for (var pi = 0;
                         pi < existing.participants.length;
                         pi++) {
                        var pid = normaliseId(
                            existing.participants[pi]
                        );
                        if (pid !== null) {
                            alreadyInRound[pid] = true;
                        }
                    }
                }

                var eligible = pool.filter(function(id) {
                    return !alreadyInRound[id];
                });

                if (eligible.length < 2) {
                    throw new Error(
                        'Not enough eligible participants to generate ' +
                        'a match (need at least 2, have ' +
                        eligible.length + ').'
                    );
                }

                // ---- Partition ----
                var partitions;
                if (isPairExam) {
                    partitions = partitionIntoPairs(eligible);
                } else {
                    partitions = partitionIntoGroups(
                        eligible,
                        matchSize
                    );
                }

                if (!partitions || partitions.length === 0) {
                    throw new Error(
                        'Could not partition participants.'
                    );
                }

                // ---- Build matches against the snapshot ----
                var matchType = snapshotRound.matchType || 'group_exam';
                if (isPairExam && matchType !== 'group_exam') {
                    matchType = 'group_exam';
                }

                var created = [];

                for (var g = 0; g < partitions.length; g++) {
                    var group = partitions[g];
                    var base = buildMatch([], {
                        matchType: matchType,
                        isPairExam: isPairExam
                    });
                    var updates = {
                        participants: group,
                        type: matchType
                    };
                    if (isPairExam) {
                        updates.isPairExam = true;
                        updates.pairings = [group.slice()];
                    }
                    var proposed = buildProposedMatch(
                        base, updates, snapshotTournament, snapshotRound
                    );
                    if (!proposed) {
                        throw new Error(
                            'Failed to build match for group ' +
                            (g + 1) + '.'
                        );
                    }
                    var copy = deepClone(proposed);
                    snapshotRound.matches.push(copy);
                    created.push(copy);
                }

                reconcileRoundStatus(snapshotRound);

                return {
                    createdCount: created.length,
                    matches: created
                };
            },
            logMessage: 'Generated matches',
            successMessage: 'Matches generated successfully.',
            failureMessage: 'Failed to generate matches.'
        });
    }

    // ============================================================
    // PARTITION HELPERS
    // ============================================================

    function partitionIntoGroups(ids, groupSize) {
        if (!Array.isArray(ids) || ids.length < 2) { return []; }
        if (groupSize < 2) { groupSize = 2; }

        var pool = ids.slice();
        for (var s = pool.length - 1; s > 0; s--) {
            var r = Math.floor(Math.random() * (s + 1));
            var tmp = pool[s];
            pool[s] = pool[r];
            pool[r] = tmp;
        }

        var groups = [];
        for (var i = 0; i < pool.length; i += groupSize) {
            var slice = pool.slice(i, i + groupSize);
            if (slice.length >= 2) {
                groups.push(slice);
            }
        }
        return groups;
    }

    function partitionIntoPairs(ids) {
        if (!Array.isArray(ids) || ids.length < 2) { return []; }

        var pool = ids.slice();
        for (var s = pool.length - 1; s > 0; s--) {
            var r = Math.floor(Math.random() * (s + 1));
            var tmp = pool[s];
            pool[s] = pool[r];
            pool[r] = tmp;
        }

        var groups = [];
        var i = 0;

        if (pool.length % 2 === 1 && pool.length >= 3) {
            groups.push(pool.slice(0, 3));
            i = 3;
        }

        for (; i < pool.length; i += 2) {
            var slice = pool.slice(i, i + 2);
            if (slice.length === 2) {
                groups.push(slice);
            } else if (slice.length === 1) {
                if (groups.length > 0) {
                    groups[groups.length - 1].push(slice[0]);
                }
            }
        }
        return groups;
    }

    // ============================================================
    // READ HELPERS - Delegated to Queries
    // ============================================================

    function getRoundMatches(tournamentId, roundId) {
        return Queries.getMatches(tournamentId, roundId);
    }

    function getMatchWrapper(tournamentId, roundId, matchId) {
        return Queries.getMatch(tournamentId, roundId, matchId);
    }

    function isMatchComplete(tournamentId, roundId, matchId) {
        var match = Queries.getMatch(tournamentId, roundId, matchId);
        if (!match) { return false; }
        return match.status === 'completed';
    }

    function getMatchAdvancing(tournamentId, roundId, matchId) {
        var match = Queries.getMatch(tournamentId, roundId, matchId);
        if (!match) { return []; }
        return Schema.deriveAdvancing(match);
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.TournamentMatches = {
        createMatch: createMatch,
        removeMatch: removeMatch,
        updateMatch: updateMatch,
        completeMatch: completeMatch,
        generateMatches: generateMatches,

        isEligibleForNewMatch: isEligibleForNewMatch,
        getEligibleParticipants: getEligibleParticipants,

        buildMatch: buildMatch,
        buildRound: buildRound,
        buildProposedMatch: buildProposedMatch,

        validateProposedMatch: validateProposedMatch,
        validateMatchParticipantsPreflight: validateMatchParticipantsPreflight,
        validateMatchParticipantsInSnapshot: validateMatchParticipantsInSnapshot,
        validateResultMap: validateResultMap,
        isTypeChangeAllowed: isTypeChangeAllowed,
        matchSizeApplies: matchSizeApplies,

        partitionIntoGroups: partitionIntoGroups,
        partitionIntoPairs: partitionIntoPairs,

        reconcileRoundStatus: reconcileRoundStatus,

        getRoundMatches: getRoundMatches,
        getMatch: getMatchWrapper,
        isMatchComplete: isMatchComplete,
        getMatchAdvancing: getMatchAdvancing
    };

    // ============================================================
    // VERIFICATION
    // ============================================================

    (function verify() {
        var exports = window.TournamentMatches;
        var missing = [];

        var required = [
            'createMatch',
            'removeMatch',
            'updateMatch',
            'completeMatch',
            'generateMatches',
            'isEligibleForNewMatch',
            'getEligibleParticipants',
            'buildMatch',
            'buildRound',
            'buildProposedMatch',
            'validateProposedMatch',
            'validateMatchParticipantsPreflight',
            'validateMatchParticipantsInSnapshot',
            'validateResultMap',
            'isTypeChangeAllowed',
            'matchSizeApplies',
            'partitionIntoGroups',
            'partitionIntoPairs',
            'reconcileRoundStatus',
            'getRoundMatches',
            'getMatch',
            'isMatchComplete',
            'getMatchAdvancing'
        ];

        for (var i = 0; i < required.length; i++) {
            if (typeof exports[required[i]] !== 'function') {
                missing.push(required[i]);
            }
        }

        if (missing.length > 0) {
            console.warn(
                '[TournamentMatches] Verification - some exports may be ' +
                'missing:', missing.join(', ')
            );
        }
    })();

})();
