/**
 * modules/tournaments/tournament-core.js - Tournament Core
 * CANONICAL mutation API for tournaments (tournament and round level).
 *
 * Path: js/modules/tournaments/tournament-core.js
 *
 * RESPONSIBILITIES:
 *   - Tournament CRUD (create, update, delete)
 *   - Participant management (add, remove)
 *   - Round management (add, remove) — by stable round ID
 *   - Tournament completion
 *   - Status transitions (canonical entry point)
 *   - Cross-domain cascade helper (stripCharacterRefs)
 *   - Synchronous reads (defensive copies)
 *
 * NOT RESPONSIBILITIES:
 *   - Match-level mutations (TournamentMatches)
 *   - Tournament-level reads for display (TournamentQueries)
 *
 * MUTATION CONTRACT:
 *   Every public mutation returns a Promise resolving to
 *   { success: boolean, data?: any, message?: string }.
 *
 *   Pre-flight reads against window.data provide immediate error
 *   messages. The pipeline's validate() callback re-reads from the
 *   snapshot and revalidates. The snapshot is authoritative.
 *
 * IDENTITY:
 *   Rounds carry stable IDs generated by TournamentSchema, via
 *   TournamentMatches.buildRound. Round operations take IDs, not
 *   indices. roundNumber is positional (index + 1) and is recomputed
 *   after round removal.
 *
 * STATUS TRANSITIONS:
 *   transitionStatus() is the single canonical entry point.
 *   completeTournament() is a thin wrapper.
 *
 *   A tournament can be marked completed when:
 *     - The lifecycle permits it (TournamentLifecycle.canCompleteTournament).
 *     - The domain is ready (TournamentRules.isReadyForCompletion).
 *     - Every round's status is 'completed'.
 *
 *   A winner is NOT required. A tournament may finish with zero, one,
 *   or many final passers.
 *
 * YEAR SEMANTICS:
 *   Tournaments are scoped to WEEKS (bounded 1-52), not years.
 *
 * DEPENDENCIES (MANDATORY):
 *   - window.TournamentSchema
 *   - window.TournamentConstants
 *   - window.TournamentLifecycle
 *   - window.TournamentRules
 *   - window.TournamentMatches
 *   - window.TournamentQueries
 *   - window.CharacterQueries
 *   - window.TeamQueries
 *   - window.CalendarValidation
 *   - window.IdUtils
 *   - window.ObjectUtils
 *   - window.MutationPipeline
 *
 * USAGE:
 *   var Core = window.TournamentCore;
 *
 *   Core.createTournament({ name: 'Spring Cup' }).then(function(result) {
 *       if (result.success) {
 *           var tournament = result.data;
 *       }
 *   });
 *
 *   Core.addRound('tourn_123', { matchSize: 2 }).then(function(result) {
 *       // result.data.round carries the new round, including its id
 *   });
 *
 *   Core.removeRound('tourn_123', 'round_abc').then(function(result) { ... });
 *
 *   Core.completeTournament('tourn_123').then(function(result) { ... });
 */

(function() {
    'use strict';

    if (window.__tournamentCoreLoaded) {
        return;
    }

    // ============================================================
    // MANDATORY DEPENDENCIES
    // ============================================================

    var Schema = window.TournamentSchema;
    var Constants = window.TournamentConstants;
    var Lifecycle = window.TournamentLifecycle;
    var Rules = window.TournamentRules;
    var Matches = window.TournamentMatches;
    var Queries = window.TournamentQueries;
    var CharacterQueries = window.CharacterQueries;
    var TeamQueries = window.TeamQueries;
    var CalendarValidation = window.CalendarValidation;
    var IdUtils = window.IdUtils;
    var ObjectUtils = window.ObjectUtils;
    var MutationPipeline = window.MutationPipeline;

    var _missing = [];

    if (!Schema || typeof Schema.findRoundById !== 'function') {
        _missing.push('TournamentSchema.findRoundById');
    }
    if (!Schema || typeof Schema.findRoundIndexById !== 'function') {
        _missing.push('TournamentSchema.findRoundIndexById');
    }
    if (!Schema || typeof Schema.isValidMode !== 'function') {
        _missing.push('TournamentSchema.isValidMode');
    }
    if (!Schema || typeof Schema.isValidStatus !== 'function') {
        _missing.push('TournamentSchema.isValidStatus');
    }
    if (!Schema || typeof Schema.isValidParticipantType !== 'function') {
        _missing.push('TournamentSchema.isValidParticipantType');
    }
    if (!Schema || typeof Schema.getCanonicalParticipantType !== 'function') {
        _missing.push('TournamentSchema.getCanonicalParticipantType');
    }
    if (!Schema || typeof Schema.isParticipantInTournament !== 'function') {
        _missing.push('TournamentSchema.isParticipantInTournament');
    }
    if (!Schema || typeof Schema.isParticipantEliminated !== 'function') {
        _missing.push('TournamentSchema.isParticipantEliminated');
    }
    if (!Schema || typeof Schema.getParticipantTypeFromRecord !== 'function') {
        _missing.push('TournamentSchema.getParticipantTypeFromRecord');
    }
    if (!Schema || typeof Schema.normaliseId !== 'function') {
        _missing.push('TournamentSchema.normaliseId');
    }
    if (!Constants) { _missing.push('TournamentConstants'); }
    if (!Lifecycle) { _missing.push('TournamentLifecycle'); }
    if (!Rules) { _missing.push('TournamentRules'); }
    if (!Matches || typeof Matches.buildRound !== 'function') {
        _missing.push('TournamentMatches.buildRound');
    }
    if (!Queries || typeof Queries.getTournament !== 'function') {
        _missing.push('TournamentQueries.getTournament');
    }
    if (!Queries || typeof Queries.getRounds !== 'function') {
        _missing.push('TournamentQueries.getRounds');
    }
    if (!Queries || typeof Queries.getRound !== 'function') {
        _missing.push('TournamentQueries.getRound');
    }
    if (!CharacterQueries || typeof CharacterQueries.getCharacterById !== 'function') {
        _missing.push('CharacterQueries.getCharacterById');
    }
    if (!TeamQueries || typeof TeamQueries.getTeamById !== 'function') {
        _missing.push('TeamQueries.getTeamById');
    }
    if (!CalendarValidation || typeof CalendarValidation.parseWeek !== 'function') {
        _missing.push('CalendarValidation.parseWeek');
    }
    if (!IdUtils || typeof IdUtils.generateId !== 'function') {
        _missing.push('IdUtils.generateId');
    }
    if (!ObjectUtils || typeof ObjectUtils.deepClone !== 'function') {
        _missing.push('ObjectUtils.deepClone');
    }
    if (!MutationPipeline || typeof MutationPipeline.performMutation !== 'function') {
        _missing.push('MutationPipeline.performMutation');
    }

    if (_missing.length > 0) {
        throw new Error(
            '[TournamentCore] Missing mandatory dependencies: ' +
            _missing.join(', ')
        );
    }

    window.__tournamentCoreLoaded = true;

    // ============================================================
    // HELPERS
    // ============================================================

    function isObject(value) {
        return value !== null &&
               typeof value === 'object' &&
               !Array.isArray(value);
    }

    function isNonEmptyString(value) {
        return typeof value === 'string' && value.trim() !== '';
    }

    function normaliseId(value) {
        return Schema.normaliseId(value);
    }

    function deepClone(value) {
        var result = ObjectUtils.deepClone(value);
        if (result === value && value !== null && typeof value === 'object') {
            throw new Error(
                '[TournamentCore] deepClone aliased the input.'
            );
        }
        return result;
    }

    function parsePositiveInteger(value) {
        if (value === undefined || value === null) {
            return null;
        }
        var num = parseInt(value, 10);
        if (isNaN(num) || num < 1) {
            return null;
        }
        return num;
    }

    function parseWeek(value) {
        return CalendarValidation.parseWeek(value);
    }

    function failure(message) {
        return { success: false, message: message };
    }

    function success(data) {
        return { success: true, data: data };
    }

    function getDataStore() {
        return window.data || {};
    }

    // ============================================================
    // SNAPSHOT-AWARE LOOKUP
    // ============================================================

    function findTournamentInSnapshot(appData, tournamentId) {
        if (!appData || !Array.isArray(appData.tournaments)) {
            return null;
        }
        var target = normaliseId(tournamentId);
        if (target === null) { return null; }
        for (var i = 0; i < appData.tournaments.length; i++) {
            var t = appData.tournaments[i];
            if (t && normaliseId(t.id) === target) {
                return t;
            }
        }
        return null;
    }

    // ============================================================
    // LIVE READ HELPERS - PRIVATE
    // ============================================================

    /**
     * Internal lookup against window.data. Used for pre-flight checks
     * and for the synchronous read path. Mutations never use this to
     * write; they use the pipeline snapshot.
     */
    function getTournamentInternal(id) {
        var normalisedId = normaliseId(id);
        if (normalisedId === null) {
            return null;
        }
        var data = getDataStore();
        if (!data || !Array.isArray(data.tournaments)) {
            return null;
        }
        for (var i = 0; i < data.tournaments.length; i++) {
            var t = data.tournaments[i];
            if (t && normaliseId(t.id) === normalisedId) {
                return t;
            }
        }
        return null;
    }

    // ============================================================
    // SCHEMA HELPERS
    // ============================================================

    function validateTournamentInternal(tournament, strict) {
        return Schema.validateTournament(tournament, {
            strict: strict !== false
        });
    }

    function getValidatedTournament(id, strict) {
        var tournament = getTournamentInternal(id);
        if (!tournament) { return null; }
        var validation = validateTournamentInternal(tournament, strict === true);
        if (!validation.valid) { return null; }
        return tournament;
    }

    function generateUniqueTournamentId(appData) {
        var attempts = 0;
        var maxAttempts = 10;
        var id;
        var generated = false;

        while (!generated && attempts < maxAttempts) {
            id = IdUtils.generateId('tourn');
            attempts++;

            var normalisedId_ = normaliseId(id);
            if (normalisedId_ === null) {
                continue;
            }

            var collision = Array.isArray(appData.tournaments) &&
                appData.tournaments.some(function(t) {
                    return t && normaliseId(t.id) === normalisedId_;
                });

            if (!collision) {
                generated = true;
            }
        }

        if (!generated) {
            return null;
        }
        return normaliseId(id);
    }

    // ============================================================
    // CASCADE HELPER - STRIP CHARACTER REFERENCES
    // ============================================================
    //
    // Pure w.r.t. appData. Preserves round and match IDs. Called from
    // CharacterCRUD.deleteCharacter inside its pipeline transaction.

    function stripCharacterRefs(appData, charId) {
        var result = {
            participantRecordsRemoved: 0,
            eliminationRecordsRemoved: 0,
            winnerRecordsCleared: 0,
            matchParticipantSlotsRemoved: 0,
            matchesPruned: 0
        };

        if (!appData || !charId) {
            return result;
        }
        if (!Array.isArray(appData.tournaments)) {
            return result;
        }

        var target = String(charId);

        for (var i = 0; i < appData.tournaments.length; i++) {
            var tournament = appData.tournaments[i];
            if (!tournament || typeof tournament !== 'object') {
                continue;
            }

            if (Array.isArray(tournament.participants)) {
                var beforeP = tournament.participants.length;
                tournament.participants = tournament.participants.filter(
                    function(p) {
                        if (!p) { return true; }
                        if (p.type !== 'character') { return true; }
                        return String(p.id) !== target;
                    }
                );
                result.participantRecordsRemoved +=
                    beforeP - tournament.participants.length;
            }

            if (Array.isArray(tournament.eliminations)) {
                var beforeE = tournament.eliminations.length;
                tournament.eliminations = tournament.eliminations.filter(
                    function(e) {
                        if (!e) { return true; }
                        if (e.participantType !== 'character') { return true; }
                        return String(e.participantId) !== target;
                    }
                );
                result.eliminationRecordsRemoved +=
                    beforeE - tournament.eliminations.length;
            }

            if (tournament.winner &&
                tournament.winner.type === 'character' &&
                String(tournament.winner.id) === target) {
                tournament.winner = null;
                result.winnerRecordsCleared++;
            }

            if (Array.isArray(tournament.rounds)) {
                for (var r = 0; r < tournament.rounds.length; r++) {
                    var round = tournament.rounds[r];
                    if (!round || !Array.isArray(round.matches)) {
                        continue;
                    }

                    var matchesToKeep = [];

                    for (var m = 0; m < round.matches.length; m++) {
                        var match = round.matches[m];
                        if (!match || typeof match !== 'object') {
                            matchesToKeep.push(match);
                            continue;
                        }

                        if (Array.isArray(match.participants)) {
                            var beforeM = match.participants.length;
                            match.participants = match.participants.filter(
                                function(id) {
                                    return String(id) !== target;
                                }
                            );
                            result.matchParticipantSlotsRemoved +=
                                beforeM - match.participants.length;
                        }

                        if (Array.isArray(match.participants) &&
                            match.participants.length === 0) {
                            result.matchesPruned++;
                            continue;
                        }

                        if (match.winner &&
                            String(match.winner) === target) {
                            match.winner = null;
                        }
                        if (match.loser &&
                            String(match.loser) === target) {
                            match.loser = null;
                        }
                        if (Array.isArray(match.advancing)) {
                            match.advancing = match.advancing.filter(
                                function(id) {
                                    return String(id) !== target;
                                }
                            );
                        }

                        matchesToKeep.push(match);
                    }

                    round.matches = matchesToKeep;
                }
            }
        }

        return result;
    }

    // ============================================================
    // TOURNAMENT CRUD
    // ============================================================

    /**
     * Create a new tournament.
     */
    function createTournament(data) {
        if (!isObject(data)) {
            return Promise.resolve(
                failure('Tournament data is required.')
            );
        }
        if (!isNonEmptyString(data.name)) {
            return Promise.resolve(
                failure('Tournament name is required.')
            );
        }
        var name = data.name.trim();

        var mode = data.mode || 'teams';
        if (!Schema.isValidMode(mode)) {
            return Promise.resolve(failure('Invalid mode: ' + mode));
        }

        var startWeek = data.startWeek !== undefined ? data.startWeek : 1;
        var parsedStart = parseWeek(startWeek);
        if (parsedStart === null) {
            return Promise.resolve(failure('Invalid start week.'));
        }

        var endWeek = data.endWeek !== undefined ? data.endWeek : 52;
        var parsedEnd = parseWeek(endWeek);
        if (parsedEnd === null) {
            return Promise.resolve(failure('Invalid end week.'));
        }

        if (parsedStart > parsedEnd) {
            return Promise.resolve(
                failure('Start week cannot be after end week.')
            );
        }

        var totalRounds = data.totalRounds !== undefined
            ? data.totalRounds
            : 1;
        var parsedRounds = parsePositiveInteger(totalRounds);
        if (parsedRounds === null) {
            return Promise.resolve(failure('Invalid total rounds.'));
        }

        var status = data.status || 'draft';
        if (!Schema.isValidStatus(status)) {
            return Promise.resolve(failure('Invalid status: ' + status));
        }

        var graduatingClassId = data.graduatingClassId !== undefined
            ? normaliseId(data.graduatingClassId)
            : null;

        var classFilterEnabled = data.classFilterEnabled !== false;

        var appData = getDataStore();
        var id = generateUniqueTournamentId(appData);
        if (id === null) {
            return Promise.resolve(
                failure('Failed to generate a unique tournament ID.')
            );
        }

        var newTournament = {
            id: id,
            name: name,
            mode: mode,
            startWeek: parsedStart,
            endWeek: parsedEnd,
            totalRounds: parsedRounds,
            status: status,
            participants: [],
            rounds: [],
            eliminations: [],
            winner: null,
            createdAt: new Date().toISOString(),
            _schemaVersion: Schema.SCHEMA_VERSION,
            graduatingClassId: graduatingClassId,
            classFilterEnabled: classFilterEnabled
        };

        var validation = validateTournamentInternal(newTournament, true);
        if (!validation.valid) {
            return Promise.resolve(
                failure(validation.errors.join('; '))
            );
        }

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                if (!appDataSnapshot ||
                    !Array.isArray(appDataSnapshot.tournaments)) {
                    return {
                        valid: false,
                        message: 'Tournament store is not available.'
                    };
                }
                var collision = appDataSnapshot.tournaments.some(
                    function(t) {
                        return t && normaliseId(t.id) === id;
                    }
                );
                if (collision) {
                    return {
                        valid: false,
                        message: 'Tournament ID collision.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                if (!Array.isArray(appDataSnapshot.tournaments)) {
                    appDataSnapshot.tournaments = [];
                }
                appDataSnapshot.tournaments.push(deepClone(newTournament));
                return { tournament: newTournament, id: id };
            },
            logMessage: 'Created tournament: ' + name,
            successMessage: 'Tournament created successfully!',
            failureMessage: 'Failed to create tournament.'
        });
    }

    /**
     * Update an existing tournament.
     *
     * UPDATABLE FIELDS:
     *   name, mode, startWeek, endWeek, totalRounds,
     *   graduatingClassId, classFilterEnabled
     */
    function updateTournament(id, updates) {
        if (!isObject(updates)) {
            return Promise.resolve(
                failure('Updates must be an object.')
            );
        }

        var updateKeys = Object.keys(updates);
        if (updateKeys.length === 0) {
            return Promise.resolve(failure('Updates are required.'));
        }

        var hasUndefined = updateKeys.some(function(key) {
            return updates[key] === undefined;
        });
        if (hasUndefined) {
            return Promise.resolve(
                failure('Updates cannot contain undefined values.')
            );
        }

        var tournament = getValidatedTournament(id, false);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var allowedKeys = [
            'name',
            'mode',
            'startWeek',
            'endWeek',
            'totalRounds',
            'graduatingClassId',
            'classFilterEnabled'
        ];
        var unknownKeys = updateKeys.filter(function(key) {
            return allowedKeys.indexOf(key) === -1;
        });
        if (unknownKeys.length > 0) {
            return Promise.resolve(failure(
                'Unknown or non-updatable keys: ' +
                unknownKeys.join(', ')
            ));
        }

        var isStructuralUpdate = updateKeys.some(function(key) {
            return ['name', 'mode', 'startWeek', 'endWeek', 'totalRounds']
                .indexOf(key) !== -1;
        });

        if (isStructuralUpdate) {
            var onlyNameChange = updateKeys.every(function(key) {
                return key === 'name';
            });

            if (!onlyNameChange &&
                !Lifecycle.canEditMetadata(tournament)) {
                return Promise.resolve(failure(
                    'Tournament status does not permit this update.'
                ));
            }
        }

        var proposed = Object.assign({}, tournament);
        Object.keys(updates).forEach(function(key) {
            if (updates[key] !== undefined) {
                proposed[key] = updates[key];
            }
        });

        if (updates.totalRounds !== undefined) {
            var newTotal = parsePositiveInteger(proposed.totalRounds);
            if (newTotal !== null &&
                Array.isArray(tournament.rounds) &&
                tournament.rounds.length > newTotal) {
                return Promise.resolve(failure(
                    'Cannot reduce total rounds below the existing ' +
                    'round count.'
                ));
            }
        }

        if (updates.mode !== undefined &&
            updates.mode !== tournament.mode) {
            if (Array.isArray(tournament.participants) &&
                tournament.participants.length > 0) {
                return Promise.resolve(failure(
                    'Cannot change mode while participants exist.'
                ));
            }
        }

        var validation = validateTournamentInternal(proposed, false);
        if (!validation.valid) {
            return Promise.resolve(
                failure(validation.errors.join('; '))
            );
        }

        var targetId = normaliseId(id);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var snapshot = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!snapshot) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var target = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!target) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                allowedKeys.forEach(function(key) {
                    if (updates[key] === undefined) { return; }
                    target[key] = proposed[key];
                });
                return { tournament: target, id: targetId };
            },
            logMessage: 'Updated tournament: ' + proposed.name,
            successMessage: 'Tournament updated successfully!',
            failureMessage: 'Failed to update tournament.'
        });
    }

    /**
     * Delete a tournament permanently.
     */
    function deleteTournament(id) {
        var normalisedId_ = normaliseId(id);
        if (normalisedId_ === null) {
            return Promise.resolve(
                failure('Tournament ID is required.')
            );
        }

        var tournament = getValidatedTournament(normalisedId_, false);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var tournamentName = tournament.name || 'Unknown';

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var target = findTournamentInSnapshot(
                    appDataSnapshot,
                    normalisedId_
                );
                if (!target) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                if (!Array.isArray(appDataSnapshot.tournaments)) {
                    throw new Error('Tournament store is not available.');
                }
                var idx = -1;
                for (var i = 0; i < appDataSnapshot.tournaments.length; i++) {
                    if (normaliseId(appDataSnapshot.tournaments[i].id) ===
                        normalisedId_) {
                        idx = i;
                        break;
                    }
                }
                if (idx === -1) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                appDataSnapshot.tournaments.splice(idx, 1);
                return { id: normalisedId_ };
            },
            logMessage: 'Deleted tournament: ' + tournamentName,
            successMessage: 'Tournament deleted successfully!',
            failureMessage: 'Failed to delete tournament.'
        });
    }

    // ============================================================
    // PARTICIPANT OPERATIONS
    // ============================================================

    function addParticipant(tournamentId, participant) {
        if (!isObject(participant)) {
            return Promise.resolve(
                failure('Participant data is required.')
            );
        }

        var id = normaliseId(participant.id);
        if (id === null) {
            return Promise.resolve(
                failure('Participant ID is required.')
            );
        }

        var type = participant.type || 'character';

        var tournament = getValidatedTournament(tournamentId, false);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        if (!Array.isArray(tournament.participants)) {
            return Promise.resolve(
                failure('Tournament participant list is malformed.')
            );
        }

        if (!Lifecycle.canModifyParticipants(tournament)) {
            return Promise.resolve(failure(
                'Tournament status "' + tournament.status +
                '" does not permit participant changes.'
            ));
        }

        if (Rules && typeof Rules.canAddParticipant === 'function') {
            if (!Rules.canAddParticipant(tournament, id, type)) {
                return Promise.resolve(failure(
                    'Participant cannot be added to this tournament.'
                ));
            }
        }

        if (!Schema.isValidParticipantType(type)) {
            return Promise.resolve(
                failure('Invalid participant type: ' + type)
            );
        }

        var canonicalType = Schema.getCanonicalParticipantType(
            tournament.mode
        );
        if (canonicalType === null || type !== canonicalType) {
            return Promise.resolve(failure(
                'Participant type "' + type +
                '" does not match tournament mode "' +
                tournament.mode + '" (expected "' + canonicalType + '").'
            ));
        }

        if (type === 'character') {
            if (!CharacterQueries.getCharacterById(id)) {
                return Promise.resolve(
                    failure('Character not found.')
                );
            }
        } else if (type === 'team') {
            if (!TeamQueries.getTeamById(id)) {
                return Promise.resolve(failure('Team not found.'));
            }
        } else {
            return Promise.resolve(
                failure('Unsupported participant type.')
            );
        }

        var exists = tournament.participants.some(function(p) {
            return p && normaliseId(p.id) === id && p.type === type;
        });
        if (exists) {
            return Promise.resolve(failure(
                'Participant is already in this tournament.'
            ));
        }

        var targetId = normaliseId(tournamentId);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (!Array.isArray(current.participants)) {
                    return {
                        valid: false,
                        message: 'Tournament participant list is malformed.'
                    };
                }
                var dup = current.participants.some(function(p) {
                    return p && normaliseId(p.id) === id &&
                        p.type === type;
                });
                if (dup) {
                    return {
                        valid: false,
                        message: 'Participant is already in this tournament.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                if (!Array.isArray(current.participants)) {
                    current.participants = [];
                }
                current.participants.push({
                    id: id,
                    type: type,
                    addedAt: new Date().toISOString()
                });
                return { participantId: id, type: type };
            },
            logMessage: 'Added participant to tournament: ' +
                (tournament.name || targetId),
            successMessage: 'Participant added successfully!',
            failureMessage: 'Failed to add participant.'
        });
    }

    function removeParticipant(tournamentId, participantId) {
        var id = normaliseId(participantId);
        if (id === null) {
            return Promise.resolve(
                failure('Participant ID is required.')
            );
        }

        var tournament = getValidatedTournament(tournamentId, false);
        if (!tournament || !Array.isArray(tournament.participants)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        if (!Lifecycle.canModifyParticipants(tournament)) {
            return Promise.resolve(failure(
                'Tournament status "' + tournament.status +
                '" does not permit participant changes.'
            ));
        }

        if (Rules && typeof Rules.canRemoveParticipant === 'function') {
            if (!Rules.canRemoveParticipant(tournament, id)) {
                return Promise.resolve(failure(
                    'Participant cannot be removed from this tournament.'
                ));
            }
        }

        var participantRecord = null;
        for (var i = 0; i < tournament.participants.length; i++) {
            if (normaliseId(tournament.participants[i].id) === id) {
                participantRecord = tournament.participants[i];
                break;
            }
        }
        if (!participantRecord) {
            return Promise.resolve(failure(
                'Participant not found in this tournament.'
            ));
        }

        var targetId = normaliseId(tournamentId);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                var present = Array.isArray(current.participants) &&
                    current.participants.some(function(p) {
                        return p && normaliseId(p.id) === id;
                    });
                if (!present) {
                    return {
                        valid: false,
                        message: 'Participant no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current || !Array.isArray(current.participants)) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                current.participants = current.participants.filter(
                    function(p) {
                        return !(p && normaliseId(p.id) === id);
                    }
                );
                return { participantId: id };
            },
            logMessage: 'Removed participant from tournament: ' +
                (tournament.name || targetId),
            successMessage: 'Participant removed successfully!',
            failureMessage: 'Failed to remove participant.'
        });
    }

    // ============================================================
    // ROUND OPERATIONS
    // ============================================================

    /**
     * Add a round to a tournament.
     *
     * The round is built by TournamentMatches.buildRound, which
     * generates a stable round ID. This function preserves that ID
     * into the tournament record.
     */
    function addRound(tournamentId, roundData) {
        var tournament = getValidatedTournament(tournamentId, false);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        if (!Lifecycle.canAddRound(
            tournament,
            tournament.rounds.length,
            tournament.totalRounds
        )) {
            return Promise.resolve(failure(
                'Cannot add another round to this tournament.'
            ));
        }

        if (Rules && typeof Rules.canAddRound === 'function') {
            if (!Rules.canAddRound(tournament, roundData)) {
                return Promise.resolve(failure(
                    'Round cannot be added to this tournament.'
                ));
            }
        }

        var matchSize = 2;
        var matchType = 'group_exam';
        var isPairExam = false;

        if (roundData && typeof roundData === 'object') {
            if (roundData.matchSize !== undefined) {
                var size = parsePositiveInteger(roundData.matchSize);
                if (size === null || size < 2) {
                    return Promise.resolve(failure(
                        'Match size must be an integer >= 2.'
                    ));
                }
                matchSize = size;
            }

            if (roundData.matchType !== undefined) {
                if (!Schema.isValidMatchType(roundData.matchType)) {
                    return Promise.resolve(failure(
                        'Invalid match type: ' + roundData.matchType
                    ));
                }
                matchType = roundData.matchType;
            }

            if (roundData.isPairExam === true) {
                isPairExam = true;
                if (matchType !== 'group_exam') {
                    matchType = 'group_exam';
                }
                matchSize = 2;
            }
        }

        var participants = [];
        if (Array.isArray(tournament.participants)) {
            for (var i = 0; i < tournament.participants.length; i++) {
                var p = tournament.participants[i];
                if (p && !Schema.isParticipantEliminated(tournament, p.id)) {
                    participants.push(p.id);
                }
            }
        }

        var roundNumber = tournament.rounds.length + 1;
        var round = Matches.buildRound({
            matchSize: matchSize,
            matchType: matchType,
            roundNumber: roundNumber,
            isPairExam: isPairExam
        }, participants);

        if (!round || !normaliseId(round.id)) {
            return Promise.resolve(
                failure('Failed to build round with a stable ID.')
            );
        }

        var roundCopy = deepClone(round);
        var targetTournamentId = normaliseId(tournamentId);
        var promoteToActive = tournament.status === 'draft';
        var expectedStatus = tournament.status;

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (current.status !== expectedStatus) {
                    return {
                        valid: false,
                        message:
                            'Tournament status has changed since this ' +
                            'request was made.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                if (!Array.isArray(current.rounds)) {
                    current.rounds = [];
                }
                current.rounds.push(roundCopy);
                if (promoteToActive) {
                    current.status = 'active';
                }
                return { round: roundCopy, roundId: roundCopy.id };
            },
            logMessage: 'Added round to tournament: ' +
                (tournament.name || targetTournamentId),
            successMessage: 'Round added successfully!',
            failureMessage: 'Failed to add round.'
        });
    }

    /**
     * Remove a round from a tournament.
     *
     * The round is identified by its stable ID. After removal, the
     * remaining rounds' roundNumber fields are recomputed positionally.
     * Round IDs are preserved.
     */
    function removeRound(tournamentId, roundId) {
        var normalisedRoundId = normaliseId(roundId);
        if (normalisedRoundId === null) {
            return Promise.resolve(
                failure('Round ID is required.')
            );
        }

        var tournament = getValidatedTournament(tournamentId, false);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var round = Schema.findRoundById(tournament, normalisedRoundId);
        if (!round) {
            return Promise.resolve(failure('Round not found.'));
        }

        if (!Lifecycle.canRemoveRounds(tournament)) {
            return Promise.resolve(failure(
                'Tournament status "' + tournament.status +
                '" does not permit round removal.'
            ));
        }

        if (Rules && typeof Rules.canRemoveRound === 'function') {
            var roundIndex = Schema.findRoundIndexById(
                tournament,
                normalisedRoundId
            );
            if (!Rules.canRemoveRound(tournament, roundIndex)) {
                return Promise.resolve(failure(
                    'Round cannot be removed from this tournament.'
                ));
            }
        }

        var targetTournamentId = normaliseId(tournamentId);
        var roundDisplayNumber = round.roundNumber || 0;

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current || !Array.isArray(current.rounds)) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (!Schema.findRoundById(current, normalisedRoundId)) {
                    return {
                        valid: false,
                        message: 'Round no longer exists.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetTournamentId
                );
                if (!current || !Array.isArray(current.rounds)) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }

                var idx = Schema.findRoundIndexById(
                    current,
                    normalisedRoundId
                );
                if (idx === -1) {
                    throw new Error(
                        'Round not found in data store.'
                    );
                }

                current.rounds.splice(idx, 1);

                // Recompute roundNumber positionally. IDs are preserved.
                for (var i = 0; i < current.rounds.length; i++) {
                    current.rounds[i].roundNumber = i + 1;
                }

                if (current.rounds.length === 0) {
                    current.status = 'draft';
                    current.winner = null;
                }

                return {
                    roundId: normalisedRoundId,
                    roundDisplayNumber: roundDisplayNumber
                };
            },
            logMessage: 'Removed round ' + roundDisplayNumber +
                ' from tournament: ' +
                (tournament.name || targetTournamentId),
            successMessage: 'Round removed successfully!',
            failureMessage: 'Failed to remove round.'
        });
    }

    // ============================================================
    // STATUS TRANSITION
    // ============================================================

    /**
     * Transition a tournament to a new status.
     *
     * A winner is NOT required for the active→completed transition.
     * Completion requires:
     *   - Lifecycle permits the transition.
     *   - Domain is ready (Rules.isReadyForCompletion).
     *   - Every round's status is 'completed'.
     */
    function transitionStatus(tournamentId, newStatus, force) {
        force = force === true;

        if (!Schema.isValidStatus(newStatus)) {
            return Promise.resolve(
                failure('Invalid status: ' + newStatus)
            );
        }

        var tournament = getValidatedTournament(tournamentId, false);
        if (!tournament) {
            return Promise.resolve(failure('Tournament not found.'));
        }

        var currentStatus = tournament.status;

        if (!Lifecycle.isValidStatusTransition(
            currentStatus,
            newStatus
        )) {
            return Promise.resolve(failure(
                'Transition from "' + currentStatus +
                '" to "' + newStatus + '" is not allowed.'
            ));
        }

        if (currentStatus === newStatus) {
            return Promise.resolve(failure(
                'Tournament is already in status "' + newStatus + '".'
            ));
        }

        if (!force) {
            if (currentStatus === 'draft' && newStatus === 'active') {
                if (Rules &&
                    typeof Rules.canStartTournament === 'function') {
                    if (!Rules.canStartTournament(tournament)) {
                        return Promise.resolve(failure(
                            'Tournament prerequisites for start ' +
                            'are not met.'
                        ));
                    }
                }
            }

            if (currentStatus === 'active' &&
                newStatus === 'completed') {
                if (Rules &&
                    typeof Rules.isReadyForCompletion === 'function') {
                    if (!Rules.isReadyForCompletion(tournament)) {
                        return Promise.resolve(failure(
                            'Tournament is not ready for completion.'
                        ));
                    }
                }

                var allRoundsComplete =
                    Array.isArray(tournament.rounds) &&
                    tournament.rounds.length > 0 &&
                    tournament.rounds.every(function(r) {
                        return r && r.status === 'completed';
                    });

                if (!allRoundsComplete) {
                    return Promise.resolve(failure(
                        'All rounds must be complete.'
                    ));
                }
                // No winner requirement.
            }
        }

        var targetId = normaliseId(tournamentId);

        return MutationPipeline.performMutation({
            validate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    return {
                        valid: false,
                        message: 'Tournament no longer exists.'
                    };
                }
                if (current.status !== currentStatus) {
                    return {
                        valid: false,
                        message:
                            'Tournament status has changed since this ' +
                            'request was made.'
                    };
                }
                return { valid: true };
            },
            mutate: function(appDataSnapshot) {
                var current = findTournamentInSnapshot(
                    appDataSnapshot,
                    targetId
                );
                if (!current) {
                    throw new Error(
                        'Tournament not found in data store.'
                    );
                }
                current.status = newStatus;
                return { id: targetId, status: newStatus };
            },
            logMessage: 'Transitioned tournament to "' + newStatus +
                '": ' + (tournament.name || targetId),
            successMessage: 'Tournament status updated!',
            failureMessage: 'Failed to update tournament status.'
        });
    }

    /**
     * Complete a tournament.
     *
     * Thin wrapper around transitionStatus. No winner required.
     */
    function completeTournament(tournamentId, force) {
        return transitionStatus(tournamentId, 'completed', force === true);
    }

    // ============================================================
    // LIFECYCLE QUERIES - SYNCHRONOUS
    // ============================================================

    function getLifecycleStatus(tournamentId) {
        var tournament = getTournamentInternal(tournamentId);
        if (!tournament) {
            return {
                status: 'unknown',
                valid: false,
                mutable: false,
                canEditMetadata: false,
                canModifyParticipants: false,
                canAddRounds: false,
                canRemoveRounds: false,
                canModifyEliminations: false,
                canComplete: false,
                terminal: false,
                description: 'Tournament not found'
            };
        }
        return Lifecycle.getLifecycleStatus(tournament);
    }

    function getLifecycleRules(status) {
        return Lifecycle.getLifecycleRules(status);
    }

    function getAllowedTransitions(tournamentId) {
        var tournament = getTournamentInternal(tournamentId);
        if (!tournament) { return []; }
        return Lifecycle.getTransitionOptions(tournament.status);
    }

    // ============================================================
    // PUBLIC READ HELPERS - SYNCHRONOUS
    // ============================================================

    function getTournament(id) {
        return Queries.getTournament(id);
    }

    function getTournaments() {
        return Queries.getTournaments();
    }

    function getParticipants(tournamentId) {
        return Queries.getParticipants(tournamentId);
    }

    function getRounds(tournamentId) {
        return Queries.getRounds(tournamentId);
    }

    function getRoundCount(tournamentId) {
        return Queries.getRoundCount(tournamentId);
    }

    function getCurrentRound(tournament) {
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return 0;
        }
        return tournament.rounds.length;
    }

    /**
     * Get the last round whose status is not 'completed'.
     * Returns null when every round is complete, or the tournament
     * has no rounds.
     */
    function getActiveRound(tournamentId) {
        var tournament = getTournamentInternal(tournamentId);
        if (!tournament || !Array.isArray(tournament.rounds)) {
            return null;
        }
        for (var i = tournament.rounds.length - 1; i >= 0; i--) {
            var round = tournament.rounds[i];
            if (round && round.status !== 'completed') {
                return deepClone(round);
            }
        }
        return null;
    }

    /**
     * Is the tournament complete?
     *
     * A completed tournament is one whose status is 'completed' and
     * whose every round has a status of 'completed'.
     *
     * A winner is NOT required. A tournament may finish with zero,
     * one, or many final passers.
     */
    function isComplete(tournamentId) {
        var tournament = getTournamentInternal(tournamentId);
        if (!tournament) {
            return false;
        }

        if (tournament.status !== 'completed') {
            return false;
        }

        if (!Array.isArray(tournament.rounds) ||
            tournament.rounds.length === 0) {
            return false;
        }

        return tournament.rounds.every(function(r) {
            return r && r.status === 'completed';
        });
    }

    /**
     * @deprecated No winner concept anymore. Returns null on new data.
     */
    function getWinner(tournamentId) {
        return Queries.getWinner(tournamentId);
    }

    function getActiveParticipants(tournamentId) {
        return Queries.getActiveParticipants(tournamentId);
    }

    function isParticipantInTournament(tournamentId, participantId, participantType) {
        return Queries.isParticipantInTournament(
            tournamentId,
            participantId,
            participantType
        );
    }

    function getParticipantType(tournamentId, participantId) {
        return Queries.getParticipantTypeFromRecord(
            tournamentId,
            participantId
        );
    }

    function isParticipantEliminated(tournamentId, participantId) {
        return Queries.isParticipantEliminated(tournamentId, participantId);
    }

    function validateTournament(tournament, strict) {
        return validateTournamentInternal(tournament, strict !== false);
    }

    function getValidationReport(tournament) {
        return Schema.getValidationReport(tournament);
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.TournamentCore = {
        // ---- Tournament CRUD (Promise-based) ----
        createTournament: createTournament,
        updateTournament: updateTournament,
        deleteTournament: deleteTournament,

        // ---- Participant Management (Promise-based) ----
        addParticipant: addParticipant,
        removeParticipant: removeParticipant,

        // ---- Round Management (Promise-based, ID-based) ----
        addRound: addRound,
        removeRound: removeRound,

        // ---- Status Transitions (Promise-based) ----
        transitionStatus: transitionStatus,
        completeTournament: completeTournament,

        // ---- Lifecycle Status (synchronous) ----
        getLifecycleStatus: getLifecycleStatus,
        getLifecycleRules: getLifecycleRules,
        getAllowedTransitions: getAllowedTransitions,

        // ---- Cascade helpers ----
        stripCharacterRefs: stripCharacterRefs,

        // ---- Query Helpers (read-only, defensive copies) ----
        getTournament: getTournament,
        getTournaments: getTournaments,
        getParticipants: getParticipants,
        getRounds: getRounds,
        getRoundCount: getRoundCount,
        getCurrentRound: getCurrentRound,
        getActiveRound: getActiveRound,
        isComplete: isComplete,
        getWinner: getWinner,
        getActiveParticipants: getActiveParticipants,
        isParticipantInTournament: isParticipantInTournament,
        getParticipantType: getParticipantType,
        isParticipantEliminated: isParticipantEliminated,
        validateTournament: validateTournament,
        getValidationReport: getValidationReport
    };

})();
