/**
 * js/modules/characters/character-crud.js - Character CRUD Operations
 * Path: js/modules/characters/character-crud.js
 * 
 * This module handles all character CRUD operations with:
 * - Clean persistence boundary using MutationPipeline
 * - Proper rollback on save failure (root-preserving)
 * - Returns structured results for caller handling
 * - No UI dependencies (no notifications, no confirm, no rendering)
 * - No DOM access
 * 
 * MUTATION FLOW:
 *   CharacterEvents/controller calls CharacterCRUD.save(dto)
 *   ↓
 *   MutationPipeline.performMutation({
 *       validate: pure validation,
 *       mutate: domain mutation,
 *       logMessage: activity log message,
 *       successMessage: user-facing message
 *   })
 *   ↓
 *   Returns { success: boolean, data?: object, message?: string }
 * 
 * STATE SOURCE OF TRUTH:
 *   - window.data is the source of truth for persisted application data
 *   - Mutations are applied to window.data through MutationPipeline
 *   - Rollback restores window.data contents (preserves root identity)
 *   - Character IDs are generated by IdUtils
 * 
 * DEATH MODEL:
 *   - deathYear is the source of truth for "when does this character die"
 *   - deceased is a DERIVED field: it means "is dead as of currentYear"
 *   - Consumers should prefer CharacterQueries.isDeceased(char, year)
 *     when they need to know alive/dead at a specific point in time
 *   - deathAge is auto-filled from birthYear + deathYear on save if missing
 *   - deathWeek is preserved for legacy data but not actively collected
 * 
 * IMPORTANT:
 *   - No DOM extraction here - form extraction is in character-form.js
 *   - No UI rendering here - rendering is in character-form.js
 *   - This module only handles CRUD operations and persistence
 *   - USES CharacterQueries for character data and display names
 *   - USES MutationPipeline for transaction management
 *   - USES IdUtils for ID generation
 *   - USES CharacterConstants for domain constants
 *   - Returns structured results (caller handles notifications)
 * 
 * DEPENDENCIES:
 *   - window.CharacterQueries (from character-queries.js) - MANDATORY
 *   - window.MutationPipeline (from mutation-pipeline.js) - MANDATORY
 *   - window.IdUtils (from id-utils.js) - MANDATORY
 *   - window.CharacterConstants (from character-constants.js) - MANDATORY
 */

(function() {
    'use strict';

    // Guard against duplicate script loading
    if (window.__characterCrudLoaded) {
        return;
    }
    window.__characterCrudLoaded = true;

    // ============================================================
    // DEPENDENCY IMPORTS - MANDATORY (no fallbacks)
    // ============================================================

    var CharacterQueries = window.CharacterQueries;
    var MutationPipeline = window.MutationPipeline;
    var IdUtils = window.IdUtils;
    var CharacterConstants = window.CharacterConstants;

    // ============================================================
    // CONSTANTS - From CharacterConstants (MANDATORY)
    // ============================================================

    var STAT_KEYS = CharacterConstants.STAT_KEYS;
    var STAT_MIN = CharacterConstants.STAT_MIN;
    var STAT_MAX = CharacterConstants.STAT_MAX;
    var STAT_DEFAULT = CharacterConstants.STAT_DEFAULT;
    var MAX_SPECIAL_MOVES = CharacterConstants.MAX_SPECIAL_MOVES;
    var MAX_MOVE_NAME_LENGTH = CharacterConstants.MAX_MOVE_NAME_LENGTH;
    var MAX_MOVE_DESCRIPTION_LENGTH = CharacterConstants.MAX_MOVE_DESCRIPTION_LENGTH;

    // ============================================================
    // DEPENDENCY CHECK
    // ============================================================

    function checkDependencies() {
        var missing = [];

        if (!CharacterQueries || typeof CharacterQueries.getCharacterById !== 'function') {
            missing.push('CharacterQueries.getCharacterById');
        }
        if (!CharacterQueries || typeof CharacterQueries.getDisplayName !== 'function') {
            missing.push('CharacterQueries.getDisplayName');
        }

        if (!MutationPipeline || typeof MutationPipeline.performMutation !== 'function') {
            missing.push('MutationPipeline.performMutation');
        }

        if (!IdUtils || typeof IdUtils.generateId !== 'function') {
            missing.push('IdUtils.generateId');
        }

        if (!CharacterConstants) {
            missing.push('CharacterConstants');
        }

        if (missing.length > 0) {
            console.warn('CharacterCRUD: Missing dependencies:', missing.join(', '));
            return false;
        }
        return true;
    }

    // ============================================================
    // HELPERS
    // ============================================================

    function getCurrentYear() {
        if (window.data && typeof window.data.currentYear === 'number') {
            return window.data.currentYear;
        }
        return new Date().getFullYear();
    }

    /**
     * Compute the cached `deceased` boolean from the death fields
     * relative to the current application year.
     * 
     * Rules:
     *   - No deathYear → alive
     *   - deathYear <= currentYear → dead
     *   - deathYear > currentYear → alive (they die in the future)
     * 
     * @param {object} data - Normalised character data
     * @returns {boolean} True if the character is dead as of current year
     */
    function computeCachedDeceased(data) {
        var deathYear = parseInt(data.deathYear, 10);
        if (isNaN(deathYear)) { return false; }
        return deathYear <= getCurrentYear();
    }

    // ============================================================
    // CHARACTER VALIDATION - Pure domain validation
    // ============================================================

    /**
     * Validate character data.
     * This is a PURE function - no side effects, no state mutation.
     * 
     * @param {object} charData - Character data to validate
     * @returns {object} { valid: boolean, message?: string }
     */
    function validateCharacter(charData) {
        if (!charData.firstName || charData.firstName.trim() === '') {
            return { valid: false, message: 'First name is required.' };
        }
        if (!charData.lastName || charData.lastName.trim() === '') {
            return { valid: false, message: 'Last name is required.' };
        }

        // Death validation
        // A character is either alive (no deathYear) or dead (deathYear set).
        // If dead, we need at least the death year.
        var hasDeathYear = charData.deathYear !== undefined &&
                           charData.deathYear !== null &&
                           String(charData.deathYear).trim() !== '';

        if (hasDeathYear) {
            var year = parseInt(charData.deathYear, 10);
            if (isNaN(year) || year < 1 || year > 9999) {
                return { valid: false, message: 'Death Year must be a valid year.' };
            }
        }

        // Death age validation (optional)
        if (charData.deathAge !== undefined &&
            charData.deathAge !== null &&
            String(charData.deathAge).trim() !== '') {
            var age = parseInt(charData.deathAge, 10);
            if (isNaN(age) || age < 0 || age > 999) {
                return { valid: false, message: 'Death Age must be a valid age.' };
            }
        }

        // Death week validation (legacy field, preserved if present)
        if (charData.deathWeek !== undefined &&
            charData.deathWeek !== null &&
            String(charData.deathWeek).trim() !== '') {
            var week = parseInt(charData.deathWeek, 10);
            if (isNaN(week) || week < 1 || week > 52) {
                return { valid: false, message: 'Death Week must be between 1 and 52.' };
            }
        }

        // Special moves validation
        var physicalMoves = charData.specialMoves && charData.specialMoves.physical ? charData.specialMoves.physical : [];
        var magicalMoves = charData.specialMoves && charData.specialMoves.magical ? charData.specialMoves.magical : [];

        if (physicalMoves.length > MAX_SPECIAL_MOVES) {
            return { valid: false, message: 'Too many physical special moves. Maximum is ' + MAX_SPECIAL_MOVES + '.' };
        }
        if (magicalMoves.length > MAX_SPECIAL_MOVES) {
            return { valid: false, message: 'Too many magical special moves. Maximum is ' + MAX_SPECIAL_MOVES + '.' };
        }

        var allMoves = physicalMoves.concat(magicalMoves);
        for (var i = 0; i < allMoves.length; i++) {
            var move = allMoves[i];
            if (move.name && move.name.length > MAX_MOVE_NAME_LENGTH) {
                return { valid: false, message: 'Move name exceeds maximum length of ' + MAX_MOVE_NAME_LENGTH + ' characters.' };
            }
            if (move.description && move.description.length > MAX_MOVE_DESCRIPTION_LENGTH) {
                return { valid: false, message: 'Move description exceeds maximum length of ' + MAX_MOVE_DESCRIPTION_LENGTH + ' characters.' };
            }
        }

        // Stats validation - only validate canonical stat keys
        var stats = charData.stats || {};
        for (var i = 0; i < STAT_KEYS.length; i++) {
            var key = STAT_KEYS[i];
            var val = stats[key];
            if (val === undefined || val === null) {
                continue;
            }
            if (typeof val !== 'number' || isNaN(val) || val < STAT_MIN || val > STAT_MAX) {
                return { valid: false, message: 'Stat "' + key + '" must be between ' + STAT_MIN + ' and ' + STAT_MAX + '.' };
            }
        }

        return { valid: true };
    }

    // ============================================================
    // NORMALISATION HELPERS
    // ============================================================

    /**
     * Normalise character data before save.
     * 
     * This function is the SINGLE boundary between form DTOs and
     * persisted character records. It:
     *   - Trims string fields
     *   - Clamps stats to their allowed range
     *   - Ensures array fields are arrays
     *   - Normalises displayParts into a canonical 5-boolean object
     *   - Derives `deceased` from `deathYear` relative to current year
     *   - Auto-fills `deathAge` from `birthYear` + `deathYear` if missing
     *   - Does NOT touch fields it doesn't know about (those are
     *     preserved on edit via Object.assign in updateExistingCharacter)
     * 
     * @param {object} charData - Character data from form collect
     * @returns {object} Normalised character data
     */
    function normaliseCharacterData(charData) {
        var data = {};

        // ---- Name fields ----
        data.firstName = charData.firstName ? charData.firstName.trim() : '';
        data.lastName = charData.lastName ? charData.lastName.trim() : '';
        data.middleName = charData.middleName ? charData.middleName.trim() : '';
        data.nickname = charData.nickname ? charData.nickname.trim() : '';
        data.alias = charData.alias ? charData.alias.trim() : '';

        // Previous names - array of trimmed non-empty strings
        data.previousNames = Array.isArray(charData.previousNames)
            ? charData.previousNames
                .map(function(n) { return String(n || '').trim(); })
                .filter(function(n) { return n !== ''; })
            : [];

        // Display parts - canonical 5-boolean object
        // Defaults: first/middle/last on, nickname/alias off
        var incomingDp = charData.displayParts && typeof charData.displayParts === 'object'
            ? charData.displayParts
            : null;

        data.displayParts = {
            first:    incomingDp ? incomingDp.first    !== false : true,
            middle:   incomingDp ? incomingDp.middle   !== false : true,
            last:     incomingDp ? incomingDp.last     !== false : true,
            nickname: incomingDp ? incomingDp.nickname === true  : false,
            alias:    incomingDp ? incomingDp.alias    === true  : false
        };

        // Legacy nameFormat - kept for backward compatibility with the
        // getDisplayName() legacy fallback path. New characters don't
        // set this; existing characters keep whatever they had.
        if (charData.nameFormat !== undefined) {
            data.nameFormat = charData.nameFormat || 'firstlast';
        }

        // ---- Physical fields ----
        data.gender = charData.gender ? charData.gender.trim() : '';
        data.birthYear = charData.birthYear ? String(charData.birthYear).trim() : '';
        data.eyes = charData.eyes ? charData.eyes.trim() : '';
        data.hair = charData.hair ? charData.hair.trim() : '';
        data.skin = charData.skin ? charData.skin.trim() : '';
        data.height = charData.height ? charData.height.trim() : '';
        data.weight = charData.weight ? charData.weight.trim() : '';
        data.build = charData.build ? charData.build.trim() : '';
        data.appearanceNotes = charData.appearanceNotes ? charData.appearanceNotes.trim() : '';

        // ---- Career / professional fields ----
        data.specialty = charData.specialty ? charData.specialty.trim() : '';
        data.attraction = charData.attraction ? charData.attraction.trim() : '';
        data.sexuality = charData.sexuality ? charData.sexuality.trim() : '';
        data.notes = charData.notes ? charData.notes.trim() : '';

        // ---- Academic fields ----
        if (charData.graduatingClassId !== undefined) {
            data.graduatingClassId = charData.graduatingClassId || null;
        }
        if (charData.graduatingClassInstructor !== undefined) {
            data.graduatingClassInstructor = charData.graduatingClassInstructor === true;
        }

        // ---- Stats ----
        data.stats = {};
        for (var i = 0; i < STAT_KEYS.length; i++) {
            var key = STAT_KEYS[i];
            var val = charData.stats && charData.stats[key] !== undefined ? charData.stats[key] : STAT_DEFAULT;
            data.stats[key] = Math.max(STAT_MIN, Math.min(STAT_MAX, val));
        }

        // ---- Magic ----
        if (charData.magic !== undefined) {
            data.magic = {};
            var MagicConstants = window.MagicConstants;
            var magicKeys = MagicConstants && MagicConstants.getTypeKeys
                ? MagicConstants.getTypeKeys()
                : Object.keys(charData.magic || {});
            for (var i = 0; i < magicKeys.length; i++) {
                var key = magicKeys[i];
                data.magic[key] = charData.magic && charData.magic[key] !== undefined
                    ? charData.magic[key]
                    : 0;
            }
        }

        // ---- Special moves ----
        if (charData.specialMoves !== undefined) {
            data.specialMoves = {
                physical: Array.isArray(charData.specialMoves && charData.specialMoves.physical)
                    ? charData.specialMoves.physical.slice()
                    : [],
                magical: Array.isArray(charData.specialMoves && charData.specialMoves.magical)
                    ? charData.specialMoves.magical.slice()
                    : []
            };
        }

        // ---- Career status ----
        if (charData.careerStatus !== undefined) {
            data.careerStatus = Array.isArray(charData.careerStatus)
                ? charData.careerStatus.slice()
                : [];
        }

        // ---- Class IDs ----
        if (charData.classIds !== undefined) {
            data.classIds = Array.isArray(charData.classIds)
                ? charData.classIds.slice()
                : [];
        }

        // ---- Personality ----
        if (charData.personality !== undefined) {
            data.personality = charData.personality ? Object.assign({}, charData.personality) : {};
        }

        // ---- Death fields ----
        // deathYear is the source of truth. `deceased` is DERIVED from
        // it relative to the current year, so it can flip back and forth
        // as the user scrubs the year.
        data.deathYear = charData.deathYear ? String(charData.deathYear).trim() : '';
        data.deathCause = charData.deathCause ? charData.deathCause.trim() : '';

        // deathWeek - legacy field. Only set if the caller provided it.
        // The form no longer collects it, but if it exists on the source
        // data, preserve it.
        if (charData.deathWeek !== undefined) {
            data.deathWeek = charData.deathWeek ? String(charData.deathWeek).trim() : '';
        }

        // deathAge - auto-fill from birthYear + deathYear if the caller
        // didn't provide an explicit value and both years are known.
        if (charData.deathAge !== undefined &&
            charData.deathAge !== null &&
            String(charData.deathAge).trim() !== '') {
            data.deathAge = String(charData.deathAge).trim();
        } else if (data.deathYear && data.birthYear) {
            var birthY = parseInt(data.birthYear, 10);
            var deathY = parseInt(data.deathYear, 10);
            if (!isNaN(birthY) && !isNaN(deathY) && deathY >= birthY) {
                data.deathAge = String(deathY - birthY);
            } else {
                data.deathAge = '';
            }
        } else {
            data.deathAge = '';
        }

        // Derive the cached `deceased` flag from deathYear.
        // This is what legacy consumers still read.
        data.deceased = computeCachedDeceased(data);

        return data;
    }

    // ============================================================
    // SAVE CHARACTER - Uses MutationPipeline
    // ============================================================

    /**
     * Save a character (create or update).
     * 
     * @param {object} formData - Form data DTO from CharacterForm.collect()
     * @returns {Promise<{ success: boolean, data?: object, message?: string }>}
     */
    function save(formData) {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        // ---- PHASE 1: VALIDATE INPUT ----
        if (!formData || typeof formData !== 'object') {
            return Promise.resolve({
                success: false,
                message: 'Form data is required.'
            });
        }

        var normalised = normaliseCharacterData(formData);
        var validation = validateCharacter(normalised);

        if (!validation.valid) {
            return Promise.resolve({
                success: false,
                message: validation.message
            });
        }

        var editId = formData._editId || null;
        var isEditing = editId !== null && editId !== undefined && editId !== '';

        var existingChar = null;
        var name = normalised.firstName + ' ' + normalised.lastName;

        if (isEditing) {
            existingChar = CharacterQueries.getCharacterById(editId);
            if (!existingChar) {
                return Promise.resolve({
                    success: false,
                    message: 'Character not found.'
                });
            }
            name = CharacterQueries.getDisplayName(existingChar);
        }

        // ---- PHASE 2: EXECUTE MUTATION VIA PIPELINE ----
        return MutationPipeline.performMutation({
            validate: function(data) {
                var reValidation = validateCharacter(normalised);
                if (!reValidation.valid) {
                    return {
                        valid: false,
                        message: reValidation.message
                    };
                }

                if (isEditing) {
                    var currentChar = CharacterQueries.getCharacterById(editId);
                    if (!currentChar) {
                        return {
                            valid: false,
                            message: 'Character no longer exists.'
                        };
                    }
                }

                return { valid: true };
            },

            mutate: function(data) {
                var result;

                if (isEditing) {
                    result = updateExistingCharacter(existingChar, normalised, data);
                } else {
                    result = createNewCharacter(normalised, data);
                }

                if (!result.success) {
                    throw new Error(result.error || 'Failed to save character.');
                }

                return {
                    id: result.id,
                    character: result.character,
                    isNew: !isEditing
                };
            },

            logMessage: function(result) {
                return isEditing
                    ? 'Updated character: ' + name
                    : 'Created character: ' + name;
            },

            successMessage: function(result) {
                return isEditing
                    ? 'Character updated successfully!'
                    : 'Character created successfully!';
            },

            failureMessage: 'Failed to save character.'
        });
    }

    // ============================================================
    // MUTATION HELPERS - Called within pipeline
    // ============================================================

    function updateExistingCharacter(existing, normalised, data) {
        var index = data.characters.findIndex(function(c) {
            return c && String(c.id) === String(existing.id);
        });

        if (index === -1) {
            return { success: false, error: 'Character not found in data store.' };
        }

        var current = data.characters[index];

        // Preserve system-managed fields
        var preserved = {
            id: current.id,
            createdAt: current.createdAt,
            eliminations: Array.isArray(current.eliminations) ? current.eliminations.slice() : [],
            eliminatedWeeks: Array.isArray(current.eliminatedWeeks) ? current.eliminatedWeeks.slice() : []
        };

        // Merge - normalised overrides everything except preserved fields.
        // Any field in `current` that is NOT in `normalised` is retained
        // automatically by Object.assign's left-to-right semantics.
        var updated = Object.assign({}, current, normalised, preserved);

        data.characters[index] = updated;

        return {
            success: true,
            id: updated.id,
            character: updated
        };
    }

    function createNewCharacter(normalised, data) {
        var id = IdUtils.generateId('char');

        var newChar = Object.assign({}, normalised, {
            id: id,
            eliminations: [],
            eliminatedWeeks: [],
            createdAt: new Date().toISOString()
        });

        data.characters.push(newChar);

        return {
            success: true,
            id: id,
            character: newChar
        };
    }

    // ============================================================
    // DELETE CHARACTER - Uses MutationPipeline
    // ============================================================

    /**
     * Delete a character.
     * 
     * @param {string} id - Character ID
     * @returns {Promise<{ success: boolean, message?: string }>}
     */
    function deleteCharacter(id) {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        if (!id) {
            return Promise.resolve({
                success: false,
                message: 'Character ID is required.'
            });
        }

        var targetId = String(id);

        var char = CharacterQueries.getCharacterById(targetId);
        if (!char) {
            return Promise.resolve({
                success: false,
                message: 'Character not found.'
            });
        }

        var name = CharacterQueries.getDisplayName(char);

        return MutationPipeline.performMutation({
            validate: function(data) {
                var currentChar = CharacterQueries.getCharacterById(targetId);
                if (!currentChar) {
                    return {
                        valid: false,
                        message: 'Character no longer exists.'
                    };
                }

                return { valid: true };
            },

            mutate: function(data) {
                // Remove character from all teams
                if (Array.isArray(data.teams)) {
                    data.teams.forEach(function(team) {
                        if (Array.isArray(team.members)) {
                            team.members = team.members.filter(function(m) {
                                return !m || String(m.characterId) !== targetId;
                            });
                        }
                    });
                }

                // Remove character
                var found = false;
                data.characters = data.characters.filter(function(c) {
                    if (c && String(c.id) === targetId) {
                        found = true;
                        return false;
                    }
                    return true;
                });

                if (!found) {
                    throw new Error('Character not found in data store.');
                }

                return { deleted: true };
            },

            logMessage: function() {
                return 'Deleted character: ' + name;
            },

            successMessage: 'Character deleted successfully!',
            failureMessage: 'Failed to delete character.'
        });
    }

    // ============================================================
    // BULK OPERATIONS
    // ============================================================

    /**
     * Delete all characters.
     * USE WITH CAUTION - mainly for testing.
     * 
     * @returns {Promise<{ success: boolean, count?: number, message?: string }>}
     */
    function deleteAllCharacters() {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        if (!confirm('Delete ALL characters permanently? This cannot be undone.')) {
            return Promise.resolve({
                success: false,
                message: 'Operation cancelled.'
            });
        }

        return MutationPipeline.performMutation({
            validate: function(data) {
                var count = Array.isArray(data.characters) ? data.characters.length : 0;
                if (count === 0) {
                    return {
                        valid: false,
                        message: 'No characters to delete.'
                    };
                }
                return { valid: true };
            },

            mutate: function(data) {
                var count = Array.isArray(data.characters) ? data.characters.length : 0;

                if (Array.isArray(data.teams)) {
                    data.teams.forEach(function(team) {
                        if (Array.isArray(team.members)) {
                            team.members = [];
                        }
                    });
                }

                data.characters = [];

                return { deletedCount: count };
            },

            logMessage: function(result) {
                return 'Deleted all characters (' + result.deletedCount + ')';
            },

            successMessage: function(result) {
                return 'Deleted ' + result.deletedCount + ' characters.';
            },
            failureMessage: 'Failed to delete all characters.'
        });
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.CharacterCRUD = {
        save: save,
        delete: deleteCharacter,
        deleteAll: deleteAllCharacters,

        validateCharacter: validateCharacter,
        normaliseCharacterData: normaliseCharacterData
    };

})();