/**
 * js/modules/characters/character-crud.js - Character CRUD Operations
 * Path: js/modules/characters/character-crud.js
 *
 * This module handles all character CRUD operations with:
 * - Clean persistence boundary using MutationPipeline
 * - Proper rollback on save failure (root-preserving)
 * - Returns structured results for caller handling
 * - No UI dependencies (no notifications, no confirm, no rendering)
 * - No DOM access
 *
 * MUTATION FLOW:
 *   CharacterEvents/controller calls CharacterCRUD.save(dto)
 *   ↓
 *   MutationPipeline.performMutation({
 *       validate: pure validation,
 *       mutate: domain mutation,
 *       logMessage: activity log message,
 *       successMessage: user-facing message
 *   })
 *   ↓
 *   Returns { success: boolean, data?: object, message?: string }
 *
 * STATE SOURCE OF TRUTH:
 *   - window.data is the source of truth for persisted application data
 *   - Mutations are applied to window.data through MutationPipeline
 *   - Rollback restores window.data contents (preserves root identity)
 *   - Character IDs are generated by IdUtils
 *
 * CLASS MEMBERSHIP (v15+):
 *   - CharacterCRUD does NOT own or originate character.classIds.
 *     normaliseCharacterData() deliberately does not accept classIds.
 *     This makes the CRUD/membership split structural: no caller can
 *     replace the membership list by passing classIds through the
 *     generic save path.
 *   - createNewCharacter() initialises classIds to [] so new characters
 *     satisfy the invariant "every character has a classIds array".
 *   - Membership mutations live in AcademyClasses.
 *   - Academy roster queries derive from character.classIds; there is
 *     no separate academy.classStudents store after v15.
 *
 * DISCIPLINE ENROLLMENT (v16+):
 *   - CharacterCRUD does NOT own or originate discipline enrollment.
 *     normaliseCharacterData() deliberately does not accept
 *     disciplineIds.
 *   - Enrollment is CLASS-SCOPED and lives at
 *     academy.enrolments[classId][charId] = [disciplineId].
 *   - Enrollment mutations live in AcademyEnrolments.
 *   - createNewCharacter() does NOT initialise disciplineIds. The
 *     field is not part of the character record.
 *   - updateExistingCharacter() does NOT preserve disciplineIds. If a
 *     legacy character record still carries the field, it is left in
 *     place by the Object.assign in updateExistingCharacter (because
 *     `current` carries it and `normalised` does not overwrite it),
 *     but nothing reads it. It will disappear naturally as records
 *     are edited, or it can be pruned by a future migration.
 *
 * CHARACTER MODE (v27+):
 *   - Every character record carries a persisted `mode` field:
 *       mode: 'student' | 'instructor'   (default 'student')
 *   - The mode is a DOMAIN FACT. It drives which tabs the Academy
 *     character detail panel renders and how the character's
 *     enrolments are interpreted. It is NOT session state.
 *   - It is set through setMode(charId, mode), a dedicated mutation
 *     that routes through MutationPipeline.
 *   - It is NOT settable through save(). normaliseCharacterData()
 *     does not read `mode` from the DTO, and updateExistingCharacter
 *     preserves whatever is currently on the record. This mirrors the
 *     classIds and disciplineIds rule: fields owned by a dedicated
 *     mutation are not touched by the generic save path.
 *   - createNewCharacter() initialises mode to 'student' so new
 *     characters satisfy the invariant "every character has a valid
 *     mode".
 *
 * DEATH MODEL:
 *   - deathYear is the source of truth for "when does this character die"
 *   - deceased is a DERIVED field: it means "is dead as of currentYear"
 *   - Consumers should prefer CharacterQueries.isDeceased(char, year)
 *     when they need to know alive/dead at a specific point in time
 *   - deathAge is auto-filled from birthYear + deathYear on save if missing
 *   - deathWeek is preserved for legacy data but not actively collected
 *
 * DEATH → PROFESSIONAL TEAM CASCADE:
 *   When a save transitions deathYear from blank to a parseable
 *   year, updateExistingCharacter calls
 *   TeamCore.endStintsForCharacter(data, charId, deathYear) inside
 *   the same pipeline transaction.
 *
 *   SCOPE:
 *     Professional teams only. Academic teams are managed by the
 *     Academy module; temporary and civilian team membership does
 *     not participate in this cascade.
 *
 *   TRIGGER:
 *     blank → parseable year. A save that changes deathYear from
 *     one non-blank year to another does NOT re-end stints (they
 *     were already ended on the first transition). A save that
 *     edits an unrelated field does not fire the cascade.
 *
 *   NON-REVERSIBLE:
 *     Clearing deathYear does NOT restore the ended stints. The
 *     user reopens stints by hand from the member manager if they
 *     want to undo a death. This matches the semantics of
 *     TeamCore.endMemberInterval.
 *
 *   FAILURE MODE:
 *     TeamCore is an OPTIONAL dependency of this module. When it
 *     is absent, the cascade is skipped silently — a character
 *     module that loads without the team module must still work.
 *     When TeamCore is present but endStintsForCharacter is not
 *     exported (older load order), the cascade is also skipped.
 *
 * YEAR SEMANTICS:
 *   - Years are UNBOUNDED positive integers.
 *   - There is no MIN_YEAR or MAX_YEAR.
 *   - deathYear must be an integer >= 1 (no upper bound).
 *   - birthYear is stored as a string and is not bounded here.
 *
 * COMBAT MODEL (v14):
 *   - hp: number, 0–999, manual or rolled
 *   - mp: number, 0–999, manual or rolled
 *   - weapons: array of { id, name, type, notes }
 *   - combatNotes: string, Combat-tab-specific notes (SEPARATE from notes)
 *   - Physical/magical classes are DERIVED from stats, never stored
 *
 * DELETE CASCADE SEMANTICS:
 *   Deleting a character is a CASCADE. In a single transaction it:
 *     1. Removes the character from every team's members list.
 *     2. Removes the character from academy.weeklyTeams (this used to
 *        be inline; now routed through AcademyCascade).
 *     3. Strips curriculum.autoGroups references (instructor + students).
 *     4. Removes academy.grades records.
 *     5. Removes academy.rankings records.
 *     6. Removes academy.enrolments entries (class-scoped).
 *     7. Removes academy.socialScores entries.
 *     8. Removes social relationships.
 *     9. Removes mission support-personnel references.
 *    10. Removes tournament participant / elimination / winner / match
 *        references.
 *    11. Removes curriculum.schedules[charId].
 *    12. Removes curriculum.restDays[charId].
 *    13. Prunes curriculum.metadata keys prefixed with the character ID.
 *    14. Deletes the character entity itself.
 *
 *   Steps 2–10 are delegated to AcademyCascade.characterDeleted.
 *   Step 1 and steps 11–13 stay inline, because they touch character-
 *   adjacent stores (team entity rosters and curriculum) that are not
 *   academy-domain concerns.
 *
 * IMPORTANT:
 *   - No DOM extraction here - form extraction is in character-form.js
 *   - No UI rendering here - rendering is in character-form.js
 *   - This module only handles CRUD operations and persistence
 *   - USES CharacterQueries for character data and display names
 *   - USES MutationPipeline for transaction management
 *   - USES IdUtils for ID generation
 *   - USES CharacterConstants for domain constants
 *   - Returns structured results (caller handles notifications)
 *
 * DEPENDENCIES:
 *   - window.CharacterQueries (from character-queries.js) - MANDATORY
 *   - window.MutationPipeline (from mutation-pipeline.js) - MANDATORY
 *   - window.IdUtils (from id-utils.js) - MANDATORY
 *   - window.CharacterConstants (from character-constants.js) - MANDATORY
 *   - window.AcademyCascade (from academy-cascade.js) - LAZY (optional)
 *   - window.TeamCore (from team-core.js) - LAZY (optional)
 *     When present, endStintsForCharacter is called on the
 *     deathYear blank → set transition. When absent, the death
 *     cascade is skipped.
 */

(function() {
    'use strict';

    // Guard against duplicate script loading
    if (window.__characterCrudLoaded) {
        return;
    }
    window.__characterCrudLoaded = true;

    // ============================================================
    // DEPENDENCY IMPORTS - MANDATORY (no fallbacks)
    // ============================================================

    var CharacterQueries = window.CharacterQueries;
    var MutationPipeline = window.MutationPipeline;
    var IdUtils = window.IdUtils;
    var CharacterConstants = window.CharacterConstants;

    // ============================================================
    // CONSTANTS - From CharacterConstants (MANDATORY)
    // ============================================================

    var STAT_KEYS = CharacterConstants.STAT_KEYS;
    var STAT_MIN = CharacterConstants.STAT_MIN;
    var STAT_MAX = CharacterConstants.STAT_MAX;
    var STAT_DEFAULT = CharacterConstants.STAT_DEFAULT;
    var MAX_SPECIAL_MOVES = CharacterConstants.MAX_SPECIAL_MOVES;
    var MAX_MOVE_NAME_LENGTH = CharacterConstants.MAX_MOVE_NAME_LENGTH;
    var MAX_MOVE_DESCRIPTION_LENGTH = CharacterConstants.MAX_MOVE_DESCRIPTION_LENGTH;

    var HP_MIN = CharacterConstants.HP_MIN;
    var HP_MAX = CharacterConstants.HP_MAX;
    var HP_HARD_CAP = 999;

    var MP_MIN = CharacterConstants.MP_MIN;
    var MP_MAX = CharacterConstants.MP_MAX;
    var MP_HARD_CAP = 999;

    var MAX_WEAPONS = CharacterConstants.MAX_WEAPONS;
    var MAX_WEAPON_NAME_LENGTH = CharacterConstants.MAX_WEAPON_NAME_LENGTH;
    var MAX_WEAPON_NOTES_LENGTH = CharacterConstants.MAX_WEAPON_NOTES_LENGTH;
    var DEFAULT_WEAPON_TYPE = CharacterConstants.DEFAULT_WEAPON_TYPE;

    var VALID_MODES = ['student', 'instructor'];
    var DEFAULT_MODE = 'student';

    // ============================================================
    // DEPENDENCY CHECK
    // ============================================================

    function checkDependencies() {
        var missing = [];

        if (!CharacterQueries || typeof CharacterQueries.getCharacterById !== 'function') {
            missing.push('CharacterQueries.getCharacterById');
        }
        if (!CharacterQueries || typeof CharacterQueries.getDisplayName !== 'function') {
            missing.push('CharacterQueries.getDisplayName');
        }

        if (!MutationPipeline || typeof MutationPipeline.performMutation !== 'function') {
            missing.push('MutationPipeline.performMutation');
        }

        if (!IdUtils || typeof IdUtils.generateId !== 'function') {
            missing.push('IdUtils.generateId');
        }

        if (!CharacterConstants) {
            missing.push('CharacterConstants');
        }

        if (missing.length > 0) {
            console.warn('CharacterCRUD: Missing dependencies:', missing.join(', '));
            return false;
        }
        return true;
    }

    // ============================================================
    // HELPERS
    // ============================================================

    function getCurrentYear() {
        if (window.data && typeof window.data.currentYear === 'number') {
            return window.data.currentYear;
        }
        return new Date().getFullYear();
    }

    function computeCachedDeceased(data) {
        var deathYear = parseInt(data.deathYear, 10);
        if (isNaN(deathYear)) { return false; }
        return deathYear <= getCurrentYear();
    }

    function getAcademyCascade() {
        return window.AcademyCascade || null;
    }

    /**
     * Lazy accessor for TeamCore.
     *
     * TeamCore is an OPTIONAL dependency. The death cascade is
     * skipped when the module is absent, or when it does not export
     * endStintsForCharacter (older load order).
     */
    function getTeamCore() {
        return window.TeamCore || null;
    }

    function isValidMode(mode) {
        return mode === 'student' || mode === 'instructor';
    }

    /**
     * Parse a deathYear string. Returns an integer >= 1 or null.
     * Blank, malformed, and sub-1 values all return null.
     *
     * Used by the death cascade trigger and by the cascade call
     * itself, so the two agree on what "a parseable year" means.
     */
    function parseDeathYear(value) {
        if (value === undefined || value === null || value === '') {
            return null;
        }
        var n = parseInt(String(value).trim(), 10);
        if (isNaN(n) || n < 1) {
            return null;
        }
        return n;
    }

    // ============================================================
    // WEAPON NORMALISATION
    // ============================================================

    function normaliseWeapon(weapon) {
        if (!weapon || typeof weapon !== 'object' || Array.isArray(weapon)) {
            return null;
        }

        var id = (typeof weapon.id === 'string' && weapon.id)
            ? weapon.id
            : (IdUtils && typeof IdUtils.generateId === 'function'
                ? IdUtils.generateId('weapon')
                : 'weapon_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8));

        var name = typeof weapon.name === 'string' ? weapon.name.trim() : '';
        if (name.length > MAX_WEAPON_NAME_LENGTH) {
            name = name.slice(0, MAX_WEAPON_NAME_LENGTH);
        }

        var type = typeof weapon.type === 'string' && weapon.type
            ? weapon.type
            : DEFAULT_WEAPON_TYPE;

        if (CharacterConstants && typeof CharacterConstants.isValidWeaponType === 'function') {
            if (!CharacterConstants.isValidWeaponType(type)) {
                type = DEFAULT_WEAPON_TYPE;
            }
        }

        var notes = typeof weapon.notes === 'string' ? weapon.notes.trim() : '';
        if (notes.length > MAX_WEAPON_NOTES_LENGTH) {
            notes = notes.slice(0, MAX_WEAPON_NOTES_LENGTH);
        }

        return {
            id: id,
            name: name,
            type: type,
            notes: notes
        };
    }

    function normaliseWeapons(weapons) {
        if (!Array.isArray(weapons)) {
            return [];
        }

        var result = [];
        var seenIds = Object.create(null);

        for (var i = 0; i < weapons.length; i++) {
            var w = normaliseWeapon(weapons[i]);
            if (!w) { continue; }
            if (!w.name) { continue; }

            if (seenIds[w.id]) {
                w.id = (IdUtils && typeof IdUtils.generateId === 'function')
                    ? IdUtils.generateId('weapon')
                    : 'weapon_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8);
            }
            seenIds[w.id] = true;

            result.push(w);

            if (result.length >= MAX_WEAPONS) {
                break;
            }
        }

        return result;
    }

    // ============================================================
    // CHARACTER VALIDATION - Pure domain validation
    // ============================================================

    function validateCharacter(charData) {
        if (!charData.firstName || charData.firstName.trim() === '') {
            return { valid: false, message: 'First name is required.' };
        }
        if (!charData.lastName || charData.lastName.trim() === '') {
            return { valid: false, message: 'Last name is required.' };
        }

        // Death validation
        var hasDeathYear = charData.deathYear !== undefined &&
                           charData.deathYear !== null &&
                           String(charData.deathYear).trim() !== '';

        if (hasDeathYear) {
            var year = parseInt(charData.deathYear, 10);
            if (isNaN(year) || year < 1) {
                return { valid: false, message: 'Death Year must be a positive number.' };
            }
        }

        if (charData.deathAge !== undefined &&
            charData.deathAge !== null &&
            String(charData.deathAge).trim() !== '') {
            var age = parseInt(charData.deathAge, 10);
            if (isNaN(age) || age < 0 || age > 999) {
                return { valid: false, message: 'Death Age must be a valid age.' };
            }
        }

        if (charData.deathWeek !== undefined &&
            charData.deathWeek !== null &&
            String(charData.deathWeek).trim() !== '') {
            var week = parseInt(charData.deathWeek, 10);
            if (isNaN(week) || week < 1 || week > 52) {
                return { valid: false, message: 'Death Week must be between 1 and 52.' };
            }
        }

        // ---- HP / MP validation ----
        if (charData.hp !== undefined && charData.hp !== null && charData.hp !== '') {
            var hp = Number(charData.hp);
            if (isNaN(hp) || hp < 0 || hp > HP_HARD_CAP) {
                return { valid: false, message: 'HP must be a number between 0 and ' + HP_HARD_CAP + '.' };
            }
        }
        if (charData.mp !== undefined && charData.mp !== null && charData.mp !== '') {
            var mp = Number(charData.mp);
            if (isNaN(mp) || mp < 0 || mp > MP_HARD_CAP) {
                return { valid: false, message: 'MP must be a number between 0 and ' + MP_HARD_CAP + '.' };
            }
        }

        // ---- Weapons validation ----
        if (charData.weapons !== undefined) {
            if (!Array.isArray(charData.weapons)) {
                return { valid: false, message: 'Weapons must be an array.' };
            }
            if (charData.weapons.length > MAX_WEAPONS) {
                return { valid: false, message: 'Too many weapons. Maximum is ' + MAX_WEAPONS + '.' };
            }
            for (var i = 0; i < charData.weapons.length; i++) {
                var w = charData.weapons[i];
                if (!w || typeof w !== 'object' || Array.isArray(w)) {
                    return { valid: false, message: 'Weapon entry at index ' + i + ' is invalid.' };
                }
                if (w.name && w.name.length > MAX_WEAPON_NAME_LENGTH) {
                    return { valid: false, message: 'Weapon name exceeds maximum length of ' + MAX_WEAPON_NAME_LENGTH + '.' };
                }
                if (w.notes && w.notes.length > MAX_WEAPON_NOTES_LENGTH) {
                    return { valid: false, message: 'Weapon notes exceed maximum length of ' + MAX_WEAPON_NOTES_LENGTH + '.' };
                }
                if (w.type && CharacterConstants && typeof CharacterConstants.isValidWeaponType === 'function') {
                    if (!CharacterConstants.isValidWeaponType(w.type)) {
                        return { valid: false, message: 'Weapon type "' + w.type + '" is not recognised.' };
                    }
                }
            }
        }

        // Special moves validation
        var physicalMoves = charData.specialMoves && charData.specialMoves.physical ? charData.specialMoves.physical : [];
        var magicalMoves = charData.specialMoves && charData.specialMoves.magical ? charData.specialMoves.magical : [];

        if (physicalMoves.length > MAX_SPECIAL_MOVES) {
            return { valid: false, message: 'Too many physical special moves. Maximum is ' + MAX_SPECIAL_MOVES + '.' };
        }
        if (magicalMoves.length > MAX_SPECIAL_MOVES) {
            return { valid: false, message: 'Too many magical special moves. Maximum is ' + MAX_SPECIAL_MOVES + '.' };
        }

        var allMoves = physicalMoves.concat(magicalMoves);
        for (var j = 0; j < allMoves.length; j++) {
            var move = allMoves[j];
            if (move.name && move.name.length > MAX_MOVE_NAME_LENGTH) {
                return { valid: false, message: 'Move name exceeds maximum length of ' + MAX_MOVE_NAME_LENGTH + ' characters.' };
            }
            if (move.description && move.description.length > MAX_MOVE_DESCRIPTION_LENGTH) {
                return { valid: false, message: 'Move description exceeds maximum length of ' + MAX_MOVE_DESCRIPTION_LENGTH + ' characters.' };
            }
        }

        // Stats validation
        var stats = charData.stats || {};
        for (var k = 0; k < STAT_KEYS.length; k++) {
            var key = STAT_KEYS[k];
            var val = stats[key];
            if (val === undefined || val === null) {
                continue;
            }
            if (typeof val !== 'number' || isNaN(val) || val < STAT_MIN || val > STAT_MAX) {
                return { valid: false, message: 'Stat "' + key + '" must be between ' + STAT_MIN + ' and ' + STAT_MAX + '.' };
            }
        }

        return { valid: true };
    }

    // ============================================================
    // NORMALISATION HELPERS
    // ============================================================

    /**
     * Normalise character data before save.
     *
     * This function is the SINGLE boundary between form DTOs and
     * persisted character records. It:
     *   - Trims string fields
     *   - Clamps stats to their allowed range
     *   - Clamps hp/mp to their allowed range
     *   - Normalises weapons to a canonical shape
     *   - Ensures array fields are arrays
     *   - Normalises displayParts into a canonical 5-boolean object
     *   - Derives `deceased` from `deathYear` relative to current year
     *   - Auto-fills `deathAge` from `birthYear` + `deathYear` if missing
     *   - Does NOT touch fields it doesn't know about (those are
     *     preserved on edit via Object.assign in updateExistingCharacter)
     *
     * NOT NORMALISED HERE (owned by dedicated mutations):
     *   - classIds        (AcademyClasses)
     *   - disciplineIds   (AcademyEnrolments) — legacy field, dead
     *   - mode            (CharacterCRUD.setMode)
     *   - eliminations    (AcademyEliminations / TournamentEliminationCascade)
     *   - eliminatedWeeks (EliminationQueries.rebuildEliminatedWeeks)
     */
    function normaliseCharacterData(charData) {
        var data = {};

        // ---- Name fields ----
        data.firstName = charData.firstName ? charData.firstName.trim() : '';
        data.lastName = charData.lastName ? charData.lastName.trim() : '';
        data.middleName = charData.middleName ? charData.middleName.trim() : '';
        data.nickname = charData.nickname ? charData.nickname.trim() : '';
        data.alias = charData.alias ? charData.alias.trim() : '';

        data.previousNames = Array.isArray(charData.previousNames)
            ? charData.previousNames
                .map(function(n) { return String(n || '').trim(); })
                .filter(function(n) { return n !== ''; })
            : [];

        var incomingDp = charData.displayParts && typeof charData.displayParts === 'object'
            ? charData.displayParts
            : null;

        data.displayParts = {
            first:    incomingDp ? incomingDp.first    !== false : true,
            middle:   incomingDp ? incomingDp.middle   !== false : true,
            last:     incomingDp ? incomingDp.last     !== false : true,
            nickname: incomingDp ? incomingDp.nickname === true  : false,
            alias:    incomingDp ? incomingDp.alias    === true  : false
        };

        if (charData.nameFormat !== undefined) {
            data.nameFormat = charData.nameFormat || 'firstlast';
        }

        // ---- Physical fields ----
        data.gender = charData.gender ? charData.gender.trim() : '';
        data.birthYear = charData.birthYear ? String(charData.birthYear).trim() : '';
        data.eyes = charData.eyes ? charData.eyes.trim() : '';
        data.hair = charData.hair ? charData.hair.trim() : '';
        data.skin = charData.skin ? charData.skin.trim() : '';
        data.height = charData.height ? charData.height.trim() : '';
        data.weight = charData.weight ? charData.weight.trim() : '';
        data.build = charData.build ? charData.build.trim() : '';
        data.appearanceNotes = charData.appearanceNotes ? charData.appearanceNotes.trim() : '';

        // ---- Career / professional fields ----
        data.specialty = charData.specialty ? charData.specialty.trim() : '';
        data.attraction = charData.attraction ? charData.attraction.trim() : '';
        data.sexuality = charData.sexuality ? charData.sexuality.trim() : '';
        data.notes = charData.notes ? charData.notes.trim() : '';
        data.combatNotes = charData.combatNotes ? charData.combatNotes.trim() : '';

        // ---- Academic fields ----
        if (charData.graduatingClassId !== undefined) {
            data.graduatingClassId = charData.graduatingClassId || null;
        }
        if (charData.graduatingClassInstructor !== undefined) {
            data.graduatingClassInstructor = charData.graduatingClassInstructor === true;
        }

        // NOTE: disciplineIds, classIds, and mode are deliberately NOT
        // normalised here. They are owned by dedicated mutations.

        // ---- Stats ----
        data.stats = {};
        for (var i = 0; i < STAT_KEYS.length; i++) {
            var key = STAT_KEYS[i];
            var val = charData.stats && charData.stats[key] !== undefined
                ? charData.stats[key]
                : STAT_DEFAULT;
            var numeric = Number(val);
            if (isNaN(numeric)) { numeric = STAT_DEFAULT; }
            data.stats[key] = Math.max(STAT_MIN, Math.min(STAT_MAX, Math.round(numeric)));
        }

        // ---- Magic ----
        if (charData.magic !== undefined) {
            data.magic = {};
            var MagicConstants = window.MagicConstants;
            var magicKeys = MagicConstants && MagicConstants.getTypeKeys
                ? MagicConstants.getTypeKeys()
                : Object.keys(charData.magic || {});
            var magicMax = MagicConstants && typeof MagicConstants.MAGIC_MAX === 'number'
                ? MagicConstants.MAGIC_MAX
                : 10;
            for (var m = 0; m < magicKeys.length; m++) {
                var mKey = magicKeys[m];
                var rawMagic = charData.magic && charData.magic[mKey] !== undefined
                    ? Number(charData.magic[mKey])
                    : 0;
                if (isNaN(rawMagic)) { rawMagic = 0; }
                data.magic[mKey] = Math.max(0, Math.min(magicMax, Math.round(rawMagic)));
            }
        }

        // ---- HP / MP ----
        var rawHP = charData.hp !== undefined && charData.hp !== null && charData.hp !== ''
            ? Number(charData.hp)
            : 0;
        if (isNaN(rawHP) || rawHP < 0) { rawHP = 0; }
        if (rawHP > HP_HARD_CAP) { rawHP = HP_HARD_CAP; }
        data.hp = Math.round(rawHP);

        var rawMP = charData.mp !== undefined && charData.mp !== null && charData.mp !== ''
            ? Number(charData.mp)
            : 0;
        if (isNaN(rawMP) || rawMP < 0) { rawMP = 0; }
        if (rawMP > MP_HARD_CAP) { rawMP = MP_HARD_CAP; }
        data.mp = Math.round(rawMP);

        // ---- Weapons ----
        if (charData.weapons !== undefined) {
            data.weapons = normaliseWeapons(charData.weapons);
        } else {
            data.weapons = [];
        }

        // ---- Special moves ----
        if (charData.specialMoves !== undefined) {
            data.specialMoves = {
                physical: Array.isArray(charData.specialMoves && charData.specialMoves.physical)
                    ? charData.specialMoves.physical.slice()
                    : [],
                magical: Array.isArray(charData.specialMoves && charData.specialMoves.magical)
                    ? charData.specialMoves.magical.slice()
                    : []
            };
        }

        // ---- Career status ----
        if (charData.careerStatus !== undefined) {
            data.careerStatus = Array.isArray(charData.careerStatus)
                ? charData.careerStatus.slice()
                : [];
        }

        // ---- Personality ----
        if (charData.personality !== undefined) {
            data.personality = charData.personality ? Object.assign({}, charData.personality) : {};
        }

        // ---- Death fields ----
        data.deathYear = charData.deathYear ? String(charData.deathYear).trim() : '';
        data.deathCause = charData.deathCause ? charData.deathCause.trim() : '';

        if (charData.deathWeek !== undefined) {
            data.deathWeek = charData.deathWeek ? String(charData.deathWeek).trim() : '';
        }

        if (charData.deathAge !== undefined &&
            charData.deathAge !== null &&
            String(charData.deathAge).trim() !== '') {
            data.deathAge = String(charData.deathAge).trim();
        } else if (data.deathYear && data.birthYear) {
            var birthY = parseInt(data.birthYear, 10);
            var deathY = parseInt(data.deathYear, 10);
            if (!isNaN(birthY) && !isNaN(deathY) && deathY >= birthY) {
                data.deathAge = String(deathY - birthY);
            } else {
                data.deathAge = '';
            }
        } else {
            data.deathAge = '';
        }

        data.deceased = computeCachedDeceased(data);

        return data;
    }

    // ============================================================
    // SAVE CHARACTER - Uses MutationPipeline
    // ============================================================

    function save(formData) {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        if (!formData || typeof formData !== 'object') {
            return Promise.resolve({
                success: false,
                message: 'Form data is required.'
            });
        }

        var normalised = normaliseCharacterData(formData);
        var validation = validateCharacter(normalised);

        if (!validation.valid) {
            return Promise.resolve({
                success: false,
                message: validation.message
            });
        }

        var editId = formData._editId || null;
        var isEditing = editId !== null && editId !== undefined && editId !== '';

        var existingChar = null;
        var name = normalised.firstName + ' ' + normalised.lastName;

        if (isEditing) {
            existingChar = CharacterQueries.getCharacterById(editId);
            if (!existingChar) {
                return Promise.resolve({
                    success: false,
                    message: 'Character not found.'
                });
            }
            name = CharacterQueries.getDisplayName(existingChar);
        }

        return MutationPipeline.performMutation({
            validate: function() {
                var reValidation = validateCharacter(normalised);
                if (!reValidation.valid) {
                    return { valid: false, message: reValidation.message };
                }
                if (isEditing) {
                    var currentChar = CharacterQueries.getCharacterById(editId);
                    if (!currentChar) {
                        return { valid: false, message: 'Character no longer exists.' };
                    }
                }
                return { valid: true };
            },
            mutate: function(data) {
                var result;
                if (isEditing) {
                    result = updateExistingCharacter(existingChar, normalised, data);
                } else {
                    result = createNewCharacter(normalised, data);
                }
                if (!result.success) {
                    throw new Error(result.error || 'Failed to save character.');
                }
                return {
                    id: result.id,
                    character: result.character,
                    isNew: !isEditing
                };
            },
            logMessage: function() {
                return isEditing
                    ? 'Updated character: ' + name
                    : 'Created character: ' + name;
            },
            successMessage: function() {
                return isEditing
                    ? 'Character updated successfully!'
                    : 'Character created successfully!';
            },
            failureMessage: 'Failed to save character.'
        });
    }

    // ============================================================
    // MUTATION HELPERS - Called within pipeline
    // ============================================================

    function updateExistingCharacter(existing, normalised, data) {
        var index = data.characters.findIndex(function(c) {
            return c && String(c.id) === String(existing.id);
        });

        if (index === -1) {
            return { success: false, error: 'Character not found in data store.' };
        }

        var current = data.characters[index];

        // Preserve system-managed fields.
        //   - classIds:      owned by AcademyClasses.
        //   - mode:          owned by CharacterCRUD.setMode.
        //   - eliminations / eliminatedWeeks: owned by AcademyEliminations
        //                    and TournamentEliminationCascade.
        //   - disciplineIds: legacy field. If present on the record, it
        //                    is preserved verbatim, but nothing reads it.
        var preserved = {
            id: current.id,
            createdAt: current.createdAt,
            classIds: Array.isArray(current.classIds) ? current.classIds.slice() : [],
            mode: (current.mode === 'student' || current.mode === 'instructor')
                ? current.mode
                : DEFAULT_MODE,
            eliminations: Array.isArray(current.eliminations) ? current.eliminations.slice() : [],
            eliminatedWeeks: Array.isArray(current.eliminatedWeeks) ? current.eliminatedWeeks.slice() : []
        };

        if (Array.isArray(current.disciplineIds)) {
            preserved.disciplineIds = current.disciplineIds.slice();
        }

        var updated = Object.assign({}, current, normalised, preserved);

        data.characters[index] = updated;

        // ---- Death → professional team cascade ----
        //
        // Trigger: deathYear transitions from blank to a parseable
        // year. A save that changes deathYear from one non-blank
        // year to another does NOT re-end stints; they were already
        // ended on the first transition.
        //
        // Scope: professional teams only. See the file header.
        //
        // Non-reversible: clearing deathYear does not restore the
        // ended stints. The user reopens them from the member
        // manager if they want to undo a death.
        //
        // TeamCore is OPTIONAL. Absent or older load order → skip
        // silently.
        var previousDeathYear = parseDeathYear(current.deathYear);
        var nextDeathYear = parseDeathYear(updated.deathYear);

        if (previousDeathYear === null && nextDeathYear !== null) {
            var TeamCore = getTeamCore();
            if (TeamCore &&
                typeof TeamCore.endStintsForCharacter === 'function') {
                TeamCore.endStintsForCharacter(
                    data,
                    updated.id,
                    nextDeathYear
                );
            }
        }

        return {
            success: true,
            id: updated.id,
            character: updated
        };
    }

    function createNewCharacter(normalised, data) {
        var id = IdUtils.generateId('char');

        var newChar = Object.assign({}, normalised, {
            id: id,
            classIds: [],
            mode: DEFAULT_MODE,
            hp: normalised.hp || 0,
            mp: normalised.mp || 0,
            weapons: Array.isArray(normalised.weapons) ? normalised.weapons : [],
            combatNotes: normalised.combatNotes || '',
            eliminations: [],
            eliminatedWeeks: [],
            createdAt: new Date().toISOString()
        });

        data.characters.push(newChar);

        return {
            success: true,
            id: id,
            character: newChar
        };
    }

    // ============================================================
    // SET MODE - Uses MutationPipeline
    // ============================================================
    //
    // The character mode is a DOMAIN FACT: 'student' or 'instructor'.
    // It drives which tabs the Academy character detail panel renders
    // and how the character's enrolments are interpreted.
    //
    // It is deliberately NOT settable through save(). The generic
    // save path preserves whatever mode is on the record. This
    // mirrors the classIds and disciplineIds rule: fields owned by a
    // dedicated mutation are not touched by generic save.
    //
    // NO SIDE EFFECTS. Flipping mode does not:
    //   - Clear or reassign enrolments.
    //   - Touch teaching groups.
    //   - Touch exam sequences.
    //   - Cascade into any other store.
    //
    // If the mode ever needs to trigger side effects, they are added
    // here, in one place, rather than scattered across call sites.

    function setMode(charId, mode) {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        if (!charId) {
            return Promise.resolve({
                success: false,
                message: 'Character ID is required.'
            });
        }

        if (!isValidMode(mode)) {
            return Promise.resolve({
                success: false,
                message: 'Invalid mode. Must be one of: ' + VALID_MODES.join(', ') + '.'
            });
        }

        var targetId = String(charId);

        var char = CharacterQueries.getCharacterById(targetId);
        if (!char) {
            return Promise.resolve({
                success: false,
                message: 'Character not found.'
            });
        }

        var currentMode = (char.mode === 'student' || char.mode === 'instructor')
            ? char.mode
            : DEFAULT_MODE;

        if (currentMode === mode) {
            return Promise.resolve({
                success: true,
                data: {
                    characterId: targetId,
                    mode: mode,
                    changed: false
                }
            });
        }

        var name = CharacterQueries.getDisplayName(char);

        return MutationPipeline.performMutation({
            validate: function() {
                var currentChar = CharacterQueries.getCharacterById(targetId);
                if (!currentChar) {
                    return { valid: false, message: 'Character no longer exists.' };
                }
                return { valid: true };
            },
            mutate: function(data) {
                if (!Array.isArray(data.characters)) {
                    throw new Error('Character store is not available.');
                }

                var found = null;
                for (var i = 0; i < data.characters.length; i++) {
                    var c = data.characters[i];
                    if (c && String(c.id) === targetId) {
                        found = c;
                        break;
                    }
                }

                if (!found) {
                    throw new Error('Character not found in data store.');
                }

                found.mode = mode;
                found.updatedAt = new Date().toISOString();

                return {
                    characterId: targetId,
                    mode: mode,
                    changed: true
                };
            },
            logMessage: function(result) {
                var label = mode === 'instructor' ? 'instructor' : 'student';
                return 'Set ' + name + ' to ' + label + ' mode';
            },
            successMessage: function(result) {
                var label = mode === 'instructor' ? 'Instructor' : 'Student';
                return label + ' mode enabled.';
            },
            failureMessage: 'Failed to set character mode.'
        });
    }

    // ============================================================
    // DELETE CHARACTER - Uses MutationPipeline
    // ============================================================
    //
    // Cascade orchestration:
    //   - Cross-domain cleanup (enrolments, grades, rankings, social
    //     scores, weekly teams, auto-groups, social, missions,
    //     tournaments) routes through AcademyCascade.characterDeleted.
    //   - Character-side cleanup (team entity rosters, curriculum
    //     schedules / rest days / metadata) stays inline.

    function stripCharacterFromCurriculum(curriculum, charId) {
        var result = {
            scheduleEntriesRemoved: 0,
            restDaysEntriesRemoved: 0,
            metadataEntriesPruned: 0
        };

        if (!curriculum || typeof curriculum !== 'object' || !charId) {
            return result;
        }

        var target = String(charId);

        if (curriculum.schedules &&
            typeof curriculum.schedules === 'object' &&
            !Array.isArray(curriculum.schedules)) {
            if (curriculum.schedules[target] !== undefined) {
                delete curriculum.schedules[target];
                result.scheduleEntriesRemoved = 1;
            }
        }

        if (curriculum.restDays &&
            typeof curriculum.restDays === 'object' &&
            !Array.isArray(curriculum.restDays)) {
            if (curriculum.restDays[target] !== undefined) {
                delete curriculum.restDays[target];
                result.restDaysEntriesRemoved = 1;
            }
        }

        if (curriculum.metadata &&
            typeof curriculum.metadata === 'object' &&
            !Array.isArray(curriculum.metadata)) {
            var prefix = target + '_';
            var keysToRemove = [];

            Object.keys(curriculum.metadata).forEach(function(key) {
                if (String(key).indexOf(prefix) === 0) {
                    keysToRemove.push(key);
                }
            });

            for (var i = 0; i < keysToRemove.length; i++) {
                delete curriculum.metadata[keysToRemove[i]];
            }

            result.metadataEntriesPruned = keysToRemove.length;
        }

        return result;
    }

    function deleteCharacter(id) {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        if (!id) {
            return Promise.resolve({
                success: false,
                message: 'Character ID is required.'
            });
        }

        var targetId = String(id);

        var char = CharacterQueries.getCharacterById(targetId);
        if (!char) {
            return Promise.resolve({
                success: false,
                message: 'Character not found.'
            });
        }

        var name = CharacterQueries.getDisplayName(char);

        return MutationPipeline.performMutation({
            validate: function() {
                var currentChar = CharacterQueries.getCharacterById(targetId);
                if (!currentChar) {
                    return { valid: false, message: 'Character no longer exists.' };
                }
                return { valid: true };
            },
            mutate: function(data) {
                var cascade = {
                    teamMembershipsRemoved: 0,
                    curriculum: null,
                    academyCascade: null
                };

                // ---- Character-side: team entity rosters ----
                if (Array.isArray(data.teams)) {
                    data.teams.forEach(function(team) {
                        if (!team || !Array.isArray(team.members)) {
                            return;
                        }
                        var before = team.members.length;
                        team.members = team.members.filter(function(m) {
                            return !m || String(m.characterId) !== targetId;
                        });
                        cascade.teamMembershipsRemoved += before - team.members.length;
                    });
                }

                // ---- Cross-domain: academy cascade ----
                var Cascade = getAcademyCascade();
                if (Cascade && typeof Cascade.characterDeleted === 'function') {
                    cascade.academyCascade = Cascade.characterDeleted(data, targetId);
                }

                // ---- Character-side: curriculum ----
                if (data.curriculum && typeof data.curriculum === 'object') {
                    cascade.curriculum = stripCharacterFromCurriculum(data.curriculum, targetId);
                }

                // ---- Remove the character entity itself ----
                var found = false;
                data.characters = data.characters.filter(function(c) {
                    if (c && String(c.id) === targetId) {
                        found = true;
                        return false;
                    }
                    return true;
                });

                if (!found) {
                    throw new Error('Character not found in data store.');
                }

                return {
                    deleted: true,
                    cascade: cascade
                };
            },
            logMessage: function(result) {
                var c = result.cascade || {};
                var details = [];

                if (c.teamMembershipsRemoved > 0) {
                    details.push(c.teamMembershipsRemoved + ' team membership(s)');
                }

                if (c.academyCascade) {
                    var Cascade = getAcademyCascade();
                    if (Cascade && typeof Cascade.formatSummary === 'function') {
                        var summary = Cascade.formatSummary(c.academyCascade);
                        if (summary) {
                            details.push(summary.replace(/^\(|\)$/g, ''));
                        }
                    }
                }

                if (c.curriculum) {
                    var cur = c.curriculum;
                    var curTotal = cur.scheduleEntriesRemoved +
                                   cur.restDaysEntriesRemoved +
                                   cur.metadataEntriesPruned;
                    if (curTotal > 0) {
                        details.push(curTotal + ' curriculum reference(s)');
                    }
                }

                var suffix = details.length > 0
                    ? ' (' + details.join(', ') + ')'
                    : '';

                return 'Deleted character: ' + name + suffix;
            },
            successMessage: 'Character deleted successfully!',
            failureMessage: 'Failed to delete character.'
        });
    }

    // ============================================================
    // BULK OPERATIONS
    // ============================================================

    function deleteAllCharacters() {
        if (!checkDependencies()) {
            return Promise.resolve({
                success: false,
                message: 'Dependencies not loaded. Please refresh the page.'
            });
        }

        if (!confirm('Delete ALL characters permanently? This cannot be undone.')) {
            return Promise.resolve({
                success: false,
                message: 'Operation cancelled.'
            });
        }

        return MutationPipeline.performMutation({
            validate: function(data) {
                var count = Array.isArray(data.characters) ? data.characters.length : 0;
                if (count === 0) {
                    return { valid: false, message: 'No characters to delete.' };
                }
                return { valid: true };
            },
            mutate: function(data) {
                var count = Array.isArray(data.characters) ? data.characters.length : 0;

                if (Array.isArray(data.teams)) {
                    data.teams.forEach(function(team) {
                        if (Array.isArray(team.members)) {
                            team.members = [];
                        }
                    });
                }

                data.characters = [];

                return { deletedCount: count };
            },
            logMessage: function(result) {
                return 'Deleted all characters (' + result.deletedCount + ')';
            },
            successMessage: function(result) {
                return 'Deleted ' + result.deletedCount + ' characters.';
            },
            failureMessage: 'Failed to delete all characters.'
        });
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.CharacterCRUD = Object.freeze({
        save: save,
        delete: deleteCharacter,
        deleteAll: deleteAllCharacters,

        setMode: setMode,

        validateCharacter: validateCharacter,
        normaliseCharacterData: normaliseCharacterData,

        VALID_MODES: Object.freeze(VALID_MODES.slice()),
        DEFAULT_MODE: DEFAULT_MODE
    });

})();
