/**
 * js/modules/missions/mission-id.js - Mission ID Utilities
 *
 * Path: js/modules/missions/mission-id.js
 *
 * Pure utilities for the human-facing mission label.
 *
 * WHAT THIS MODULE OWNS:
 *   - The label grammar: YEAR-SEQ-DIFFICULTY (e.g. 2026-005-E).
 *   - Year validation (unbounded positive integers).
 *   - Sequence allocation for a new mission within (year, difficulty).
 *   - Label generation (assigned at creation).
 *   - Label derivation from a mission record (recomputed on read).
 *   - Label parsing.
 *   - Label canonicalisation.
 *
 * WHAT THIS MODULE DOES NOT OWN:
 *   - The canonical UUID stored on the mission as `id`. That is
 *     generated by IdUtils and stored by MissionCore. MissionId
 *     knows nothing about it.
 *   - Cross-domain references. Every reference in the app uses the
 *     UUID. The label is a display string and is never a foreign
 *     key.
 *   - Queries. `existingMissions` is supplied by the caller.
 *   - Storage. This module never touches window.data.
 *   - Presentation formatting beyond the raw label. Views layer
 *     decides how to render the label in a UI.
 *   - Validation of mission records. MissionSchema owns that.
 *
 * LABEL GRAMMAR:
 *
 *     YEAR '-' SEQ '-' DIFFICULTY
 *
 *   YEAR       unbounded positive integer, min width 4 digits.
 *   SEQ        positive integer, min width 3 digits, scoped to
 *              (year, difficulty). Never reused, never decremented.
 *   DIFFICULTY single-letter code (E / M / H / X), from
 *              MissionConstants.DIFFICULTY_CODES.
 *
 *   Examples: 2026-005-E, 2026-012-M, 25000-003-X, 1-001-H.
 *
 * WHY THE LABEL IS DERIVED, NOT STORED:
 *
 *   The label is a function of (year, sequence, difficulty). All
 *   three live on the mission record. Storing the label would create
 *   a second source of truth and drift the moment any input changes.
 *
 *   `sequence` IS stored, because it is a fact about the mission
 *   ("this was the 5th Easy mission of 2026 when it was created")
 *   and cannot be recomputed after the fact. The year and difficulty
 *   can be edited by the user; when they are, the label changes
 *   accordingly. That is the intended behaviour: the label describes
 *   the mission's current (year, sequence, difficulty), not its
 *   original values.
 *
 * YEAR SEMANTICS:
 *   Years are UNBOUNDED positive integers. There is no MIN_YEAR or
 *   MAX_YEAR. Any integer >= 1 is valid. `undefined` and `null`
 *   mean "current calendar year" when a caller is generating a new
 *   label. Any other invalid value is rejected; the module never
 *   silently substitutes the current year for a bad value.
 *
 * SEQUENCE ALLOCATION:
 *   Sequences are MONOTONIC and NON-REUSABLE within a
 *   (year, difficulty) scope. `generate()` returns
 *   `max(sequence) + 1` across existing missions with the same year
 *   and difficulty. If no mission exists, it returns 1. A gap left
 *   by an archived mission is never filled.
 *
 *   This preserves the historical-record principle: a label that
 *   has been used to identify a mission is never reassigned to a
 *   different mission.
 *
 * UNIQUENESS:
 *   The label is NOT a foreign key. Two missions with the same label
 *   cannot be created (sequence is monotonic per scope), but nothing
 *   in the app relies on the label being unique for lookups.
 *   Lookups use the UUID.
 *
 * DEPENDENCIES (MANDATORY):
 *   - window.MissionConstants
 *
 * DEPENDENCIES (NONE):
 *   No queries, no storage, no other mission modules.
 */

(function() {
    'use strict';

    if (window.__missionIdLoaded) {
        return;
    }

    // ============================================================
    // MANDATORY DEPENDENCIES
    // ============================================================

    var MissionConstants = window.MissionConstants;

    var _missing = [];

    if (!MissionConstants) {
        _missing.push('MissionConstants (module)');
    } else {
        if (!Array.isArray(MissionConstants.VALID_DIFFICULTIES)) {
            _missing.push('MissionConstants.VALID_DIFFICULTIES');
        }
        if (!MissionConstants.DIFFICULTY_CODES ||
            typeof MissionConstants.DIFFICULTY_CODES !== 'object') {
            _missing.push('MissionConstants.DIFFICULTY_CODES');
        }
        if (!MissionConstants.DIFFICULTY_FROM_CODE ||
            typeof MissionConstants.DIFFICULTY_FROM_CODE !== 'object') {
            _missing.push('MissionConstants.DIFFICULTY_FROM_CODE');
        }
        if (typeof MissionConstants.LABEL_YEAR_MIN_WIDTH !== 'number') {
            _missing.push('MissionConstants.LABEL_YEAR_MIN_WIDTH');
        }
        if (typeof MissionConstants.LABEL_SEQUENCE_MIN_WIDTH !== 'number') {
            _missing.push('MissionConstants.LABEL_SEQUENCE_MIN_WIDTH');
        }
        if (typeof MissionConstants.LABEL_SEPARATOR !== 'string' ||
            MissionConstants.LABEL_SEPARATOR === '') {
            _missing.push('MissionConstants.LABEL_SEPARATOR');
        }
    }

    if (_missing.length > 0) {
        throw new Error(
            '[MissionId] Missing mandatory dependencies: ' +
            _missing.join(', ')
        );
    }

    window.__missionIdLoaded = true;

    // ============================================================
    // SHORTHAND IMPORTS
    // ============================================================

    var DIFFICULTY_CODES = MissionConstants.DIFFICULTY_CODES;
    var DIFFICULTY_FROM_CODE = MissionConstants.DIFFICULTY_FROM_CODE;
    var VALID_DIFFICULTIES = MissionConstants.VALID_DIFFICULTIES;
    var YEAR_WIDTH = MissionConstants.LABEL_YEAR_MIN_WIDTH;
    var SEQ_WIDTH = MissionConstants.LABEL_SEQUENCE_MIN_WIDTH;
    var SEP = MissionConstants.LABEL_SEPARATOR;

    // ============================================================
    // HELPERS
    // ============================================================

    function isNonEmptyString(value) {
        return typeof value === 'string' && value.trim() !== '';
    }

    function isPlainObject(value) {
        return value !== null &&
               typeof value === 'object' &&
               !Array.isArray(value);
    }

    function pad(value, width) {
        var str = String(value);
        while (str.length < width) {
            str = '0' + str;
        }
        return str;
    }

    function currentYear() {
        return new Date().getFullYear();
    }

    function isValidDifficulty(difficulty) {
        return VALID_DIFFICULTIES.indexOf(difficulty) !== -1;
    }

    // ============================================================
    // YEAR VALIDATION
    // ============================================================

    /**
     * Validate a year value.
     *
     * Years are UNBOUNDED positive integers. Any integer >= 1 is
     * valid. This function does NOT accept `undefined` or `null` as
     * "current year"; that decision belongs to `generate()`, which
     * has explicit knowledge of the calling context.
     *
     * @param {*} value
     * @returns {number|null} Parsed year, or null if invalid
     */
    function isValidYear(value) {
        if (value === undefined || value === null || value === '') {
            return null;
        }

        if (typeof value === 'number') {
            if (!Number.isInteger(value) || value < 1) {
                return null;
            }
            if (!Number.isSafeInteger(value)) {
                return null;
            }
            return value;
        }

        if (typeof value === 'string') {
            var trimmed = value.trim();
            if (trimmed === '' || !/^\d+$/.test(trimmed)) {
                return null;
            }
            var num = Number(trimmed);
            if (!Number.isSafeInteger(num) || num < 1) {
                return null;
            }
            return num;
        }

        return null;
    }

    /**
     * Resolve a year for generation: explicit value, or current year
     * if the input is genuinely absent.
     *
     * Distinguishes:
     *   undefined / null  -> current year
     *   invalid value     -> null (caller rejects)
     *
     * @returns {number|null}
     */
    function resolveYearForGeneration(value) {
        if (value === undefined || value === null || value === '') {
            return currentYear();
        }
        return isValidYear(value);
    }

    // ============================================================
    // LABEL CONSTRUCTION
    // ============================================================

    /**
     * Build a label from resolved year, sequence, and difficulty.
     * Pure. Callers must have already validated the components.
     *
     * @returns {string}
     */
    function buildLabel(year, sequence, difficulty) {
        var code = DIFFICULTY_CODES[difficulty];
        return pad(year, YEAR_WIDTH) + SEP +
               pad(sequence, SEQ_WIDTH) + SEP +
               code;
    }

    // ============================================================
    // SEQUENCE ALLOCATION
    // ============================================================

    /**
     * Find the next available sequence number for a (year, difficulty)
     * scope, across a list of existing missions.
     *
     * MONOTONIC and NON-REUSABLE: returns max(sequence) + 1, or 1
     * when the scope has no missions. Gaps are never filled.
     *
     * Only considers missions whose `sequence` is a valid positive
     * integer and whose `year` and `difficulty` match the target
     * scope. Malformed missions in the input are ignored, not
     * repaired.
     *
     * @param {array} existingMissions - Live or cloned mission records
     * @param {number} targetYear
     * @param {string} targetDifficulty
     * @returns {number} Next sequence number (>= 1)
     */
    function findNextSequence(existingMissions, targetYear, targetDifficulty) {
        if (!Array.isArray(existingMissions)) {
            return 1;
        }

        var maxSeq = 0;

        for (var i = 0; i < existingMissions.length; i++) {
            var m = existingMissions[i];
            if (!isPlainObject(m)) { continue; }

            var mYear = isValidYear(m.year);
            if (mYear !== targetYear) { continue; }

            if (m.difficulty !== targetDifficulty) { continue; }

            var mSeq = m.sequence;
            if (typeof mSeq !== 'number' ||
                !Number.isInteger(mSeq) ||
                mSeq < 1) {
                continue;
            }

            if (mSeq > maxSeq) {
                maxSeq = mSeq;
            }
        }

        return maxSeq + 1;
    }

    // ============================================================
    // GENERATE
    // ============================================================

    /**
     * Generate a mission label for a new mission.
     *
     * @param {number|null|undefined} year - The mission's year. When
     *   undefined or null, the current calendar year is used.
     *   When provided, it must be a valid positive integer; an
     *   invalid value is rejected (returns null), never silently
     *   replaced by the current year.
     * @param {string} difficulty - One of VALID_DIFFICULTIES.
     *   Required. Invalid values are rejected, never defaulted.
     * @param {array} existingMissions - Existing mission records.
     *   Used to compute the next sequence number within
     *   (year, difficulty). Malformed records are ignored.
     * @returns {object|null}
     *   { label, year, sequence, difficulty } or null on invalid input
     */
    function generate(year, difficulty, existingMissions) {
        var resolvedYear = resolveYearForGeneration(year);
        if (resolvedYear === null) {
            return null;
        }

        if (!isValidDifficulty(difficulty)) {
            return null;
        }

        var sequence = findNextSequence(
            existingMissions || [],
            resolvedYear,
            difficulty
        );

        return {
            label: buildLabel(resolvedYear, sequence, difficulty),
            year: resolvedYear,
            sequence: sequence,
            difficulty: difficulty
        };
    }

    // ============================================================
    // DERIVE
    // ============================================================

    /**
     * Derive the label from a mission record.
     *
     * The mission must carry `year`, `sequence`, and `difficulty`
     * as valid values. This function does NOT consult any storage;
     * it computes the label from the record it is given.
     *
     * When the mission is invalid (missing or malformed components),
     * returns null. The caller decides how to render an unavailable
     * label.
     *
     * @param {object} mission
     * @returns {string|null}
     */
    function derive(mission) {
        if (!isPlainObject(mission)) {
            return null;
        }

        var year = isValidYear(mission.year);
        if (year === null) { return null; }

        var sequence = mission.sequence;
        if (typeof sequence !== 'number' ||
            !Number.isInteger(sequence) ||
            sequence < 1 ||
            !Number.isSafeInteger(sequence)) {
            return null;
        }

        var difficulty = mission.difficulty;
        if (!isValidDifficulty(difficulty)) {
            return null;
        }

        return buildLabel(year, sequence, difficulty);
    }

    // ============================================================
    // PARSE
    // ============================================================

    /**
     * Parse a mission label into its components.
     *
     * Enforces the canonical grammar strictly:
     *   - The year segment must be pure digits, no leading '+',
     *     no decimals, no signs.
     *   - The sequence segment must be pure digits.
     *   - The difficulty segment must be a single known code.
     *   - Segments are separated by exactly one SEP character.
     *
     * The parser does NOT require the year or sequence segments to
     * be padded to their minimum widths. `2026-5-E` and `2026-005-E`
     * parse to the same components. Canonicalisation (`format`) is a
     * separate concern.
     *
     * @param {string} label
     * @returns {object|null}
     *   { year, sequence, difficulty, difficultyCode } or null
     */
    function parse(label) {
        if (!isNonEmptyString(label)) {
            return null;
        }

        var parts = label.trim().split(SEP);
        if (parts.length !== 3) {
            return null;
        }

        var yearStr = parts[0];
        var seqStr = parts[1];
        var codeStr = parts[2];

        if (!/^\d+$/.test(yearStr)) { return null; }
        if (!/^\d+$/.test(seqStr)) { return null; }

        var year = Number(yearStr);
        if (!Number.isSafeInteger(year) || year < 1) { return null; }

        var sequence = Number(seqStr);
        if (!Number.isSafeInteger(sequence) || sequence < 1) { return null; }

        if (codeStr.length !== 1) { return null; }
        var difficulty = DIFFICULTY_FROM_CODE[codeStr];
        if (!difficulty) { return null; }

        return {
            year: year,
            sequence: sequence,
            difficulty: difficulty,
            difficultyCode: codeStr
        };
    }

    /**
     * Is the label well-formed?
     *
     * @param {string} label
     * @returns {boolean}
     */
    function isValid(label) {
        return parse(label) !== null;
    }

    // ============================================================
    // FORMAT
    // ============================================================

    /**
     * Canonicalise a label to its padded form.
     *
     *     "2026-5-E" -> "2026-005-E"
     *
     * Returns null for invalid input. Does not fabricate a valid
     * label; it only reformats a label that already parses.
     *
     * @param {string} label
     * @returns {string|null}
     */
    function format(label) {
        var parsed = parse(label);
        if (parsed === null) {
            return null;
        }
        return buildLabel(
            parsed.year,
            parsed.sequence,
            parsed.difficulty
        );
    }

    // ============================================================
    // EXPOSE
    // ============================================================

    window.MissionId = {
        // Generation
        generate: generate,

        // Derivation
        derive: derive,

        // Parsing
        parse: parse,
        isValid: isValid,
        format: format,

        // Year validation (used by MissionSchema and MissionRules)
        isValidYear: isValidYear,

        // Internal-ish helpers, exposed for testing and for callers
        // that need the raw pieces. These are pure and side-effect
        // free.
        findNextSequence: findNextSequence
    };

    // ============================================================
    // VERIFICATION
    // ============================================================

    (function verify() {
        var exports = window.MissionId;
        var missing = [];

        var required = [
            'generate',
            'derive',
            'parse',
            'isValid',
            'format',
            'isValidYear',
            'findNextSequence'
        ];

        for (var i = 0; i < required.length; i++) {
            if (typeof exports[required[i]] !== 'function') {
                missing.push(required[i]);
            }
        }

        // Smoke test: the parse/format round trip must be stable.
        try {
            var sample = format('2026-5-E');
            if (sample !== '2026-005-E') {
                missing.push('format("2026-5-E") !== "2026-005-E"');
            }

            var parsed = parse('2026-005-E');
            if (!parsed ||
                parsed.year !== 2026 ||
                parsed.sequence !== 5 ||
                parsed.difficulty !== 'easy') {
                missing.push('parse("2026-005-E") returned wrong shape');
            }

            var derived = derive({
                year: 2026,
                sequence: 5,
                difficulty: 'easy'
            });
            if (derived !== '2026-005-E') {
                missing.push('derive() returned wrong label');
            }

            var generated = generate(2026, 'easy', []);
            if (!generated ||
                generated.label !== '2026-001-E' ||
                generated.sequence !== 1) {
                missing.push('generate() on empty list returned wrong shape');
            }

            var generatedWithGap = generate(2026, 'easy', [
                { year: 2026, sequence: 3, difficulty: 'easy' },
                { year: 2026, sequence: 7, difficulty: 'easy' },
                { year: 2026, sequence: 2, difficulty: 'medium' }
            ]);
            if (!generatedWithGap || generatedWithGap.sequence !== 8) {
                missing.push(
                    'generate() did not pick max(sequence) + 1 ' +
                    '(expected 8, got ' +
                    (generatedWithGap ? generatedWithGap.sequence : 'null') +
                    ')'
                );
            }
        } catch (e) {
            missing.push('smoke test threw: ' + e.message);
        }

        if (missing.length > 0) {
            console.warn(
                '[MissionId] Verification failed - ' +
                'some exports may be missing or broken:',
                missing.join(', ')
            );
        }
    })();

})();
